### ISSUE TITLE
XEP-0363: HTTP File Upload

### ISSUE THREAD

**Issue by anurodhp** [anurodhp/Monal#1]
http://xmpp.org/extensions/xep-0363.html

**Comment by tristan-k** [comment]
I'm having issues using this. I'm not sure if is related to my SSL-Certificate, but httpupload is working with Conversations on Android. So I assume it's caused by Monal.

![monal_httpupload](https://cloud.githubusercontent.com/assets/732025/13744089/f437c908-e9e5-11e5-907f-c4f0cc43727f.jpeg)

**Comment by andersruneson** [comment]
@tristan-k I have the exact same issue (except with jabber.at), I created issue #29.

**Comment by anurodhp** [comment]
As posted in in #29 
--
iOS is incredibly strict about HTTP connections. The errors seen are OS error messages. HTTP will never be supported as Apple doesn't really allow non HTTPS connections anymore without compromising the security of the app for everyone. In the case of HTTPS, it is strict about checking the certificate. If the OS suspects the connection is insecure (e.g TLS <1.2 ), it will not allow it. There is a checklist of criteria on this post here:
http://stackoverflow.com/questions/31231696/ios-9-ats-ssl-error-with-supporting-server

If you visit the same URL in safari does it still work or do you see an error message?

**Comment by Mrfuyu** [comment]
@anurodhp You wrote in your [blog](https://monal.im/blog/osx-support-http-upload/) you was testing XEP-0363 with Prosody as Server. Did you use the [mod_http_upload](https://modules.prosody.im/mod_http_upload.html) for prosody or an external component? If you used the mod then is it handling the SSL request by itself or did you configure e.g. Apache to handle this?
I use simply the mod_http_upload from Prosody with a certificate from Let's Encrypt but i also get this error.

**Comment by Mrfuyu** [comment]
@anurodhp You wrote in your [blog](https://monal.im/blog/osx-support-http-upload/) that you was testing XEP-0363 with [Prosody](http://prosody.im/) as Server. Did you use the [mod_http_upload](https://modules.prosody.im/mod_http_upload.html) for prosody or an external component like the [HttpUploadComponent](https://github.com/siacs/HttpUploadComponent)? If you used the mod then is it handling the SSL request by itself or did you configure e.g. Apache to handle this?
I use simply the mod_http_upload from Prosody with a certificate from Let's Encrypt and i also get this error. Viewing a sent picture in Safari is possible.

I testet my https://domain.tld:5281 with  
[Free SSL Server Test by htbridge.com](https://www.htbridge.com/ssl/) and got 

> SUPPORTED PROTOCOLS
> TLSv1.0Good configuration
> TLSv1.1Good configuration
> TLSv1.2Good configuration
>
> 
> SUPPORTED CIPHERS
> TLS_RSA_WITH_AES_128_CBC_SHAGood configuration
> TLS_RSA_WITH_AES_256_CBC_SHAGood configuration
> TLS_RSA_WITH_CAMELLIA_128_CBC_SHAGood configuration
> TLS_RSA_WITH_CAMELLIA_256_CBC_SHAGood configuration
> TLS_RSA_WITH_AES_128_CBC_SHA256Good configuration
> TLS_RSA_WITH_AES_256_CBC_SHA256Good configuration
> TLS_RSA_WITH_AES_128_GCM_SHA256Good configuration
> TLS_RSA_WITH_AES_256_GCM_SHA384Good configuration
