### ISSUE TITLE
Remove notification + mark as read on multi-client message

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#103]
When I use two clients (Desktop and phone), I want my phone to reset the "unread" counters on messages that I read and answered to from the phone.

When Monal receives a 'sent' carbon (not a 'received' one!), it should:
* remove the notification of the respective chat
* reset the message counter for that chat to 0
* reduce the message counter badge on Monal

In the future, it would also great to silence/delay Monal/mobile notifications if there was recent activity on the Desktop, cf. https://github.com/pfleidi/yaxim/issues/114#issuecomment-377780351

**Comment by Echolon** [comment]
Are there acutally any read marking notifications in the chat? Like in Conversations or green ticks?

**Comment by anurodhp** [comment]
Yes read and delivered 

--
Anurodh Pokharel

**Comment by Echolon** [comment]
@tmolitor-stud-tu will this be solved with the recent PR?

**Comment by tmolitor-stud-tu** [comment]
no, but hopefully with the next one ...xep 333 read markers are on my list :)
