### ISSUE TITLE
Minor UI issues on OSX

### ISSUE THREAD

**Issue by eun-ice** [anurodhp/Monal#106]
Hi,

I have some minor suggestions for the UI on OSX

- If I copy something I sent (blue bubble with white text) and insert in another chat, the text is invisible because it is inserted as white on white background. I have to find the quite hidden option to fix the text color, otherwise everything I type stays white

- Sometime text flows out of the chat bubbles, e.g. if you send long urls.

- Having a wider window should increase the size of the chat bubbles.

- Notifications bubbles with number of messages are not shown in "Contacts" list

- If you have a chat open with monal in background and that person sends you messages, the notification bubble counts up. But if you get monal in the foreground you have to click on another chat and back to reset the notification bubble.

Thank you for this outstanding client!

Aron

**Comment by schwindp** [comment]
> Sometime text flows out of the chat bubbles, e.g. if you send long urls.

Happens unfortunately even without long (unwrappable) URLs:

<img width="506" alt="bildschirmfoto 2018-04-21 um 10 25 22" src="https://user-images.githubusercontent.com/187595/39082121-5ba512e2-454e-11e8-980e-0d8cdb95f4a8.png">

The word that partially escapes the bubble is "Blacky". Nothing else in front.

**Comment by anurodhp** [comment]
I believe ive fixed the bubble issue. Will update the beta soon.

**Comment by eun-ice** [comment]
Great, thank you!

**Comment by anurodhp** [comment]
I think the latest App Store release has it fixed.
