### ISSUE TITLE
Feature Request: Multiple windows

### ISSUE THREAD

**Issue by eun-ice** [anurodhp/Monal#107]
Being a user that switched over from Adium, I am used to having one small window with the contact list and a few windows with active chats (either tabbed or separate).

I am sure other user would like that too. Maybe you could consider adding that functionality.

**Comment by d9h20f** [comment]
I doubt a lot of people want a simple chat application to use multiple windows.

**Comment by anurodhp** [comment]
its not impossible, message does both and it could collapse to do it. Really its a matter of time and priorities.

**Comment by eun-ice** [comment]
I understand. I would not recommend implementing this feature request soon, get the current UI perfect and then think about it ;)

**Comment by Echolon** [comment]
@eun-ice This is a macOS only related suggestion right?

**Comment by Echolon** [comment]
I think multiple windows are an outdated feature...

**Comment by foss-** [comment]
@Echolon Agreed, although this feature request is very much one of personal use-case / preference.

Are there other clients besides Adium that have this feature? Beagle, Signal, RocketChat all do not have this feature. Maybe close this issue and see if more requests come in?

**Comment by Echolon** [comment]
Hmm, only Pidgin does it. Even Gajim moved over to unifiying to one window.

I think spliting into windows is bad UI and not in the scope of Monal.

The only thing one could build is a minimalistic mode.

**Comment by Echolon** [comment]
I will close this due to being out of scope.
