### ISSUE TITLE
Not fetching contact list

### ISSUE THREAD

**Issue by da2x** [anurodhp/Monal#11]
Version 1.2 (24) from MAS, OS X 10.11.3.

Client connects okay. From the status light in Preferences: Accounts, it looks like it’s connecting and disconnecting a few times (blinks between red and green light), before settling on connected (green light). My contact list, however, is never fetched and the contacts list is never populated.

**Comment by anurodhp** [comment]
fixed in develop

**Comment by anurodhp** [comment]
fixed in next iOS and OS X releases

**Comment by Aeyoun** [comment]
Not resolved in version 1.3 on the App Store nor in the “latest beta” build found on the website. Are these not new enough?

**Comment by anurodhp** [comment]
Oh. They are the latest. Maybe I'm thinking of a different issue. 

--
Anurodh Pokharel

**Comment by Aeyoun** [comment]
Then please reopen. I’m definitely logged in, but my contact list is entirely empty. Server is latest Prosody.

**Comment by anurodhp** [comment]
Thats very strange it should get either the presence notification and fill the contact list or the roster should download.  Is there anything special about your configuration or is it stock prosody?

**Comment by Aeyoun** [comment]
I have a few modules, but they’re not causing problems for any other clients (I‘ve tested quite a few for an article I’m working on.)

```
pidfile = "/var/run/prosody.pid"
prosodyctl_timeout = 60
admins = { }
plugin_paths = { "/root/prosody-modules" }
modules_enabled = {
	"roster"; -- Allow users to have a roster. Recommended ;)
	"saslauth"; -- Authentication for clients and servers. Recommended if you want to log in.
	"tls"; -- Add support for secure TLS on c2s/s2s connections
	"dialback"; -- s2s dialback support
	"disco"; -- Service discovery
	"private"; -- Private XML storage (for room bookmarks, etc.)
	"vcard"; -- Allow users to set vCards
	"carbons";
	"mam";
	"smacks";
	"ipcheck";
	"csi";
	"throttle_presence";
	"filter_chatstates";
	"http";
	"privacy"; -- Support privacy lists
	"compression"; -- Stream compression
	"version"; -- Replies to server version requests
	"uptime"; -- Report how long server has been running
	"time"; -- Let others know the time here on this server
	"ping"; -- Replies to XMPP pings with pongs
	"pep"; -- Enables users to publish their mood, activity, playing music and more
	"register"; -- Allow users to register on this server using a client and change passwords
	"posix"; -- POSIX functionality, sends server to background, enables syslog, etc.
};
allow_registration = false;
ssl = {
	key = "/usr/local/etc/prosody/certs/self-ca.key";
	certificate = "/usr/local/etc/prosody/certs/xmpp-priv-no.crt";
}
c2s_require_encryption = true
s2s_secure_auth = false
authentication = "internal_plain"
log = {
	"*console"; -- Log to the console, useful for debugging with daemonize=false
}
https_ports = { 5281 }
https_interfaces = { "*" }

VirtualHost "xmpp.priv.no"
archive_expires_after = "10d"
smacks_hibernation_time = "270"
Component "web.xmpp.priv.no" "http_upload"
http_upload_file_size_limit = 1000 * 1024 * 1024
```

**Comment by anurodhp** [comment]
This is weird. It doesn't happen with the prosody server i test it with. Could you open the OS X console and filter for monal and see if there are any errors reported there?
