### ISSUE TITLE
Online & offline contacts not showing

### ISSUE THREAD

**Issue by jitendra129** [anurodhp/Monal#113]
Hi 
I have completed my account setup using XMPP and got success
Jid=xxxxxxxxxxx
pass=xxxx
server=xxxx.xxx.xxx
But i am not able to get online/offline contacts
whenever i am going to create contact it is asking for permission
Please help me 

Thanks
Jitendra Kumar

**Comment by anurodhp** [comment]
This should be fixed by the latest release. please reopen if it isn't.
