### ISSUE TITLE
"Approve Contact" dialog on start doesn't even work (iOS, build 269)

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#116]
When starting the app with pending subscirption requests, I need to manually decide yes/no on each of those requests, until all are completed. Even worse, tapping "no" doesn't actually remove that contact from my pending list on my other device, so this looks like it's not properly responding to the server.

Please change this to be a non-modal feature (have the pending contacts at the top of the contact list or some such), and please also have a "deny all" button :)

Being a victim of XMPP spammers, this might be a rather long process (screenshot from another client):
<img src="https://user-images.githubusercontent.com/165635/40834313-bcd2e33e-6590-11e8-9b03-fdca4632cfca.png" width="300">

**Comment by Echolon** [comment]
@ge0rg can you confirm this is still an issue?

**Comment by Echolon** [comment]
Okay I think one thing that Monal needs to improve is to show that there are actually pending requests.

However, I lag the technical knowledge to evaluate on the problem. But I have an iPhone for testing purposes with the Monal Alpha an can offer Debug logs, if it helps @tmolitor-stud-tu @ge0rg

**Comment by tmolitor-stud-tu** [comment]
Is this still the case? Please reopen if necessary.
