### ISSUE TITLE
Push notifications fail after reconnection (iOS build 269)

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#117]
When Monal attempts to resume a 0198 session, but fails because the session timed out on the server, it reconnects with a new resource, but fails to register the new session for push notifications.

While the XEP is not clear in that regard, and this might not technically be *required*, it is still good practice to make this binding so the server can be smarter about when to trigger push for that specific session.

Also, it breaks on current prosody mod_cloud_notify :(

**Comment by tmolitor-stud-tu** [comment]
You really should register for push when you start a new session (`bind`).
You will get pushes even if your app is connected and foregrounded otherwise.

**Comment by skyfox675** [comment]
Bump, I am able to recreate. Use case:

All is back grounded for long duration and stream resumption timer expires. 

Thanks! 
-Skyfox
