### ISSUE TITLE
Monal 3.0.2 (274) / iOS 11.4 Disconnects When Running in Background 

### ISSUE THREAD

**Issue by mossmoss** [anurodhp/Monal#120]
I run Monal in the background on my bike commute to work, I'm also running Strava and iTunes ... when I check Monal after arriving, it seems to be reconnecting ... do wifi preferences affect Monal's connect behavior? I'm not confident Monal is staying connected during my commute. I'm connecting to an Openfire 4.0.3 XMPP. Thanks!

**Comment by anurodhp** [comment]
Monal works in two different ways , first is the old way like a normal xmpp client that tries to stay open. This has been removed from iOS as of 10 and it will disconnect after a few min.

However, I address that monal 3 onwards uses push (if it is turned on on your server).  Monal disconnects but push will wake it up and fetch messages if there are any. This works about as reliably as iMessage in my testing.  You may show up as offline to other xmpp users, that’s a limitation of xmpp but you will get evey message. 

To see if push is enabled go to settings-> notifications and see if everything is turned on.  If it is you should be receiving all of your messages

**Comment by anurodhp** [comment]
Just realized you said open fire. That’s the only major server that doesn’t support push :(

https://monal.im/blog/ios-3-0-1-released-how-is-push/

**Comment by mossmoss** [comment]
Thanks for the info!

**Comment by mossmoss** [comment]
Is there any reason this would now be fixed? I think the connection is no longer disconnecting while running in the background. I'm running Monal 3.0.2 (274) with iOS 12.0 (16A366), and still connecting to same Jive 4.0.3 server.

**Comment by anurodhp** [comment]
unless something changed on your server or iOS 12.  I haven't tested enough with ios12

**Comment by anurodhp** [comment]
Closing this for now, please reopen If  it is still an issue in the latest client.

**Comment by esu23** [comment]
It also happens to a friend of mine using Monal 3.1 (297) and iOS 12.1 
The account appears to be offline but push wakes up the app. But after 10 minutes or so, the app is not waken up anymore. Server has push module installed.
