### ISSUE TITLE
macOS app disconnects on idle

### ISSUE THREAD

**Issue by melange-GRX** [anurodhp/Monal#122]
After a moment or so in the background, the desktop client stops pinging the server, and does not respond to ping requests from the server even if the screen is not locked and the user is actively working in other applications. No messages will be received until the user opens the Monal window, at which point a notification appears about connecting to the server. 

I understand the advantages of push notifications on the mobile side, but on the desktop side, is there a setting or something I am missing to keep the user connected? Trillian and Converse (via HTTP) behave differently on the desktop and mobile (push on mobile, ping on the desktop), so I am wondering if I am missing a setting, if the connection is purposefully closed from the client (this is what is appears to be), or if this is a bug with the XEP-0199 handling?

Using 2.1.2 (85) on Mojave.

**Comment by anurodhp** [comment]
This sounds like a big. The Mac client is a normal xmpp client.  I haven’t tested on Mojave yet will do

**Comment by melange-GRX** [comment]
Yes, I have tried Version 2.2 (89). The problem does not seem to be resolved. I launch the app, and I see a session from Monal-OSX.73 on my XMPP server. I also launch Aduim with my test account logged in, so I see them both online. Then I keep working as usual, with the Monal window still open but in the background. Five minutes later, I check the server, and the Monal session is closed while the Adium session is still open. I tried a test message from the test account to the one Monal is using - no notification, nothing. As soon as I try and send a message in Monal, it reconnects, and I get the message I missed plus my new one goes to Adium.

**Comment by anurodhp** [comment]
Hmm this is strange. I use it as my desktop client and have not had this issue.  Out of curiosity, could it be that your server is disconnecting it because of at time out?   It might  be an issue with the ping frequency I currently have it to ping every 60 seconds.  It also sets the client as inactive when the window goes to the background.  I've never heard of it disconnecting.  I'll keep looking.

**Comment by anurodhp** [comment]
I found one possible issue that could cause the connection to hand that I've fixed in iOS.  I just put out a new Mac beta. Could you let me know if it helps?

**Comment by anurodhp** [comment]
Thanks. I don’t have any Mojave devices (my Macs are too old) working on getting one up and running to test this. 

Mac client doesn’t have any push support, need planned on it.  I will enable a debug menu on the Mac so you can view all the events in a window. 

What server are you runnin our of curiosity? I really want to resolve this, it’s  very weird and you are probably not the only person impacted

**Comment by melange-GRX** [comment]
I'm connecting to a CloudFire server, but I can also replicate this with XMPP.jp, although setting up buddies has been unreliable there.

**Comment by anurodhp** [comment]
I’ll test on xmpp.jp thanks 

--
Anurodh Pokharel

**Comment by anurodhp** [comment]
I have Mojave installed and am testing on xmpp.jp and haven’t had any disconnects. Will test more tonight.

**Comment by melange-GRX** [comment]
I did not either at first, because the welcome message from the robot admin kept the connection up.I had to remove the account and re-add it, so that I had nothing under the "Active Chat" tab.

**Comment by anurodhp** [comment]
Ok, Ive closed all active chats and am currently connected on Mojave as monal1@xmpp.jp . Will observe when it diconnects.

**Comment by anurodhp** [comment]
Oh I think I have identified the issue.  App nap. (https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html) Monal is app nap enabled and it was never a problem before. However there appears to have been a change in the logic in Mojave where UI work can stop app nap.. which would bring the strange behavior linking the UI to networking. 
Monal has a regular ping that should keep things open but I think you have identified a worst case scenario where the ping/network activity isn't frequent enough and the connection times out.  

Working on a fix.

**Comment by anurodhp** [comment]
Ive posted a new build with the fix. I do not see it napping anymore.  I think the dark mode is mostly complete now too.  canyon verify the fix so we can close this story.

**Comment by melange-GRX** [comment]
It's a lot better, but still disconnects over time. If I just leave it and Safari open, and then click to change the focus rapidly back and forth between Monal and Safari, I can see a notification about my account connecting. I can't quite pin it down. If the application is in the foreground and the window open, it behaves perfectly. As soon as the window is closed, backgrounded, or hidden - it seems to disconnect at irregular intervals. 

I think I really need Wireshark to see what Adium, Swift, and Wime are doing differently that is keeping them connected. I'll try and work on that more over the weekend. Sorry.

**Comment by anurodhp** [comment]
Wireshark will be tricky because everything uses SSL so your traffic will be encrypted.  Monal is a sandboxed app so ill have to see what changed in the sandbox. This is definitely one of the strangest issues . Glad the updates have progressively made it better.   When it disconnects is it for a long time or does it immediately reconnect?

**Comment by melange-GRX** [comment]
Monal does indeed immediately reconnect whenever the app is brought into the foreground again after a disconnect. I feel terrible about bringing you this issue - and I appreciate so much that you're looking into it.

**Comment by anurodhp** [comment]
do you see a notification that is reconnects immediately when it is in the background? I have certainly seen other clients disconnect and reconnect. If it is staying disconnected, thats a problem.  Dot feel bad im glad each iteration  it is improving things.

**Comment by melange-GRX** [comment]
Yes, I see the notification. So what I see logged in as another user on the InVerse web interface is that Monal goes offline after about five minutes. If I send a message, the server queues it up. Then I click on the Monal window, and I immediately see a notification that my account has connected, and I see myself switch to available on InVerse.

**Comment by anurodhp** [comment]
got it, thats not a good experience.

**Comment by anurodhp** [comment]
Hi I've worked on fixing lots of connection issues in the lat month or so, is this still a problem with any recent build?

**Comment by melange-GRX** [comment]
Flawless as far as I can tell. I tried three servers, and all the combinations of idling/active, window in foreground, background, or closed, initiating and receiving messages - everything I could think of. It was perfect. Amazing work, @anurodhp - so impressive. A very Merry Christmas to you and yours, and Happy Holidays to all!

**Comment by anurodhp** [comment]
Fantastic. Thanks!
