### ISSUE TITLE
"Add Contact" UI not clear (3.1; build 285)

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#130]
The "Add Contact" dialog has a single input box "Contact Name" with a hint regarding the format of a JID.

However, "Contact Name" implies that this is the place to enter the screen name, not the JID of the contact, and there is no way to edit the actual screen name.

After tapping "Add contact", a modal dialog is shown, which is rather bad practice, and you return to the "Add Contact" screen instead of the roster.

**Comment by Echolon** [comment]
I think you need to be more precise or drop a screenshot

**Comment by ge0rg** [comment]
The "Add contact" dialog:
![image](https://user-images.githubusercontent.com/165635/48315901-739c7780-e5dc-11e8-8487-c8f6e0569df5.png)
The modal popup:
![image](https://user-images.githubusercontent.com/165635/48315915-a3e41600-e5dc-11e8-80f2-78e2d841f42c.png)
And after pressing "Close" I'm back at "Add contact".

**Comment by anurodhp** [comment]
Good idea on the dismissal. The modal is there because I found even when I used it that there wasn't an obvious indicator of success.  Im open on changing the language.  What is there is literally the first thing  I thought. Do people know what JIds mean? Contact address maybe? 

At the moment I am leaning towards:
Contact Added Successfully

The new person will be added to your contacts list when they have approved your request.

**Comment by ge0rg** [comment]
From my experience, the best thing would be to display the Chat tab for the new contact right after requesting permission, and maybe to have an indication of the subscription status / presence that would be updated on approval.

**Comment by anurodhp** [comment]
Good idea. 

--
Anurodh Pokharel

**Comment by Echolon** [comment]
I would additionally suggest, to build an inline add button. so that users can directly add a contact from chat window. the same goes for MUCs. it should be clear what's a single person or whats a group chat before adding/joining

**Comment by anurodhp** [comment]
There is an add contact button in contact details screen  for adding contacts itself takes you to the chat.
