### ISSUE TITLE
Encryption: Make it as simple as possible

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#132]
Hi,

I recently dropped a few suggestions to ChatSecure and Conversations to improve about encryption UX.

Maybe Monal can take about this first hand.

Best would be:

- Show a locker symbol with encryptions choice in the direct chat window
- If there is anything else than OMEMO, hide it by default, experienced users still can activate it from settings
- Basically just give the choices:

-  _Unencrypted_  (Do not write _plaintext_ or so)

- _Encrypted (OMEMO)_  (Do not write encryptions name only)

Most users **cannot**  differentiate or decide sufficiently on anything else. They only can handle this. And thats okay.

I hope this could help you. If you wanna see a bad solution take a look at ChatSecure and their "way". No offence.

Cheers

**Comment by anurodhp** [comment]
Ive looked at iMessage, line and whatapp and it will probably resemble them. If it is more complicated than that (with more advanced options) it will likely not be very useful for most people

**Comment by benjaminbischoff** [comment]
Oh yeah ...,, and conversations is on a good way, I think, and my hope for iOS is monal! :)

**Comment by Echolon** [comment]
Hi Anu,

just read you recent blog post: https://monal.im/blog/trusting-keys/

And I would like to suggest the following changes or UI:



<img src="https://user-images.githubusercontent.com/29168011/50560680-79bcf380-0d03-11e9-968b-2343c9dc4575.jpg"  width="350">

As you may already see I suggested:

- adding names for each key (There should be an automatic generation as well as the possibilty to edit)

- reduced the text to explain, as every key has
-- description for its encryption
-- directly offering of QR-Code scanning

- Added a general hint about key trusting

Furthermore, I recommend to add a visual and/or colorised indicator about having QR-verfied or not (e.g. a green tick). 
Although, I changed the words like 'Trust' to 'Trusted' - does this make sense to you, too?

So, feel free comment on this.

**Comment by Echolon** [comment]
Awesome, you implemented it! Looks great and very simple! Thereby, I just close it!

Last thing I would somehow still do is:

- Show a locker symbol with encryptions choice in the direct chat window
