### ISSUE TITLE
OMEMO - Monal should encrypt to my other devices as well

### ISSUE THREAD

**Issue by dholl** [anurodhp/Monal#135]
I'm using both Conversations (on phone) and Monal beta (on laptop, downloaded a few hours ago today).  When I send a message with Conversations to another contact, Monal can also see what I sent, because Conversations encrypted the message for both the destination contact, as well as for Monal running on my laptop. But when I send a message with Monal, only my contact can see it, and on Conversations, I only see a message from me saying "Message was not encrypted for this device." So, I'm speculating that Monal isn't encrypting to my own OMEMO keys on my other devices as well.

**Comment by foss-** [comment]
Seeing similar behavior. Wondering if this is the same problem. For me, when I receive an OMEMO encrpyted message from a contact, the message decrypts fine on monal desktop, but not on monal iOS. On iOS I see "I sent you an OMEMO encrypted message but your client doesn't seem to support that. Find more information on https://conversations.im/omemo"

Seems like the message is not encrypted with monal key on iOS but only monal desktop + recipient. Sounds like the exact problem dholl is seeing?

**Comment by anurodhp** [comment]
fixed in the latest osx and next iOS builds

**Comment by dholl** [comment]
Thank you!!!
