### ISSUE TITLE
Certificate domain isn't verified

### ISSUE THREAD

**Issue by mimi89999** [anurodhp/Monal#140]
Monal 3.1 accepts any valid TLS certificate regardless of the domains present. If the certificate doesn't contain the domain from the JID, it will still be accepted.

Example: Add an account on the domain `lebihan.nsupdate.info`. The server certificate is only valid for `lebihan.pl` domains and doesn't contain the `lebihan.nsupdate.info` domain. Nevertheless, Monal will connect to the server.

This is a security issue as anybody MITMing the connection and presenting a valid certificate for any domain can then intercept credentials and data sent to the server.

This issue seems to have been resolved in the latest master.

Do we need a CVE for this?

**Comment by anurodhp** [comment]
taking a look.

**Comment by anurodhp** [comment]
good news is it is a one line fix, there was some debug code left in. bad news is when I make an SSL change it always seems to break for people.  :(

**Comment by mimi89999** [comment]
I think that a new release with this patch should me made immediately and the users should be clearly informed about the existence of this issue as they were vulnerable to MITM attacks and potentially had some of their data recorded by an attacker.

**Comment by anurodhp** [comment]
I’m testing it. There is an an update coming this week that this will be in, always let people know when I make ssl changes because it will break existing accounts on miacondigured servers that were working.

**Comment by anurodhp** [comment]
I believe this is fixed now. I have made the beta available online so you can verify this has been resolved. 
https://testflight.apple.com/join/RjIlyvqa

**Comment by anurodhp** [comment]
feel free to reopen if the issue persists. the fix appears to be working for me.
