### ISSUE TITLE
macOS beta 2.2 (98) startup crash / crash when selecting contact

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#141]
[Crash log](https://bin.disroot.org/?98044cb2450421ac#p0vr1cfICpX/b3y+AqSORzmBhQsl7MTIqCOUEIl3bQw=) (1 month from now)
Reproducible: always
macOS 10.14 + 10.13

**Comment by anurodhp** [comment]
Hi, thanks for the report. Any details on how to go about reproducing it?

**Comment by foss-** [comment]
Either it crashes right away or it crashes as soon as I click on any contact in my contact list. Does that reproduce for you?

**Comment by anurodhp** [comment]
Just got it to happen. Will update.

**Comment by anurodhp** [comment]
its a bad build (thats what I get for doing it at midnight)

**Comment by anurodhp** [comment]
build 99 is up.
