### ISSUE TITLE
add sparkle support for macOS beta updates

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#142]
Sparkle is there, but beta updates are not yet in place. It would hugely improve usability for beta testers if updates were provided via Sparkle update mechanism.

**Comment by anurodhp** [comment]
Unfortunately this is an issue with sparkle. There has been an open bug for three years  :(
https://github.com/sparkle-project/Sparkle/issues/499

There really isn’t something better that I know of,  which is why I use sparkle. :(

**Comment by foss-** [comment]
Hm, reading up on https://github.com/sparkle-project/Sparkle/issues/363 it's a bit unclear what the current state is.
