### ISSUE TITLE
XEP-0201: Best Practices for Message Threads - Replying to specific thread

### ISSUE THREAD

**Issue by benjaminbischoff** [anurodhp/Monal#143]
Regarding to https://github.com/siacs/Conversations/issues/3303
Would be great to implement it like requested there (just as a feature request)

https://xmpp.org/extensions/xep-0201.html

**Comment by benjaminbischoff** [comment]
Seems to be denied by Daniel (Conversations) atm :(.

**Comment by tmolitor-stud-tu** [comment]
@anurodhp replying to a message is something else than message threads. there is a xep under work for such "reply to" functionality.

**Comment by Echolon** [comment]
@tmolitor-stud-tu yesterday we removed this from the list?

**Comment by tmolitor-stud-tu** [comment]
Yes de removed xep 0201 and this issue can be closed

Am 30. Oktober 2020 09:02:24 MEZ schrieb Echolon <notifications@github.com>:

**Comment by Echolon** [comment]
Please refer to **Quote on message swipe** #239
