### ISSUE TITLE
Add Translation into different languages

### ISSUE THREAD

**Issue by benjaminbischoff** [anurodhp/Monal#144]
@anurodhp ,
I am not sure how much effort it would be, but did you already thought about support for multiple languages?
If yes, I would offer translations for german and dutch.

**Comment by anurodhp** [comment]
Its a good idea but would require a lot of work and time that I don't have at the moment.  The current app isn't designed to be translated, I did some bad things a long time ago like put strings in the code instead of the strings file. That can be fixed but the bigger issue is a real translation would need to have the UI adjusted properly so that text is the right size and fits.  This is something that needs to be done manually -- automated tools exist but there is always a manual adjustment.

**Comment by licaon-kter** [comment]
This would be welcomed...

I recommend Weblate, Crowdin or Transifex (in this order)

**Comment by Echolon** [comment]
@anurodhp I think thats a bit too quick - let's wait till I fully setup everything please

**Comment by anurodhp** [comment]
sorry, i dint close this. i blame GitHub doing it on merge

**Comment by cweiske** [comment]
When I understand #403 and #405 correctly, the Monal's strings are translatable now.

What would be the next step to actually add translations? (Sorry, I have no experience with OSX development)

**Comment by Echolon** [comment]
Hi @cweiske 
thanks for you interest. At the moment I am evaluating and trying to setup translations service. Once I have that done I will send an announcement and at least sufficient information in here!

**Comment by Echolon** [comment]
Hello @orangesunny,

I contacted you via email and wanted to ask if something is missing yet?
- We transferred the license text into a separate file so it should be standard: https://github.com/anurodhp/Monal/blob/develop/LICENSE
- I attached the localization.string file in the email from the 27th of July

Kind regards

**Comment by licaon-kter** [comment]
@comradekingu Could you ask the Weblate people what's the holdup here? Thanks

**Comment by comradekingu** [comment]
@licaon-kter From perusing some bugreports I picked up that the inclusion is going to be more automated in the future. Also everyone and their dog is trying to join it seems. Sent a message to the person who adds projects.

**Comment by orangesunny** [comment]
> Hello @orangesunny,
> 
> I contacted you via email and wanted to ask if something is missing yet?
> 
>     * We transferred the license text into a separate file so it should be standard: https://github.com/anurodhp/Monal/blob/develop/LICENSE
> 
>     * I attached the localization.string file in the email from the 27th of July
> 
> 
> Kind regards

Hi, we don’t need any files, just know which are the right ones in your repo. Anyway, you have the rights to manage Monal project on Hosted Weblate now, so go on!

**Comment by orangesunny** [comment]
> @comradekingu Could you ask the Weblate people what's the holdup here? Thanks

Nothing, just my backlog. Problem solved, and translations will be up and running once @Echolon says 🚀

**Comment by Echolon** [comment]
@orangesunny Thank you very much for doing the setup! Will check out!

**Comment by comradekingu** [comment]
@Echolon If you add https://hosted.weblate.org/user/kingu/ as admin in https://hosted.weblate.org/access/monal/ I can try to help with any issues.

**Comment by Echolon** [comment]
Hello everyone, 

I think we are ready to go: https://hosted.weblate.org/access/monal/
As the people are already going crazy, I think there is not much to do from my side. If you see something I should handle, please tell me!

**Comment by orangesunny** [comment]
> Hello everyone, 
> 
> I think we are ready to go: https://hosted.weblate.org/access/monal/
> As the people are already going crazy, I think there is not much to do from my side. If you see something I should handle, please tell me!
> 

Are you happy with the component setup and naming?

**Comment by Echolon** [comment]
Hi @orangesunny 

I am not sure. It seems to me there are only 11 strings shown. Now I am trying to setup the string file atm. But not sure if Im doing it right actually.

**Comment by orangesunny** [comment]
If you tell me which file in your repo is the one containing strings, I can set it up. Does the one in the e-mail attachment in the repo?

**Comment by Echolon** [comment]
We have a more current one: https://github.com/tmolitor-stud-tu/Monal/commit/d1a6095c5603a4f29eb651840099b5a6b4ab2254

**Comment by orangesunny** [comment]
I am not going to set up the translation file to another repo, it doesn’t make sense. Once you have it in your main repo, point me to the file and mention the branch you want to use. Until then, I locked the project on Hosted to not waste translators' effort.

**Comment by Echolon** [comment]
Yes sorry, I forgot, will do it

**Comment by Echolon** [comment]
Hello @orangesunny 

we added the current file here: https://github.com/anurodhp/Monal/blob/43a5a665e6b506995c750a728c490639b5b7c40e/Monal/Base.lproj/Localizable.strings

**Comment by orangesunny** [comment]
Okay, one last thing: We need to have some language code in the naming of the files to let Weblate work. Can you make a copy of `Base.lproj` or rename it to `en.lproj`?  I suppose it will be _English_ will be used as a source language.

**Comment by Echolon** [comment]
Hi @orangesunny,

I changed as you suggested!

https://github.com/anurodhp/Monal/blob/5ca9352a2b53c7466219e30125879f6c0862e2cd/Monal/en.lproj/Localizable.strings

**Comment by Echolon** [comment]
@orangesunny Thilo did it himself. So I think you don't need to help out on this anymore. 

Thank you very much for helping on this project!

**Comment by Echolon** [comment]
Hello everyone,

short statement: Weblate is officially ready. Thanks for everyone being so quick already with early efforts. You can add your prefered languages now!

Happy translating!

@cweiske

**Comment by Echolon** [comment]
https://hosted.weblate.org/access/monal/

**Comment by cweiske** [comment]
Your link gave me a "permission denied", this one works for me: https://hosted.weblate.org/projects/monal/

**Comment by orangesunny** [comment]
Yes @cweiske, you are right, the one previously shared by @Echolon was to manage page.

The best way to promote your project traslations is https://hosted.weblate.org/engage/monal/ or click on `Share` in Monal project menu in Weblate.

**Comment by Echolon** [comment]
Hi @orangesunny,

we use a rebase based workflow and weblate frequently has conflicts even for files that have nothing to do with translations. Solving all those conflicts manually every time is way too much manual work. is there any addon/extension to make weblate resolve conflicts in non-translation files automatically (e.g. always use the files from upstream repository)?

@tmolitor-stud-tu

**Comment by nijel** [comment]
@Echolon do you do force pushes to the repo? In case you do, then Weblate would have to be reset at this point because otherwise it will try to rebase disappeared commits onto new ones.

**Comment by anurodhp** [comment]
No one should be force pushing on develop it’s not the kind of thing that should be done on any branch that someone else also has
