### ISSUE TITLE
allow Shift + Enter to get to a new line (without sending the message)

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#146]
Many clients (signal comes to mind) support Shift + Enter to get to the next line to enter text like this:

First Line
Shift + Enter goes to next line

It would be great if Monal supported this.

- [X] fixed in macOS Monal 2.3 (110) beta

- [ ] unfixed in iOS Monal 3.3 stable (not on beta channel so can't say if it's fixed there)

**Comment by Echolon** [comment]
I understand right, that this option will also come to iOS Monal?

Will it be possible to define the standard event when pressing 'Return'? A friend of mine, and I think lots of others aswell, seems to expect that 'Return' will go to the next line.

**Comment by foss-** [comment]
solved in https://github.com/anurodhp/Monal/commit/396664640fbb4b409ea913e44914386acee1cd57

it's solved a bit differently than suggested in this issue here. instead enter always creates a new line on iOS. "Send" will send the message. That way accidental sends are avoided as well. The behavior switches to the macOS behavior with an external keyboard connected.
