### ISSUE TITLE
[macOS] Sometimes text goes out of the bubble

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#147]
This existed as https://github.com/anurodhp/Monal/issues/106 and was fixed. We are now looking at a regression:

![ui glitch](https://user-images.githubusercontent.com/5708172/49803500-4b757500-fd50-11e8-8c65-ab60ad516e1a.png)

Besides the text going outside the bubble, I'd also love, if Monal (macOS) had a little bit more space between the latest msg and the bottom toolbar. Currently it looks a bit squished.

Both issues are obviously not priority and of cosmetic nature.

**Comment by Echolon** [comment]
@foss- 

Is this still persistent?

**Comment by foss-** [comment]
Let's close. I can't recall seeing this recently.
