### ISSUE TITLE
XEP-0084 User Avatar: Add option to set an avatar for contacts

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#148]
Currently Monal lacks an option for that.

Expected: UI to set an avatar image for the xmpp account.

EDIT: https://xmpp.org/extensions/xep-0084.html

**Comment by citbr** [comment]
This and the ability to give names to the contacts instead of just showing the address the server sends.   In the meantime is there any way to change these by modifying a pref file or something?  REALLY don't like getting the generic icon next to all my contacts.
