### ISSUE TITLE
"Contacts" and "Chats" buttons should always open the respective lists (build 309)

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#150]
When you have a chat open, switching tabs will yield that open chat instead of the list.

Steps to reproduce:
1. Open "Contacts" tab
2. tap any contact to open a chat with them
3. Open "Chats" tab
4. tap any chat (could even be the same as in 2)
5. Tap "Contacts". Expected view: Contacts tab. Actual view: chat with your contact
6. Tap "Chats". Expected: list of chats. Actual: chat with somebody

**Comment by foss-** [comment]
Obsolete. Contacts and Chat tabs have been merged / UI has been restructured.
@anurodhp / @Echolon  can you close this one please?
