### ISSUE TITLE
room name empty for MUC rooms

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#151]
macOS 10.14.2
Monal 2.3 (110)

Unsure how to reproduce, but keeps happening since I started using Monal on macOS. In my case this is IRC rooms on freenode. In some cases both the room name and my own nick are not shown (1st case in screenshot) in other cases my nick is shown but not the room name (2nd and 3rd case in screenshot).

This is quite confusing for users. To identify which room is which, the respective rooms have to be selected since otherwise it's impossible to tell.

![monal macos 2 3 110 missing room names](https://user-images.githubusercontent.com/5708172/50149124-9fd1a500-02ba-11e9-8bf9-8a15d17b830c.jpg)

**Comment by anurodhp** [comment]
I was able to replicate it once but not after that. I don't know what is causing this yet.

**Comment by foss-** [comment]
Re-added the rooms with missing room names and all room names appeared in Version 2.3 (112). Will keep an eye on this and report back. Maybe this is already fixed by some commit from the last days.

**Comment by Echolon** [comment]
@foss- Hi, is this still existent with the current version?

**Comment by foss-** [comment]
no let's close and thanks for the ping.
