### ISSUE TITLE
[security] macOS: keep OMEMO setting state for conversation

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#152]
macOS 10.14.2
Monal 2.3 (110)

**Currently**

After enabling OMEMO encryption for a 1:1 conversation and then closing and restarting Monal on macOS the encryption is disabled. Reproduce is easy and 100% reliable by enabling OMEMO and then restarting Monal.

EDIT: Actually it's even worse - leaving the conversation and switching back to it seems to be sufficient to disable OMEMO encryption. Maybe related to the client used on receiving side. Since Monal is a bit of a limbo regarding OMEMO, this may or may not be expected until OMEMO is officially available in both macOS and iOS versions.

**Expected**

This is a security concern and very bad behavior. Users should be able to trust encryption and once they enable it, it should stay that way. If - for whatever reason- the encryption becomes disabled, Monal needs to show a big warning inside of the chat, informing users about that change.

But ideally that would not happen and encryption state would simply survive a restart.

**Comment by anurodhp** [comment]
fixed in the latest release for OSX, will be in the next iOS beta too

**Comment by lindenstaub** [comment]
Not sure if I should open a new issue, having a similar problem in build 130: chats switching back to unencrypted after successfully sending a couple encrypted messages. Don't see any pattern in what's triggering the switch back to unencrypted, but possibly receiving an incoming message toggles encryption off.

Even worse is, the icon in the corner indicates that it's encrypted and I don't see the the encryption failed until after I send the message there's no "encrypted" icon next to it.

Receiving side is Gajim 1.1.2.
