### ISSUE TITLE
pre-select the first user account in Chat > Join Group Chat dialog

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#154]
**Currently**

User account is blank.

**Expected**

Use first user account from dropdown list. For users with a single account this resolves a lot of unnecessary clicks because their pre-selection would be always the correct account.

Showing an empty dropdown is uncommon and probably not best practice.

**Bonus track 1**: allow to set a default account *or* maybe allow sorting user accounts in Monal > Preferences so if pre-selected account is always the first account from that location users would put the most used account to the top so that in most cases the pre-selected account would fit already.

**Bonus track 2**: Once users click "Join"
**Currently** The room is added, but the Join Group Chat dialog stays open.
**Expected** Join Group Chat dialog is closed and user is taken to the room they just added.

If you prefer separate issues for the bonus track stuff, just let me know.

![join group chat](https://user-images.githubusercontent.com/5708172/50151729-fd1d2480-02c1-11e9-92cf-a1f98b60e790.png)

**Comment by foss-** [comment]
Version 2.3 (112) does not seem to fix this for the case when several acounts exist. your commit description is "when there is only one account hide account menu and select the first…" so maybe this is only fixed for when a single account exists?

Teste with several accounts and in my test, the field stays blank. Should this issue remain open until that part is also addressed?

**Comment by anurodhp** [comment]
Will update to remember last used/ select first

**Comment by anurodhp** [comment]
closing this as it defaults to he first user, having it remember is a TODO item. bonus 2 is a good idea and should be another bug.
