### ISSUE TITLE
MUC: Disable output "xxx has set the subject to"

### ISSUE THREAD

**Issue by truenicoco** [anurodhp/Monal#157]
Everytime I open a MUC in monal, the first message is "[user] set the subject to [subject]", which results in a bloated history. It would be great if monal had a feature to disable these kind of messages.

**Comment by Echolon** [comment]
@truenicoco 

Can you provide a screenshot of this?

**Comment by Echolon** [comment]
@foss- may you able to replicate this?

**Comment by foss-** [comment]
Unable to reproduce on macOS 10.15.4 and Monal 4.5 (593) as well as iOS 13.4.1 and Monal 4.5 (596).

I suggest to close @Echolon 
@truenicoco  If I am mistaken something, please re-open and provide additional details as to how to reproduce the problem.

**Comment by Echolon** [comment]
@truenicoco I will close this issue for the moment. Please review with the current version. Soon there will be also a new debug log which would help us to review your issue in case it is still there. Thanks for reporting anyway!
