### ISSUE TITLE
macOS: Deleting an account should ask for confirmation

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#159]
Removing a contact opens up a dialog:
> Are you sure you want to remove this contact? Yes | No (defaults to no)

**Currently**
Once an account is selected and delete button is pressed, the account is gone right away.

**Expected**
Dialog: Are you sure you want to remove this account? Yes | No (defaults to no)

[X] iOS 3.4 (334)
[ ] macOS

**Comment by Echolon** [comment]
this is good!

**Comment by mbirth** [comment]
I believe this is implemented in the latest beta?

**Comment by foss-** [comment]
is that so? Checked Version 2.3 (127) and not solved yet.

**Comment by mbirth** [comment]
iOS 3.4 (334) has the confirmation dialog. Just tested it again.

**Comment by Echolon** [comment]
If that is true I will close.

Please report if wrong and I reopen.

**Comment by foss-** [comment]
Not true for macOS client.

**Comment by anurodhp** [comment]
this is in catalyst

**Comment by foss-** [comment]
Version 4.3 (525) verified, thanks.
