### ISSUE TITLE
[macOS] Lock icon placement in chat view could be improved

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#160]
Currently see screenshot
Lock for personal messages is far to the left and lock for messages of conversational partner is next to their avatar image.

Expected
I think it would be a lot cleaner and easier for the eye to catch if the lock was always inside the msg bubble. Not entirely sure about the best placement though. Signal has a reading indicator *below* each message. Maybe that's a way to improve this. Other options are possible of course.

![lock placement](https://user-images.githubusercontent.com/5708172/50724510-a3ed2780-10ee-11e9-8f45-13a8091af4e8.jpg)

**Comment by Echolon** [comment]
rel.

**[UI] Improve text bubble allocation, time stamp and lock symbol** #214

**Comment by foss-** [comment]
solved
<img width="590" alt="lock placement" src="https://user-images.githubusercontent.com/5708172/74084986-ad289080-4a74-11ea-9647-aa584e355fb8.png">
