### ISSUE TITLE
Contacts shown multiply on Monal iOS

### ISSUE THREAD

**Issue by thephishermen** [anurodhp/Monal#163]
Current Monal iOS Client (3.4 (320)) shows certain contacts more than once - even though JabberID and Fingerprint of the respective contact are identical.

**Comment by foss-** [comment]
Another affected user, seeing this on macOS + iOSI now have 4 active chats for the same contact.

**Comment by thephishermen** [comment]
see it on iOS now as well (321)

**Comment by thephishermen** [comment]
Notifications of new messages to those multiply shown chats are not sync'd. You have to read/focus every instance of the chat displayed to make the notification disappear for the different instances of the same chat.

**Comment by foss-** [comment]
macOS Version b2.3 (116) persisting. should be re-opened?

**Comment by anurodhp** [comment]
Next build is today, let’s see if that fixes it

**Comment by foss-** [comment]
![macos b2 3 117](https://user-images.githubusercontent.com/5708172/50912578-c35bbb80-1432-11e9-884f-4d13e83b670f.png)

**Comment by anurodhp** [comment]
still looking at this I think it may be related to #44.   I haven't ever been able to replicate but it seems to have been happening for a while

**Comment by anurodhp** [comment]
actually we have two different issues here. active chats which I believe has been fixed and contacts which may not me

**Comment by foss-** [comment]
> actually we have two different issues here. active chats which I believe has been fixed and contacts which may not me

That's exactely the situation I am seeing. Contacts view showing multiple entries for some contacts has been a problem for as long as I have started using / testing Monal iirc.

**Comment by anurodhp** [comment]
The the container in (home/librAry/containers/Im.monal.monalosx) will fix Mac clients on the newest beta that may have a dB in an in consitwnt state that show duplicate contacts. iOS you can delete and reinstall.
