### ISSUE TITLE
Cannot join any MUC with latest beta

### ISSUE THREAD

**Issue by ritzmann** [anurodhp/Monal#167]
I just downloaded the latest beta for macOS and entered my existing XMPP credentials. 1:1 chats seem fine but I completely failed to join any MUC. When I enter the JID of a MUC and press the JOIN button, nothing seems to happen. I can see later in the bookmarks that when I have the bookmark checkbox enabled, it inserts a new bookmark each time I press the Join button.

Please let me know if there is any other information I can provide to help debug this.

**Comment by thephishermen** [comment]
I just succesfully joined a groupchat ... the group chat is added to the contact list, i then manually closed the modal window (Join Group Chat) and was able to chat in the group. I am running the latest beta as well (2.3, 115)

**Comment by ritzmann** [comment]
Now after I rediscovered the console in macOS, I was able to establish what is going on. When I am trying to join a MUC, I am seeing a reply from the server like this:
`<presence type='error' to='me@myserver.net/Monal-OSX.97' from='some-muc@rooms.dismail.de/'><error type='modify'><jid-malformed xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>The destination address is invalid: some-muc@rooms.dismail.de/</text></error></presence>`

Note the `/` at the end of the JID. I had not explicitly set a nick in Monal's MUC dialog. When I do that, joining MUCs works just fine. So apparently Monal is not correctly setting the JID of the MUC when trying to join with the default nick.

**Comment by anurodhp** [comment]
Thanks for looking into it! Will fix 

--
Anurodh Pokharel

**Comment by Echolon** [comment]
@ritzmann have you checked the recent version? or beta?

Is is still existent? Otherwise please close

**Comment by ritzmann** [comment]
Yes, still existent with the latest build. Not sure why you are asking? There is no indication that the author would have fixed it.

**Comment by licaon-kter** [comment]
@ritzmann by indication you mean store release notes notes or commit titles or support room feedback?

**Comment by foss-** [comment]
On which macOS and Monal version does the problem persist? If you are runnning Catalina, could you test the Catalyst beta and see how that behaves?

**Comment by ritzmann** [comment]
Catalina, 2.5 beta 5,159 according to Homebrew. Will still be a few months before I can upgrade to Catalyst. Note that this issue has been around for a year already (and is still reproducible).

**Comment by foss-** [comment]
@ritzmann why can you not test the catalyst version?

**Comment by foss-** [comment]
@ritzmann would be great if you could test the Catalyst build. You can find the latest Catalyst beta build here: http://monal.im/Monal-OSX/Monal-catalyst.zip

**Comment by anurodhp** [comment]
closing as this isn't reproducible anymore
