### ISSUE TITLE
Roster-Groups should be shown (optional)

### ISSUE THREAD

**Issue by thephishermen** [anurodhp/Monal#170]
Feature Request:

It would be great if one could optionally display the Roster-Groups of my contacts (very helpful if you have a lot of contacts and you are managing those in different groups)

**Comment by zippydan** [comment]
I believe this is a duplicate of https://github.com/anurodhp/Monal/issues/121 

> [feature request] support for user groups #121

Unless "Roster-Groups" is somehow different from standard XMPP user groups?

**Comment by Echolon** [comment]
I agree with @zippydan
