### ISSUE TITLE
iOS: Online/offline status in contact list is of no use

### ISSUE THREAD

**Issue by thenktor** [anurodhp/Monal#171]
Hi,

in an iOS client only environment the online/offline status in the contact list is of no use. The iOS clients actually are always offline except when the app is active. 
Please make it possible to disable this split view because it is just disturbing users that nowadays are only used to IM services like WhatsApp.

**Comment by anurodhp** [comment]
I agree, things are going to move to the active chats screen. I need to balance the needs of long time XMPP users who are used to the contact list with modern users who have no concept of that.

**Comment by eveofdestruction** [comment]
Is there a third party app for ios (like tasker with android) to bring forward an app [briefly] into focus?

@Echolon

**Comment by anurodhp** [comment]
There is nothing like that. Apps on iOS work in a confined sandbox with limited permissions. This is why sever side tech like push exist.  Online and offline is very 90s and I don’t think outside of xmpp it is used anywhere.  Clients like WhatsApp(which is xmpp based) call it recently seen or something like that and is probably what xmpp clients should call it

**Comment by anurodhp** [comment]
Addressing the actually bug, online offline has been removed in the new ui which looks a lot like WhatsApp.
