### ISSUE TITLE
macOS: Repeating error notifications on connection problems

### ISSUE THREAD

**Issue by CodingMarkus** [anurodhp/Monal#173]
When my Jabber server is not reachable, I get a system notification that Monal was unable to connect, showing me the NSError description. This is pretty useful, of course, however, it is not useful, that this notification is repeated every couple of seconds, over and over, until I set the account to offline or make sure connectivity is restored. It's okay to just post that notification once, indicate the account offline status somewhere in the app window and then only post another one when connectivity is restored.

**Comment by Echolon** [comment]
@CodingMarkus 

Hi,

is this still existing?

**Comment by anurodhp** [comment]
ive reduced the frequency. Ill think of a better indicator that is less intrusive

**Comment by Echolon** [comment]
I will close this issue, please report if something is still going on.
