### ISSUE TITLE
Set your own screenname for a contact

### ISSUE THREAD

**Issue by thephishermen** [anurodhp/Monal#174]
It would be great if Monal would support the feature of maintaining your own ScreenName for the Jabber-ID's in your contact list. Makes it much easier to keep track of who is who ...

**Comment by Echolon** [comment]
Absolutely essential!

**Comment by anurodhp** [comment]
yeah I'm going to do this. the inconstant names are killing me and I agree its ugly

**Comment by dholl** [comment]
Is this a duplicate of #43 ?

**Comment by Echolon** [comment]
Yep, I will close this because of #43
