### ISSUE TITLE
OMEMO: Showing users' own keys

### ISSUE THREAD

**Issue by jelmer** [anurodhp/Monal#175]
Is there a way to see all the current users' device keys and/or change keys?

**Comment by anurodhp** [comment]
this is in iOS at the moment coming to the Mac soon.

**Comment by anurodhp** [comment]
closing because the Mac is covered by #168

**Comment by jelmer** [comment]
I'm running the iOS beta but I'm having trouble finding the list of my own device keys. Where do I find it?

**Comment by anurodhp** [comment]
in the latest beta (323) got to settings->accounts-> your account 
scroll to the bottom and at the bottom just above delete is "My Keys"
