### ISSUE TITLE
Received OMEMO Images Do Not Display Properly

### ISSUE THREAD

**Issue by a11fruitless** [anurodhp/Monal#176]
Version: Monal 3.4 (323)
Communicating with: Gajim 1.1.1
Server: Prosody 0.11.2

Received OMEMO images do not display inline properly. Only a cryptic URL (without a link) is shown. However, OMEMO images sent from Monal do display properly in other clients.

Received unencrypted images display inline without error.

Thank you!

**Comment by jelmer** [comment]
I can also reproduce this, communicating with conversations.

**Comment by anurodhp** [comment]
I think I know what this is. I need to turn on my android tablet and test it.

**Comment by anurodhp** [comment]
yeah as expected conversations sends files with a protocol aesgcm:// I need so add support for its style of sending files

**Comment by Chobbes** [comment]
Any word on this? OMEMO support feels *very* close to being perfect, and having this little bit missing is a little frustrating :).

**Comment by thirtyfiveo** [comment]
> Any word on this? OMEMO support feels _very_ close to being perfect, and having this little bit missing is a little frustrating :).

Yes, in the new blog post on thursday:
https://monal.im/blog/ios-updates/

**Comment by anurodhp** [comment]
Just  wasted a good deal of time on this but it is working now. Turns out the documentation here is wrong :(
https://xmpp.org/extensions/inbox/omemo-media-sharing.html

**Comment by jelmer** [comment]
Thanks, that works well. The aegscm links still appear in the notifications. Perhaps it would make sense to just show an indication that an image was received instead (e.g. https://emojipedia.org/frame-with-picture/)?
