### ISSUE TITLE
Modal-Window with Contacts FullName can't be closed when clicking "Close"

### ISSUE THREAD

**Issue by thephishermen** [anurodhp/Monal#177]

**Comment by thephishermen** [comment]
<img width="432" alt="bildschirmfoto 2019-01-15 um 14 11 40" src="https://user-images.githubusercontent.com/46441076/51182782-84fd4b00-18cf-11e9-9558-df98f27027bf.png">

Also the Window is not Labeled

**Comment by anurodhp** [comment]
The close button is gone now

**Comment by anurodhp** [comment]
resources screen has also been fixed
