### ISSUE TITLE
When Opening Modal Window "Resources" or "Encryption Keys" the ContactDetail-Window closes 

### ISSUE THREAD

**Issue by thephishermen** [anurodhp/Monal#178]
When Opening Modal Window "Resources" or "Encryption Keys" the ContactDetail-Window closes. From a Workflow perspective this does not make sense as I would be expecting the window with Additional Information would be on top of the "basic" information window

**Comment by anurodhp** [comment]
part of the motivation to move the details into new windows was to remember that this isn't a mobile app so things can be in windows (e.g. you can have man key windows open) , but I agree it may not be a good to close the original details screen

**Comment by anurodhp** [comment]
shouldn't be an issue in the catalyst builds
