### ISSUE TITLE
Take user to newly joined MUC chat and close join dialog

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#181]
**Currently**
The room is added, but the Join Group Chat dialog stays open.

**Expected**
Join Group Chat dialog is closed and user is taken to the room they just added.

**Comment by idnovic** [comment]
I have the same problem

**Comment by Echolon** [comment]
I'm gonna close this, it works like expected in the current alpha.
I can reopen if that is still the case for the next stables.
