### ISSUE TITLE
Contacts in Contact List not shown on iPad until accounts accessed

### ISSUE THREAD

**Issue by WainPetopia** [anurodhp/Monal#182]
On my iPad (iPad Air 2, iOS 12.1.1, Monal v. 3.3 (311)), when I foreground Monal and go to the Contacts tab, it's empty - it shows the headings "Online" and "Offline" but with no actual contacts under them. Also, at the top of the right hand pane it says "[Logged Out]".

It remains that way until I manually go into my Settings tab and select Accounts. Then my account becomes active and my contacts list is populated. (Actually, I only have one contact for that account right now, in case that's relevant). The "[Logged Out]" message at the top of the chat pane remains, however.

If I background the app and leave it a while, it will revert to the previous state where my contacts (well, contact) are missing.

This isn't the case on my iPhone (6s, running iOS 12.1.2 , Monal v. 3.3 (311)), but Monal seems to behave differently on that device.

Both devices have push enabled.

I've only recently started using this app. Thank you for creating it :)

**Comment by anurodhp** [comment]
looks like a UI behavior issue. Will take a look

**Comment by anurodhp** [comment]
will be fixed in the next beta

**Comment by WainPetopia** [comment]
Thanks, it works great now :)
