### ISSUE TITLE
macOS contacts view: contacts being online and have green dot and communicate with me are still displayed as offline

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#186]
**Currently**
Contacts are shown as offline while clearly they are online. They communicate with me and also they have the green dot (correct) but are shown as offline (wrong).

**Expected**
Contacts should always be in the correct section in contacts view.

**Comment by thephishermen** [comment]
+1 - have the same issue

**Comment by foss-** [comment]
not seeing this anymore with Version 2.3 (124).
removing ~/Library/Containers/im.monal.monalosx folder was a requirement to get this back to working state.
@thephishermen could you try above steps and report back if that also fixes the problem for you.

**Comment by anurodhp** [comment]
The  clearing the container will fix Mac clients on the newest beta that may have a dB in an in consitwnt state that show duplicate contacts. iOS you can delete and reinstall. The contact online / offline issue is actually a problem with xmpp :(. There is a reason most modern clients have ditched the presence part
