### ISSUE TITLE
TBD OMEMO messages from Dino are not decrypted

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#187]
This needs to be inspected and teste more thoroughly. With one contact I ran into a situation where message from conversations from them arrived fine but messages from Dino resulted in "[This message is OMEMO encrypted]" and no decrypted msg. Not sure if this is 100% reproducible. And not using Dino myself. https://dino.im/

**Comment by anurodhp** [comment]
It appears the GCM keys that come from Dino are only 16 bytes and are missing the auth tag.  Compare that to Monal or Conversations, where it is 32 bytes.

**Comment by anurodhp** [comment]
oddly enough Dino to gajim works but gajim to Dino doesnt. Monal can send to Dino but not receive.  Monal to gajim is fine.

**Comment by anurodhp** [comment]
since this works ok with every other client and the fact that Dino doesnt seem to work with gajim makes me think  this is a Dino issue.

**Comment by foss-** [comment]
Did you file a ticket with dino about this problem? would be great to make them aware of this issue - maybe they don't even know this is a problem.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/xsf/xeps/pull/894

**Comment by Neustradamus** [comment]
Several years after, it is now solved:
- https://github.com/dino/dino/commit/cd5b639a826ccafe5741a51f10cc8ca76ebfdd14
- https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1 (https://github.com/dino/dino/issues/909)
