### ISSUE TITLE
Remember collapsed state of contacts view

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#189]
Reproduce

1. collapse online and uncollapse offline in contacts view
2. restart monal

Currently

After restart online is uncollapsed and offline is collapsed.

Expected

Respect user choice and remember states.

Crosslinking #201 Doesn't remember active section

**Comment by Echolon** [comment]
@anurodhp is this still part of the UI ?

**Comment by foss-** [comment]
Thanks for pinging about this @Echolon. This issue is no longer applicable and obsolete due to UI redesign. Closing.
