### ISSUE TITLE
add checkbox to macOS settings allowing to opt out of Crashlytics / sending crash logs

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#190]
GDPR would require such a setting. iOS has it already at Settings > Crash Logging > Crashlytics.
Unsure where a good location on macOS client would be as non of the current four setting categories seems to fit (Accounts, Presence, Display, Cloud Storage).

**Comment by anurodhp** [comment]
It will be a new setting like I did on iOS.  I somehow forgot to expose this in the ui
