### ISSUE TITLE
[macOS] Increase typing area size

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#193]
**Currently**

The typing area is a single row and fairly narrow.

**Expected**

The bar above the typing area show be not as thick as it currently is. The typing area should be expanded so that clicking it becomes easier. Curently often times trying to click the typing area often results in the active cursor not being in that area since the click was slightly too high.

![typing area](https://user-images.githubusercontent.com/5708172/52041641-4e643900-253b-11e9-8438-4c17f2f39ad1.png)

**Comment by anurodhp** [comment]
should be better now
