### ISSUE TITLE
[iOS] Permission to access camera roll is only asked once, then never again

### ISSUE THREAD

**Issue by mbirth** [anurodhp/Monal#195]
When playing around in the settings, I came across the Chat Background option where you could select a photo from the camera roll. However, as I didn't want that, I denied the request for access.

Later when trying to send a photo in a chat, nothing happened when touching the option. Also, when trying to capture a photo from the camera, the camera came up black. No question about the permission. The only solution was to delete the whole app and reinstall.

EDIT: This was with the latest iOS Beta as of today.

**Comment by dzaikos** [comment]
I don't think this is an issue with the app. It's pretty normal operation for iOS. You are asked by the **operating system** if you want to allow access to the app, if you deny then the operating system simply doesn't allow access. Period.

If you change your mind later you go into Settings > Privacy and toggle on the Camera and/or Camera Roll for the app in quesiton.

This works both ways, too. If you allow access but later want to revoke, or if you deny it and and later want to allow it. And it works across the various types of permission (camera, camera roll, location, health, etc.).

**Comment by anurodhp** [comment]
Thanks yeah, this is an iOS thing. I could provide info about being blocked and instructions on how to unblock by going into iOS settings but once you deny access there’s not much monal can do
