### ISSUE TITLE
[macOS] Deleted MUC room keeps returning after restarting

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#199]
see title. not tested on iOS. if you need additional info, please ping.

**Comment by foss-** [comment]
Hi Anu, thanks for the fix. Should this fix be part of the latest beta? Running  2.4 (131) here and this problem is persisting.

**Comment by anurodhp** [comment]
should be fixed in the latest release.

**Comment by foss-** [comment]
Version 2.4 (135), persisting. Room re-appears after Monal restart.

**Comment by Echolon** [comment]
@foss- 

Still persistent?

**Comment by foss-** [comment]
Yes, this especially concerns IRC rooms accessed via xmpp bridge. Anu is testing this I think.

**Comment by anurodhp** [comment]
I think we figured out that the issue here was that i was set as an auto join room
