### ISSUE TITLE
Does not so how text in second line

### ISSUE THREAD

**Issue by xb-shibby** [anurodhp/Monal#2]
On my iPhone, Monal does not show the text that I enter when I am bejond the first line.
When entering text in the second line, I will only show up once I get to the third line and so on.
See attached screenshot. There I am typing text in the third line but it does not show up. It shows up one I reach the fourth ine.
![img_2633](https://cloud.githubusercontent.com/assets/17108159/12872230/6687c842-cd9d-11e5-88b3-07dfb8805256.PNG)

**Comment by anurodhp** [comment]
This should be fixed on develop, will be in the next release. I need to update some more of the code/test the changes before release. .
