### ISSUE TITLE
Online/offline list not correct

### ISSUE THREAD

**Issue by andersruneson** [anurodhp/Monal#20]
I have about 109 users in my roster, currently 35 are connected according to the server (prosody).
Gajim and Conversations displays those 35 as online but Monal just displays 15 as "online". The missing 20 can be found under "offline".

**Comment by andersruneson** [comment]
Very strange, now there are 44 users are connected and Monal only displays 5 as online.

**Comment by ungkaren** [comment]
Same problem here. Shows only part of all online/offline contacts. Anyone can help?

**Comment by anurodhp** [comment]
Sounds like a bug I'll have to investigate

**Comment by anurodhp** [comment]
looked at this tonight. It may be fixed in develop now.  If you have OS X, take a look on the latest OS X beta

**Comment by ungkaren** [comment]
Hello, thanks for your reply. 
I use MONAL on iOS ,waiting for the fix. 
Another issue: 

When I write a message, after the first few words I can't see anymore what I write. I can see he message only when I send it. 
Plus after few messages I can't see the beginning of conversation, I can see it only in the logs. 

Looking forward for a definitive fix. 

Thanks 

G.A.

**Comment by andersruneson** [comment]
I just updated to 2.9, will test this now.

**Comment by ungkaren** [comment]
Thanks dear

G.A.

**Comment by tristan-k** [comment]
The issue remains for me. I'm running Monal iOS 2.9.

**Comment by ungkaren** [comment]
Which issue? That doesn't show all contacts ? 


G.A.

**Comment by anurodhp** [comment]
Sorry for the late reply here. I can add you to the latest 3.x betas if you want to test this

**Comment by anurodhp** [comment]
This should be fixed in 3.0
