### ISSUE TITLE
Push notifications not working on iOS

### ISSUE THREAD

**Issue by WainPetopia** [anurodhp/Monal#200]
Similar to https://github.com/anurodhp/Monal/issues/83 (which is closed), I haven't had Jabber push notifications work on my iPhone since at least early January, perhaps earlier. I know they did work at some point. Even though Monal is still running (in the background), the messages never arrive until after I foreground it and wait a short while. They're timestamped for the time I foreground the app.

Push notifications are still allowed on my phone, that never changed. Also, when I foreground Monal I always get a splash screen as if the app was freshly loading. I'm unsure if that's normal or not. Unfortunately I no longer receive messages unless I constantly check.

**Comment by anurodhp** [comment]
Can you grab the new iOS beta on monal.im . I am testing something different. It was trying to show notifications only if it could get a message now it will show a generic “you have a new message notification” that goes Away when the message is downloaded.

**Comment by WainPetopia** [comment]
Thanks! I installed the beta version and tried it out. 

Unfortunately it seems to be worse. Messages still don’t arrive on time, but now they sometimes don’t arrive immediately when I foreground the app - sometimes I have to wait a bit. 

Also, some of my outgoing messages are being flagged with red ! warnings that they haven’t been sent. Perhaps this is a coincidence but I’ve never had this problem before installing the beta. 

Sorry for the bad news :(

**Comment by anurodhp** [comment]
This should be fixed by a server side upgrade tonight https://monal.im/blog/resolving-push-with-ejabberd/
