### ISSUE TITLE
[iOS] Doesn't remember active section

### ISSUE THREAD

**Issue by MarcelWaldvogel** [anurodhp/Monal#201]
When starting, Monal on iOS always ends up in "Contacts" section/pane, even if I left it in "Chats" (which is my main pane). It would be great if the previous section would be reactivated on restart.

It would be great if that also applied to #87.

**Comment by foss-** [comment]
Not limited to iOS. macOS behaves identical. #189 would be related.
A solution could be to only use "Active Chats" and only show contacts when creating a new chat.

**Comment by anurodhp** [comment]
fixed
