### ISSUE TITLE
[iOS] MUCs from Bookmarks are not respected

### ISSUE THREAD

**Issue by MarcelWaldvogel** [anurodhp/Monal#202]
I have added two MUCs to the bookmarks in other clients. When starting Monal, it does not recognize these MUCs nor auto-join them, if that flag is set..

**Comment by Echolon** [comment]
@MarcelWaldvogel 

Is this still appearing in the current version?

**Comment by Echolon** [comment]
ref. **XEP-0048: Bookmarks** #19

**Comment by Echolon** [comment]
Confirmed, after restarting Monal I cannot text and write in the group anymore. However, the group is still shown. Maybe that is a first improvement.

`Error: cancle - not acceptable`

Also there is no possibility to easily try resending.

**Comment by Echolon** [comment]
@MarcelWaldvogel 

I will close this in favor of #19 - it is on the list for implementation, hopefully this year!

If you want to help us in the meantime to get things done in the back-end you can join the [Testflight](https://testflight.apple.com/join/RjIlyvqa) and test the upcoming update! That would be a big help!
