### ISSUE TITLE
[iOS] MUC handling weirdnesses

### ISSUE THREAD

**Issue by MarcelWaldvogel** [anurodhp/Monal#203]
MUC handling is confusing/broken in several ways. (Please let me know if I should break them into multiple issues.)

Expected behavior on a fresh install*:
- Go to "groups", which is empty
- Select the parameters (with the help of auto-completion)
- Click "Join"
  * The entry is added to the lefthand list
  * Maybe it should directly switch to the chat and activate the MUC
- When switching to "Chats", the MUC should be there, once.

Actual behavior:
- Go to "groups", which is empty
- Select the parameters
  * The account selected is not shown, only when actually clicking on "Account"
  * There is no auto-completion from known (MUC) domains, so the whole JID needs to be entered (this is very inconvenient, as apparently bookmarks are not handled either, see #202)
  * For the Nick, selection from JID left hand sides would be nice
- Click "Join"
  * The entry does *not* appear on the left hand side, clicking again does nothing, either. There is absolutely no user feedback
  * After switching sections/panes and back to chats, there is one entry for each time the user had clicked on "Join" (it was a dozen or so for me). There should only be one entry (normally).
  * Deleting them by long-swiping left behaves weird: Sometimes it is directly deleted, sometimes only the "Delete" button appears, which has to be clicked. It seems to be related to swipe speed (slow swipe enables direct delete), but this is not intuitive.
- After switching to "Chats", the MUC was there twice.
  * Activating one of them while it was downloading MAM crashed Monal
  * After restarting, the MUC chat was there either twice or not at all. Deleting one of the pair would crash and delete both. Re-adding it from the "Groups" section would add it twice.

*: I had installed Monal pretty much when it first came out. It became very slow (a minute or so to start) and unreliable over time, so last week I deleted it and reinstalled it from scratch.

**Comment by MarcelWaldvogel** [comment]
After a restart, the second entry for the MUC in "Chats" is gone.

**Comment by FRNK-BK** [comment]
Which server is your user and MUC on?

**Comment by MarcelWaldvogel** [comment]
Account and MUC are on the same recent Prosody server (account on `server.domain`, MUC on `conference.server.domain`).

**Comment by Echolon** [comment]
referencing also #216

**Comment by anurodhp** [comment]
agreed this can all be fixed. working on these right now.   There probably aren't a ton of Monal 1.0 users.  thanks! sorry it slowed down. In theory it should upgrade smoothly. let me know if it happens again because it really shouldn't

**Comment by Echolon** [comment]
@MarcelWaldvogel Does this still appear?

**Comment by anurodhp** [comment]
this should be resolved with the new ui
