### ISSUE TITLE
[iOS] Messages to MUC disappear

### ISSUE THREAD

**Issue by MarcelWaldvogel** [anurodhp/Monal#204]
I cannot send messages (or HTTP uploads) to the only MUC I currently have set up on Monal. They just are not delivered to any of the members.

Also, MUC history (MAM) is unreliable. It is missing a lot of messages in that MUC.

(And there are double messages, but they probably caused by the duplicate entry in the chat window, see #203)

**Comment by Echolon** [comment]
@MarcelWaldvogel 

Hi, have you tried the current version?

**Comment by anurodhp** [comment]
this should be fixed now
