### ISSUE TITLE
Support VoIP for voice calling with other apps

### ISSUE THREAD

**Issue by smaroff92** [anurodhp/Monal#205]
Hello!
When I calling with Monal to user that using Monal, he can accept call (only if his app on foreground)
But when I call from other apps (AstraChat, aTalk ...) they shown alert ("Contact doesn't support VoIP")
Is it possible enable VoIP in Monal, and receive calls in background?

**Comment by Echolon** [comment]
Or create a parallel jitsi instance somehow

**Comment by Echolon** [comment]
And I suggest to add voice messages before this!

**Comment by anurodhp** [comment]
Monal should work with other jingle voip apps. I have tested it with jitsi and some versions of pidgin

**Comment by anurodhp** [comment]
unless this is broken, voip has worked in monal since 2012
