### ISSUE TITLE
Implement SRV lookup and use correct ALPN value in TLS

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#206]
Please implement SRV DNS-record lookup (see here: https://wiki.xmpp.org/web/SRV_Records)

This way it is possible to provide an IP/port combination different to the A-record of the xmpp domain.
Even multiple SRV records with different priority are possible and should be tried in order by clients.

This allows server operators to even use port 443 (https) as fallback for environments where only http/https is allowed and all other ports are filtered out.

To multiplex https and xmpp (and possibly others) on port 443 a correct ALPN value of `xmpp-client` and support of `_xmpps-client` SRV records is needed.

One service provider (apart from myself) using port 443 multiplexing based on ALPN values and SRV records is conversations.im

**Comment by tmolitor-stud-tu** [comment]
Additional information: XEP-0368 explains SRV records for direct TLS.

**Comment by anurodhp** [comment]
Monal has had SRV lookups since 2012.

**Comment by tmolitor-stud-tu** [comment]
But no support for XEP-0368 and it doesnt set correct ALPN TLS values.

**Comment by tmolitor-stud-tu** [comment]
this will also allow for faster reconnects and is needed in environments where slow mobile internet access prevents monal from connecting (in time, because of background)...

**Comment by Echolon** [comment]
Ref: https://xmpp.org/extensions/xep-0368.html
