### ISSUE TITLE
[iOS] OMEMO MUC group rights bug

### ISSUE THREAD

**Issue by idnovic** [anurodhp/Monal#209]
I can "activate" encryption on a MUC i do not have enough rights for.
Obviusly it does nothing but the button tries to activate encryption anyway and monal "thinks" that encryption is activated

**Comment by Echolon** [comment]
@idnovic Hi, would you be so kind and test with the current version again?

**Comment by anurodhp** [comment]
This is fixed in the 4.4 betas
