### ISSUE TITLE
Server address field is ignored.

### ISSUE THREAD

**Issue by dandrzejewski** [anurodhp/Monal#21]
When I specify a server other than the one that is in my domain's srv record, that value is ignored and the srv record is used anyway (according to the console log).

**Comment by Echolon** [comment]
Related: #206

**Comment by tmolitor-stud-tu** [comment]
I think this can be closed?
Can anyone test if this is still the case?
The issue seems to be rather old...

**Comment by Echolon** [comment]
@dandrzejewski ?

**Comment by Echolon** [comment]
I will close this, if there is something up I can reopen.

That means: Another milestone - check :heavy_check_mark: :D @anurodhp @tmolitor-stud-tu :tada:
