### ISSUE TITLE
[iOS] OMEMO chat not working

### ISSUE THREAD

**Issue by idnovic** [anurodhp/Monal#210]
I tried a direct chat with someone and the encryption did not work.
-We started as unencrypted chat
-both tried to activate encryption
-msgs where send unencrypted
-my monal showed an encryption lock but the receipient received the msgs unencrypted.

**Comment by anurodhp** [comment]
Hi is this still an issue?

**Comment by anurodhp** [comment]
should be fixed in the latest release.
