### ISSUE TITLE
[iOS] add reset button

### ISSUE THREAD

**Issue by idnovic** [anurodhp/Monal#211]
Please add a reset function to the iOS client. 
Currently monal does not work at all for me and uninstalling and installing again takes time.
I want to be able to reset it.

**Comment by idnovic** [comment]
I installed the latest beta for iOS

**Comment by anurodhp** [comment]
I’m of sure what reset would do. Do you mean the accounts? You can remove and account and readd it

**Comment by idnovic** [comment]
I do not know how monal works internally so I can only guess. For me monal seems to get stuck. By reset I mean delete config and cache. If it is possible keep the account login config so I do not need to type it again. 

Also I can not answer because I do not know why it gets stuck in the first place. 

I just like to help with the debugging but on iOS I do not have a simple way to reset monal other than uninstall and reinstall
