### ISSUE TITLE
Inline add button for XMPP-URIs (contact or MUC)

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#217]
I would like to suggest, to build an inline add button to directly add a contact to the list if someone drops an xmpp-uri. 

Maybe cross-check how conversations is doing it or how th URI from conversations look like if that's anything special.

The same goes for MUCs URIs. It also should be clear what's a single person or whats a group chat before adding/joining.

Related: #130

As XMPP environment for the moment does not provided a full contact list (by phone numbers), this is essential to easily add new people and makes it much more comfortable to get started in general.

**Comment by anurodhp** [comment]
in the latest build the links are recognized and clicking on them in monal will take you to the chat.
