### ISSUE TITLE
Set correct http content-type header on upload

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#219]
At least Prosody's `mod_http_upload_external` (share_v2.php) checks the content-type header of the HTTP-PUT-request against the content-type specified when requesting the upload slot.

Monal doesn't specify a content-type HTTP-header on upload:

**That means Monal can't upload files on servers using this prosody module.**

**Comment by centertivevier** [comment]
I can confirm it. Monal doesnt`t specify a content- type HTTP-header on upload and Monal can`t upload files.

See XEP-0363 on Point 7.
