### ISSUE TITLE
Monal sending duplicate messages

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#221]
Messages sent by Monal (version unknown, device unknown, as used by Anu on 2019-03-06) are repeated by the sending client, causing duplication on receiving clients.

While the sender re-uses the same message @id attribute, other clients are not expected to de-duplicate live messages (only messages from archives), so the messages end up doubled at the recipients.

My client shows:
```
12:52:35 Anu> Go to encryption keys and click the toggle
...
12:55:21 Anu> Go to encryption keys and click the toggle
13:00:56 Anu> Go to encryption keys and click the toggle
```

Respective raw XML:
```xml
12:52:35,151 <message id="D1889914-4ACA-4D0E-8366-514FBF6F3D31" type="groupchat" from="monal@chat.yax.im/Anu" to="..."><body>Go to encryption keys and click the toggle</body><store xmlns="urn:xmpp:hints" /></message>
12:55:21,103 <message id="D1889914-4ACA-4D0E-8366-514FBF6F3D31" type="groupchat" from="monal@chat.yax.im/Anu" to="..."><body>Go to encryption keys and click the toggle</body><store xmlns="urn:xmpp:hints" /></message>
13:00:56,518 <message id="D1889914-4ACA-4D0E-8366-514FBF6F3D31" type="groupchat" from="monal@chat.yax.im/Anu" to="..."><body>Go to encryption keys and click the toggle</body><store xmlns="urn:xmpp:hints" /></message>
```

**Comment by anurodhp** [comment]
oddly there isn't actually any retry logic ( I thought there was some old stuff). as far as I can tell I am sending the message once.  The fact that is is arriving several minutes apart makes me think this may be server side

**Comment by ge0rg** [comment]
I can assure you that there is no server-side component like that. Maybe you have the message in your "to send" queue, and you drain that queue on each c2s reconnect, without marking the message as "has been sent already", so with often reconnects it will be retransmitted?

**Comment by anurodhp** [comment]
should be fixed in the latest release.

**Comment by Echolon** [comment]
Hello,

regarding my own experience for quite a while and also just today (version 4.3) i would like to reopen.

Sending server is blabber.im. It gets replicated to Conversations - however NOT to Dino, which I also use. I will try to get logs from blabber.im admins.

**Comment by Echolon** [comment]
OMEMO is not active to exclude any encryption reasons

**Comment by Echolon** [comment]
Some extract from blabber.im, but to so detailed as they doesnt log so much...

```2020-02-21 12:33:32.224 [info] <0.27761.183>@mod_stream_mgmt:handle_resume:442 (tcp|<0.27761.183>) Resumed session for JABBERID@blabber.im/Monal-iOS.54
2020-02-21 12:33:32.105 [info] <0.27761.183>@ejabberd_c2s:process_auth_result:267 (tcp|<0.27761.183>) Accepted c2s PLAIN authentication for JABBERID@blabber.im by sql backend from hidden_by_ejabberd
2020-02-21 12:33:32.303 [info] <0.27761.183>@mod_push:enable:308 Enabling push notifications for JABBERID@blabber.im/Monal-iOS.54
2020-02-21 12:06:22.452 [info] <0.19786.183>@mod_push:enable:308 Enabling push notifications for JABBERID@blabber.im/Monal-iOS.54
```

**Comment by anurodhp** [comment]
my guess is that if monal retries it uses the same messaged and some clients my dedupe on that and others dont

**Comment by Echolon** [comment]
Dino does not, but Conversations

**Comment by Echolon** [comment]
I discussed the issue, this was the outcome (not from me):

> **Sounds as if Monal tries to resend messages when it thinks the first attempt failed. If this happens often, I assume that Monal is often wrong with this assumption and already the first attempt was successful.**
> If the stream management session can be resumed is trivial for clients to check if the first attempt failed. If this happens often with Monal, it will somehow make the easy case wrong.

For me it happens at least with two contact which both only use Monal (as sending party).

> That's the way it's gonna be:
> **Guess is that if Monal retries it uses the same messaged and some clients may dedupe on that and others dont**
> The question is whether Monal didn't regress too often. If Monal really wanted to, Monal would never have to _(@anurodhp  can check the MAM archive for outgoing messages with Origin IDs Monal gave itself; and delete messages from his outgoing queue accordingly)_. 
> But as I said, let's guess that its already down in **stream management**.
> So just to explain the **stream resumption case**: The idea of stream management is that both Monal and its server count the stanzas that Monal sends. Then Monal loses the connection. And then Monal resumed its session over a new connection. In the process, the server tells Monal how many stanzas it has received. For example, 100, but Monal has sent 102. So Monal knows it has to retransmit the last two.
> An astonishing number of clients (and servers) had **problems with counting in the beginning**. Which then leads to too many or too few messages being resent when resuming. But not sure how Monal does these things.

**Comment by Echolon** [comment]
@tmolitor-stud-tu maybe you also have some ideas about this.

**Comment by licaon-kter** [comment]
CS often miscalculates, my server logs were full of "X stanzas, but X+Y requeste" or whatever the message was.

**Comment by Echolon** [comment]
@licaon-kter may you provide some more detailed logs or a decent example? That would be very helpful!

**Comment by licaon-kter** [comment]
No, I don't see this now with Monal, no more CS users, but then again I rarely see a user connected with Monal anyway.

**Comment by tmolitor-stud-tu** [comment]
To me this sounds exactly as the stanza counting bug I told you about a few days ago.

My pull request *might* solve the issue, but I'm 100% not sure.

**Comment by Echolon** [comment]
#360 **Some smack fixes**

https://github.com/anurodhp/Monal/pull/360/commits/0e8ab07189c2b01ea12279241cab38213b0161a6

**Comment by anurodhp** [comment]
the patch seems to have fixe the counting issue. It appears to be related to a zero vs 1 index resulting in a counting error
