### ISSUE TITLE
MUC: Encryption & device publishing

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#225]
Hi,

as already texted to you, we expienced the following issue during testing OMEMO in group chats:

One client replied, that no devices were published from the monal app:

`<iq xml:lang='en' to='fabianuwpx@sprint.kaidan.im/UWPX_1392393637' from='marekmonalios@sprint.kaidan.im' type='error' id='7c3ee62b-a05d-4c73-8879-9af04060b413'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.devicelist' max_items='1'/></pubsub><error code='404' type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Node not found</text></error></iq>`

The opponent client was UWPX (windows) and the server ran ejabberd FYI.

**Comment by Echolon** [comment]
@COM8

Have you crossed checked about this again?

**Comment by anurodhp** [comment]
I believe this has been fixed. reopen if it isn't.

**Comment by Echolon** [comment]
Re-open on users request

**Comment by anurodhp** [comment]
on the newest beta, 1) make sure you are both have the other approved as contacts. This will show in details if one cant see the others keys.  2) upgrade all monal clients to the beta. There is a bug in current clients the accidentally wipes the devices 3) log out and log in all monal clients (use the log out, reconnect all buttons at the top right of settings). this will republish devices.

**Comment by anurodhp** [comment]
sorry  i just realized this said muc :(

**Comment by Echolon** [comment]
Hi,

I think it does not make sense to keep this open anymore. Both sides have changed a lot. Especially the OMEMO implementation.

I suggest to comeback with new experienced errors and maybe some logs another day if somethings happens.
