### ISSUE TITLE
Send XEP-0184 Delivery Receipts for MAM messages

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#226]
You should not treat messages received directly and messages received via MAM any different.
That means: a new message received via MAM catchup should trigger a XEP-0184 receipt as any directly received message would, too.

Otherwise the following workflow (which happens a lot) will not trigger such receipts correctly:

1. monal is not connected to xmpp sever
2. monal receives a push triggered by a new message
3. monal connects to xmpp sever
4. monal receives the message that triggered the push via MAM and displays it

**Comment by Neustradamus** [comment]
XEP-0184 is not only for MAM.

**Comment by tmolitor-stud-tu** [comment]
@Neustradamus I didn't say they are only for mam ;)

**Comment by tmolitor-stud-tu** [comment]
this is probably due to #268

**Comment by tmolitor-stud-tu** [comment]
Also: the receipts should have a XEP-0334 store-hint to make them reliable.
