### ISSUE TITLE
No change log for iOS releases

### ISSUE THREAD

**Issue by Midar** [anurodhp/Monal#230]
The latest iOS release says that it fixes a security problem. However, there is no changelog to be found from which it could be derived what kind if security problem even, and what needs to be rotated. E.g. was TLS verification not properly and I should change my server password? Was OMEMO not done properly and I should regenerate my keys? Users should have a way to know what changed and what they need to do.

**Comment by anurodhp** [comment]
good point,  I usually do include a better description. this is the specific bug:
https://github.com/anurodhp/Monal/issues/222
