### ISSUE TITLE
Sending OMEMO images doesn't work!

### ISSUE THREAD

**Issue by Chobbes** [anurodhp/Monal#231]
Hi there!

OMEMO seems *so close* to perfect in monal, which is fantastic! But, I'm having this problem here. If you enable OMEMO in a chat, and then try to upload an image (http upload, if that matters)... It gets stuck uploading the image, and it just spins forever until the app is closed.

Perhaps this is somewhat related to this situation:

https://github.com/anurodhp/Monal/issues/176

Thanks for all the work on this so far!

Context here is iOS.

**Comment by Echolon** [comment]
@Chobbes 

First of all is the issue still existent with the current release?

Have you tried with a compliant server? https://compliance.conversations.im/

**Comment by anurodhp** [comment]
in latest beta
