### ISSUE TITLE
Not available in France

### ISSUE THREAD

**Issue by meaz** [anurodhp/Monal#236]
I've read there https://monal.im/blog/omemo-and-french-laws/ that it is still not available in France. ANy news about that?

**Comment by anurodhp** [comment]
Will be addressed by iOS 13.

**Comment by bouscram** [comment]
What about macOS ?

**Comment by anurodhp** [comment]
While it’s not in the Mac App Store, nothing stops you from downloading the zip from the website

**Comment by bouscram** [comment]
> While it’s not in the Mac App Store, nothing stops you from downloading the zip from the website

This is exactly what I did... But I prefer to have to use App Store validated apps on my company laptop when possible.

**Comment by anurodhp** [comment]
This will be fixed by iOS 13 and Catalina

**Comment by Echolon** [comment]
Ref: http://monal.im/blog/ios-4-2-final-beta/

**Comment by Echolon** [comment]
> Some updates for OMEMO coming. First, I noticed a bug there I was using an initialization vector of 16 bytes instead of 12 bytes. While a lot of clients seems to tolerate this, the extra 4 bytes may explain some of the cases where Monal worked with some clients but not others. Since this is an encryption related bug I should clarify, I am not aware of any security issue with this it is just inefficient and not the suggested size. I am hoping this improves compatibility. Flapping bugs like this are really hard to diagnose and fix because unlike a lot of other things, it doesn’t always fail.
> Second, I have OMEMO working with Apple’s native AES-GCM libraries. This removes the dependency on OpenSSL and I have OEMEO working in mac catalyst bulds as well now (try the latest build form the link on the side).
> Finally, the pending removal of openssl will allow me to return to the French app store in the future.

https://monal.im/blog/omemo-fixes-catalyst-and-france/

**Comment by anurodhp** [comment]
https://monal.im/blog/monal-4-3-is-coming-out-in-about-a-week-even-in-france/

**Comment by anurodhp** [comment]
fixed

**Comment by Echolon** [comment]
https://monal.im/blog/monal-ios-is-available-in-france/

> Monal 4.3 if out for iOS. Mac os will come soon. It’s taking longer because it is treated as a new app. I am leaving the other mac app in the app store for older macs. This change in 4.3 also means it is now available in france.

> On a related note the first build of 4.4 for Mac is in beta. This has some fixes for message duplication as well as OMEMO device and key discovery. iOS will come soon.
