### ISSUE TITLE
Some received messages missing with multiple monal accounts

### ISSUE THREAD

**Issue by jelmer** [anurodhp/Monal#237]
When having two iOS devices running Monal active on a single account, one of them sometimes doesn't see all the received messages. I haven't been able to work out a pattern yet.

**Comment by Echolon** [comment]
Hi @jelmer,

have you tried the current version? Or can you be more specific about the issue?

**Comment by jelmer** [comment]
Sorry, I've given up on Monal for the moment. This should be really to reproduce if it's still an issue though.

**Comment by anurodhp** [comment]
this shouldn't be an issue anymore.
