### ISSUE TITLE
Autostart at boot

### ISSUE THREAD

**Issue by andersruneson** [anurodhp/Monal#24]
For me this does not work, is Monal suppose to start at boot? (without opening the app first)

**Comment by anurodhp** [comment]
If you have the app running and restart iOS, Monal will restart. There is no way to auto start an app that was closed ( swipe up).

**Comment by andersruneson** [comment]
Just tried as you said, I had Monal running and did a phone shutdown and then started with the power switch. I could not see Monal logged in to the server after booting and unlocking the phone, checking with Gajim. Is there any way in ios I can see running apps?

**Comment by andersruneson** [comment]
Second try this worked so I will test some more tomorrow.

**Comment by anurodhp** [comment]
It should definitely work. Its something provided by the OS (since iOS4) and not really something I control. Make sure Monal is running, try restarting, give it a second for everything to start up. You can double tap home to see all the apps that are running.

**Comment by andersruneson** [comment]
When it fail it was probably running but maybe did not connect. Even when i
started monal it did not connect. Maybe it tries before WiFi is
established? This phone has no sim card so it may be something that is
different then.

I'll try again a few times tomorrow.

**Comment by andersruneson** [comment]
Gah, I've tested maybe 10 times now, mostly Monal stays disconnected even if I wait 10-15 minutes. 
When I open Monal, once it stated "Could not login" another time "Logging in" (for at least 20 minutes before I manually disconnected and connected again).

Could it be a stream resumption issue? Does Monal try to restore the old session after reboot?

At one time I saw this in the prosody log, notice how the client connected at 10:34 but not until I opened Monal it logged in at 10:40:
Mar 08 10:34:17 c2s2ead000      info    Client connected
Mar 08 10:40:36 c2s2ead000      info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Mar 08 10:40:36 c2s2ead000      info    Authenticated as user@server.com
Mar 08 10:40:57 c2s2ead000      info    Client disconnected: closed

**Comment by anurodhp** [comment]
I'll have to go back and look at this. one caveat, If the device is locked the keychain is locked and Monal can't access the password.

**Comment by Mrfuyu** [comment]
Same problem here.

**Comment by anurodhp** [comment]
Monal will now just launch itself ( startup or not) if there is a message.  I think that should resolve your issues.
