### ISSUE TITLE
Delete Prior Conversations with Contact

### ISSUE THREAD

**Issue by mayjethva** [anurodhp/Monal#241]
I would like to know how to delete old messages with contacts.  I have gone through and swiped them out to delete, have closed the conversation and have deleted the contact and re-added.  None of these work and the messages reappear once I start a new chat.

Is there a special way to do this or is it currently being worked on?

Thanks.

**Comment by Echolon** [comment]
Ref.

**Option request: Delete full history per contact at once** #180

**Comment by Echolon** [comment]
@mayjethva I will close this as this is a duplicate of #180 I think.

Please report if you see anything different!
