### ISSUE TITLE
Advanced Server Setting ignored (SSH Forward Tunnel, SRV)

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#242]
Hi!

When trying to tunnel through a SSH forward tunnel, Monal is unable to establish a connection to the server. It tries to connect to the server specified in DNS SRV RR, but not to the server configured in Advanced setting for the server address, e.g. 127.0.0.1 port 5222, which forwards this to the real XMPP server. 

However, other XMPP clients such as Psi+ or Jitsi do work that way, so I assume this should also work with Monal... :-)

**Comment by Echolon** [comment]
ref. #21 #206 #385

**Comment by Echolon** [comment]
@ingoj  would be so kind and review you issue with the current version or even better the current Testflight of Monal?

**Comment by anurodhp** [comment]
so i think i know whats going on here,  we need to be able to override the server address to ignore the DNS entry so it goes via the local address

**Comment by ingoj** [comment]
> @ingoj would be so kind and review you issue with the current version or even better the current Testflight of Monal?

Currently a little bit difficult... as many of us I'm working now at home and not in the office anymore where the restrictive firewall is and where I need to tunnel through SSH. But as soon as I'm back in office, I can test... 

Another idea instead of using SSH tunneling would may be using http-alt-connect... therefor I could imagine something like: 
1. try SRV record
2. try A record
3. try http-alt-connect
4. try ssh forwarding

**Comment by tmolitor-stud-tu** [comment]
@anurodhp Yes, I fixed it, see my newest pull request :)

**Comment by Echolon** [comment]
Just another milestone :tada
