### ISSUE TITLE
Monal messages multiple devices

### ISSUE THREAD

**Issue by mayjethva** [anurodhp/Monal#243]
I am having issues between Monal and conversations. The accounts messaging each other are in multiple devices. When sending messages from monal only one of the devices from the recipient receives the message. When sending from conversations, all recipient conversations accounts receive the message and only sometimes does monal.

Does monal need to be setup for multiple device accounts to work? Is this something that is being worked on? 

Thanks.

**Comment by sokai** [comment]
One additional question: with which priority (XMPP) is Monal acting? (Conversations is running with prio 0.)

If the connected clients are running with several priorities only the device with the lowest prio will receive messages. Only if all clients are set up with the same prio, the possibility to receive messages on all of that devices is enabled.

**Comment by anurodhp** [comment]
Pushed an update that may fix this today. Should be out this week

**Comment by Echolon** [comment]
@mayjethva Is the issue still existent?

**Comment by anurodhp** [comment]
Closing this as fixed I haven't seen this issue in a while. can reopen if needed.
