### ISSUE TITLE
Monal doesn´t send files on omemo with aesgcm://

### ISSUE THREAD

**Issue by centertivevier** [anurodhp/Monal#244]
Hi,

Testing Versions:

IOS: Monal 3.6
Android: Conversations 2.5.1
Server: Prosody 0.11.2 with HTTP Upload

with the new version of Monal can received files (images at this moment) with "aesgcm://" from Conversations and decrypted this. It´s very fine, but Monal send files on a OMEMO-Chat on HTTP-Upload with "https://". Conversations get this message and posted the link to the file. Of course the image/file is not decrypted with this method on the http-upload and you can see this one over the link in all browsers!

Can you fix it on a next realease, so that Monal send files/images with aesgcm:// on a OMEMO-Chat. Because on the issues with the old reason to this subject, you write it gives problems with the cryptograhpy on this one.

**Comment by Echolon** [comment]
I think this is in work in progress: https://monal.im/blog/progress-on-omemo-and-push/

**Comment by Echolon** [comment]
security and privacy: dont inline every image url #224

Also actually double

**Comment by centertivevier** [comment]
You are right. Is it a double issue. I close this one, because anurodhp is still working on this.
