### ISSUE TITLE
aesgcm Files show like other previous sent file

### ISSUE THREAD

**Issue by maxbax0808** [anurodhp/Monal#245]
So I discovered this while chatting with a friend and he sent some pictures and some PDF-Files over. Every single thing he sent over was the exact same thing on my iPad, looking like the first Picture he sent. Checking on my Linux Machine I saw everything correctly using Gajim. 
Now he sent some more photos and now every photo (even those from before) looks like the one he sent me now...

**Comment by jelmer** [comment]
FWIW I can reproduce this as well. It doesn't seem to be 100% consistent, i.e. the picture that is replicated will change as new pictures come in.

**Comment by anurodhp** [comment]
I believe I have fixed this.

**Comment by anurodhp** [comment]
should be fixed in the latest release.
