### ISSUE TITLE
Bug: Monal says message not send but it is actually send

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#246]
Hi,

a user just reported this to me:

He sent an encrypted text message but Monal was warning that the message wasn't send by: 
`Failed to send Message. Retry?`

<img src="https://user-images.githubusercontent.com/29168011/58049045-32b58a80-7b4c-11e9-89ec-6fede6e9b846.jpg" width="350">

You might don't understand the conversation, but I replyed to all messages which seemingly hasn't been send. So I still received them correctly.

I ask him to send uncrypted, that somehow helped, but not sure if that really was the solution. later back sending again encrypted messages worked.

System:
Sending: Monal 3.6, prosody server
Receiving: Conversations/Dino (I was at my desktop but also using my phone), ejabberd server

Please change the title if too imprecise!

_PS: He said he tried to send pictures from the Gallery (or whatever that thing is called on iOS), but he couldn't chose Monal. From the app it works, but as I heard this particular often from ChatSecure people that should be possible as well I think._

Cheers

**Comment by anurodhp** [comment]
should be fixed in the latest release.
