### ISSUE TITLE
New Monal install doesn't create OMEMO keys

### ISSUE THREAD

**Issue by pgeorgi** [anurodhp/Monal#247]
A friend just migrated to a new phone and while Monal was copied, it's config wasn't. Looks easy enough, we set it up anew. Unfortunately my Conversations client still has the old OMEMO key data and tries to use that, so all my friend receives is "not encrypted for this device", while I get unencrypted messages from him.

His Monal has an idea about my OMEMO keys, but on the "My Keys" pane it shows no keys of its own and also doesn't announce them to my client. He pressed the keylock icon on my account and the lock is closed, so I think we should be all set. What's missing?

**Comment by anurodhp** [comment]
This should be fixed in iOS 3.7 and the most recent Mac beta. 3.7 will be out this week
