### ISSUE TITLE
Bug: Inline pictures switches randomly

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#248]
Hello hello,

new bug, new luck! Here we go:

iOS: 12.3
Monal: 3.6
Sending party: Conversations, Android 

My friend told me that the picture as shown here was shown the first time like this:

<img src="https://user-images.githubusercontent.com/29168011/58123529-504a2900-7c0c-11e9-9d53-71aa1c528cbd.jpg" width="250">

Then, when the app is reopened (from tab not from restart), the following picture is shown:

<img src="https://user-images.githubusercontent.com/29168011/58123500-3ad4ff00-7c0c-11e9-8bae-e4ad62a1fa51.jpg" width="250">

This is the **actual picture I send**. The previous picutre is from the history, but was also send by me sometime before. So you recognise that those are two different pictures shown. Of course the user is confused.

Hope that helps to find the bug. I can also confirm that this happened to another contact as well.

Cheers

**Comment by anurodhp** [comment]
I think this is fixed in 3.7 which should be out this week, if it isn't fixed please reopen.
