### ISSUE TITLE
MUC: List participants in the MUC description

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#249]
Hello,

new users often thinks that there are no people in the MUC they are invited to. So it would be great to list the participants and maybe also the number of participants.

Not sure if related: 

- **Not fetching contact list** [#11](https://github.com/anurodhp/Monal/issues/11)
- **[iOS][UX] MUC handling weirdnesses** [#203](https://github.com/anurodhp/Monal/issues/203)

PS: Also, contacts which are already registered to a group, don't see the exsisting groups in their list once they add their account to Monal. I think invitations from other clients to the MUC also doesn't work appropiately

Furthermore I would like to remind of this:  
- **MUC/group chat: Message double, shown from sender AND recipient** [#216](https://github.com/anurodhp/Monal/issues/216) 
Still appears, also/only in MUCs.

**Comment by anurodhp** [comment]
the participants is listed under detail s-> resources but i agree its not clear at all -- naming too .

**Comment by Echolon** [comment]
Will close this, I think that was improved
