### ISSUE TITLE
only displaying first line in composing edit field

### ISSUE THREAD

**Issue by jubalh** [anurodhp/Monal#25]
It seems that when writing more than one line it only displays the first line in the edit field of the chat window. Which makes it hard to write :-)
I haven't tested this myself but a friend wrote me about it. He is using latest AppStore version.

**Comment by apokharel** [comment]
This has been fix in the version that should be published this week. There is about a week lag between finishing a version and publishing as it waits for apples review

**Comment by jubalh** [comment]
Very nice. Thank you!
