### ISSUE TITLE
Contacts appear as offline even though they're connected to the Internet

### ISSUE THREAD

**Issue by marmistrz** [anurodhp/Monal#250]
Setup: I'm using Conversations+Gajim, the remote contact uses Monal.

If the remote contact doesn't use the app for a while, they appear as offline, even though they're still connected to the Internet. When I send them a message, they appear briefly as online and are displayed as offline once again after a while.

This may be of importance: the remote contact does swipe the app away.

**Comment by anurodhp** [comment]
This is correct. This is a limitation of xmpp. The online/offline thing isn’t real. It’s like what’s app has last seen.

**Comment by marmistrz** [comment]
@anurodhp Can you please elaborate why this is a limitation of XMPP? As far as I know, XMPP servers use XEP-0199 (XMPP Ping) to determine whether the contact hasn't disconnected.

**Comment by eveofdestruction** [comment]
How does conversations succeed in this?  I only see a similar android behavior for roster contacts (with mutual presence exchange) when they have failed to disable overbearing battery management

**Comment by licaon-kter** [comment]
@eveofdestruction maybe not Conversations but Android ;)

**Comment by anurodhp** [comment]
Yeah there is a reason iOS devices have always had smaller batteries/less ram but much better battery life than android. Android is copying the iOS battery management now
