### ISSUE TITLE
Delay in receiving messages

### ISSUE THREAD

**Issue by destruktiw** [anurodhp/Monal#251]
During the last week, I was receiving notifications about new messages with great delay, multiple at once, the next day after they were sent.

I have an account on dismail.de (Prosody 0.11.1), contact uses wiuwiu.de (Prosody 0.11.2)

My device/system details:
iPhone XS running on iOS 12.3.1
Monal version 3.6 (354)

**Comment by Echolon** [comment]
Hello,

all the servers you named in the previous textversions:

- wiuwiu.de (Prosody 0.11.2)
- dismail.de (Prosody)
- magicbroccoli.de (ejabberd 18.12.1)

are part of the same 'developer-group' whose once called theirselves "XMPP-Comminty". Please also contact them about that. I am a bit suspious you named exactly those servers.

@mightyBroccoli

**Comment by sebastiansterk** [comment]
@destruktiw 
Can you provide steps how to reproduce the problem?
Have you experienced this behavior when using Gajim, Conversations or other clients?

**Comment by anurodhp** [comment]
The delay in arrival makes me suspect its something with CSI and push interactions on the account

**Comment by marmistrz** [comment]
Does Monal show a notification if the background connection to the XMPP server fails? (one common reason for such failures is 5222 outgoing being blocked)

I have a much simpler explanation: 
1. @destruktiw receives messages. Push notifies Monal that there are messages to be fetched. Monal tries to fetch messages.
2. Connection to dismail.de:5222 fails. No notification about it is shown, so the user doesn't know that the failure has occurred
3. The user switches network, but Monal doesn't retry fetching the messages until another push event (message) arrives.

**Comment by anurodhp** [comment]
Monal will show a generic notification regardless of whether the message is downloaded or not.
