### ISSUE TITLE
XEP-0308: Last message correction

### ISSUE THREAD

**Issue by marmistrz** [anurodhp/Monal#252]
https://xmpp.org/extensions/xep-0308.html

**Comment by anurodhp** [comment]
realistically, probably in fall 2019

**Comment by Echolon** [comment]
@tmolitor-stud-tu isn't this included already?

**Comment by tmolitor-stud-tu** [comment]
Yes it is

Am 26. Januar 2021 19:21:54 MEZ schrieb Echolon <notifications@github.com>:
