### ISSUE TITLE
[iOS] Keyboard covers JID and password fields on Welcome UI

### ISSUE THREAD

**Issue by ivucica** [anurodhp/Monal#253]
![5DA5662C-5065-4CDA-964B-50D8C89587E8](https://user-images.githubusercontent.com/477596/58890954-847d1980-86e3-11e9-81fc-67261f7cccb1.png)

On the welcome dialog, keyboard is covering JID and password fields when focusing on either of the fields.

**Comment by anurodhp** [comment]
That should auto scroll. Will fix, thanks
