### ISSUE TITLE
Roadmap: Suggestiongs on changes for the summer plan

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#254]
Hey Anu,

you were just mentioning your plan for the summer, which was for iOS:
https://monal.im/blog/wwdc-2019-and-the-future/

```
- Registration, Password change and QR codes.
- Dark Mode
- Muc fixes /Mix
- New Contact List
- encrypted attachments
- simple video/audio support
```

Of course, I absolutely appreciate you fight the iOS front. This comment shouldn't be  any pushing nor "telling you what to do". Just a feedback from what I see when my friends use Monal and what they are missing or hassle with. Hence, I would just like prioritize in the following way (for the next months, so strikethrough is meant as postponing): 

- Registration, Password change ~~and QR codes.~~
- Voice messages   ~~simple video/audio support~~
- Muc fixes ~~Mix~~
- encrypted attachments
- New Contact list (?)
- (Dark Mode)

Why did I reorder? I think two things which are missing in Monal, to get people _accepting_ it. It's actually not about features, but basic functions. This is why I would prioritize working groups/MUC. If MIX helps, that's fine, but if you can get it right for the moment without, that should be the current choice I think. For users of other clients, encrypted attachments are also important. One feature, which is really in the _"need"_ of _"iPhone people"_ is **voice messaging**. I wouldn't go for calls or video now. Also Dark Mode, not a priority I think. 

People rather miss Dark Mode and Calls/Video, than hassling with not haveing voice messages or weird group management.

I hope you see my arguments. For sure, this is your software and I am personally always patient on your progress.

Therefore thanks a lot for your work! :heart:

**Comment by anurodhp** [comment]
I think we are in agreement, the video/audio is voice messaging

**Comment by stevenroose** [comment]
Just stable and reliable (group) chat and omemo would already be a great achievement. It's crazy how often I have to go check Conversations because my other clients fuck up message fetching or reliable broadcasting. Conversations is just super reliable. That's how a client should be. All the rest is optional extras.

**Comment by Echolon** [comment]
But remind the platform and its users. Something like voice messages is still important, steven roose

**Comment by Letterus** [comment]
Having problems using MUC on macOS (room is shown three times) and iOS (cannot join, simply nothing happens). Would highly appreciate a fix here and even set a bounty if this is helpful for someone. Thank you for your commitment!

**Comment by anurodhp** [comment]
muc should be heavily improved in the lates iOS beta. I just completed a lot of the major changes needed in that code

**Comment by Echolon** [comment]
With respect to
