### ISSUE TITLE
URL links open to image, not webpage

### ISSUE THREAD

**Issue by johnfdl** [anurodhp/Monal#255]
I'm relatively new to Monal but in 2.3 (127) this worked, but in later versions it doesn't.  Here's the issue.  

My friend and I both use Monal with our google ids and we're both running it on MacOS.  I like Monal better than google hangouts. 
My friend sends me a link (such as this one:  https://www.redfin.com/OR/Portland/6735-SE-Brooklyn-St-97206/home/26400429 which shows in my monal IM window as an image of the house (which I love).  I click on it and it takes me to the URL of the image, not the URL above that my friend sent.  As I said, this works when I run 2.3 (127) but doesn't work in more recent/latest versions.

**Comment by anurodhp** [comment]
Thanks I’ll take a look.

**Comment by anurodhp** [comment]
fixed.
