### ISSUE TITLE
MAM doesn't work with Prosody / Monal 1.3

### ISSUE THREAD

**Issue by lumines** [anurodhp/Monal#26]
I've updated Monal to 1.3 from the Mac App Store but the new MAM feature doesn't seem to work. Should it work out of the box or do I need to activate it on the client manually?

I'm using Debian Jessie, Prosody 0.9.7 from the Debian repositories and the most recent mod_mam on my server. At least with Conversations (Android) on my phone MAM seems to work without any issues.

Btw, thanks for this awesome client!

**Comment by anurodhp** [comment]
It should work out of the box but there was an issue handling time stamps. I am testing  with prosody to make sure it works there too.

**Comment by anurodhp** [comment]
This is fixed. If you want to test it out, grab the latest OS X beta from monal.im
