### ISSUE TITLE
Incomplete Push Notifications with Multiple Devices 

### ISSUE THREAD

**Issue by a11fruitless** [anurodhp/Monal#261]
Client A: Gajim 1.1.2
Client B: Gajim 1.1.2 & Monal (iOS) 3.8 (377)
Server: Prosody 11.2 (up to date relevant XEPs: 0198, 0313, 0352, 0357)

It seems plausible that this is reproducible with other permanently connected clients aside from Gajim. Ultimately, it is causing me significant delays in receiving messages, and I am not certain this isn't intended behavior. OMEMO is involved, but I'm not sure that matters.

To reproduce:
All clients connected and communicating normally. Client B's Monal (iOS) is left idle and eventually logs out. This is confirmed in Client A's roster with the missing resource and in the server logs.

Client A then sends another message to Client B. Message is received by Client B's Gajim and Client B's Monal client is observed to log back in from push. However, no notification of a new message is received by Monal. If Client B opens Monal, the message is there (from MAM?) and everything proceeds as normal. 

Here is the issue with this behavior:
If client B steps away from their permanently connected client for the day leaving it on and takes their Monal device, they will not receive notifications of new messages until their permanently connected device has logged out (or they just log into Monal manually to check for new messages).

**Comment by anurodhp** [comment]
Fixed in the latest beta.

**Comment by a11fruitless** [comment]
Great! Thank you for your help!
