### ISSUE TITLE
Push Not Working after a Few Days

### ISSUE THREAD

**Issue by mayjethva** [anurodhp/Monal#262]
Hi,

After several days, the push messaging on Monal is not working and we are not receiving messages on the Monal devices.  In order for Monal to work again, the person on the Monal phone needs to send a message out to get push working again, but this only lasts a few days again.

Is this normal for the push to stop working so frequently?  All devices are using OMEMO.

Thank you.

**Comment by anurodhp** [comment]
This is definitely not normal. Can you give me some more info about your setup? Which server software etc,
