### ISSUE TITLE
XEP-0198 stanza counting errors

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#263]
Monal has significant stanza counting bugs observed after a smacks resume:

`Jul 08 01:07:54 c2s555fdd118940 debug   SEND(34): <a xmlns='urn:xmpp:sm:3' h='203'/>
Jul 08 01:07:54 c2s555fdd118940 debug   RECV(40): <a xmlns='urn:xmpp:sm:3'  h='1079' ></a>
Jul 08 01:07:54 c2s555fdd118940 debug   Received[c2s]: <a xmlns='urn:xmpp:sm:3' h='1079'>
Jul 08 01:07:54 c2s555fdd118940 debug   #queue = 0
Jul 08 01:07:54 c2s555fdd118940 debug   RECV(40): <a xmlns='urn:xmpp:sm:3'  h='1074' ></a>
Jul 08 01:07:54 c2s555fdd118940 debug   Received[c2s]: <a xmlns='urn:xmpp:sm:3' h='1074'>
Jul 08 01:07:54 c2s555fdd118940 debug   #queue = 0
Jul 08 01:08:14 c2s555fdd118940 debug   RECV(40): <a xmlns='urn:xmpp:sm:3'  h='1079' ></a>
Jul 08 01:08:14 c2s555fdd118940 debug   Received[c2s]: <a xmlns='urn:xmpp:sm:3' h='1079'>
Jul 08 01:08:14 c2s555fdd118940 warn    The client says it handled 5 new stanzas, but we only sent 0 :)
Jul 08 01:08:14 c2s555fdd118940 debug   Client h: 1079, our h: 1074
Jul 08 01:08:14 c2s555fdd118940 debug   #queue = 0
Jul 08 01:08:15 c2s555fdd118940 debug   RECV(45): <inactive xmlns='urn:xmpp:csi:0' ></inactive>`

**Comment by tmolitor-stud-tu** [comment]
better formatting:
```
Jul 08 01:07:54 c2s555fdd118940 debug   SEND(34): <a xmlns='urn:xmpp:sm:3' h='203'/>
Jul 08 01:07:54 c2s555fdd118940 debug   RECV(40): <a xmlns='urn:xmpp:sm:3'  h='1079' ></a>
Jul 08 01:07:54 c2s555fdd118940 debug   Received[c2s]: <a xmlns='urn:xmpp:sm:3' h='1079'>
Jul 08 01:07:54 c2s555fdd118940 debug   #queue = 0
Jul 08 01:07:54 c2s555fdd118940 debug   RECV(40): <a xmlns='urn:xmpp:sm:3'  h='1074' ></a>
Jul 08 01:07:54 c2s555fdd118940 debug   Received[c2s]: <a xmlns='urn:xmpp:sm:3' h='1074'>
Jul 08 01:07:54 c2s555fdd118940 debug   #queue = 0
Jul 08 01:08:14 c2s555fdd118940 debug   RECV(40): <a xmlns='urn:xmpp:sm:3'  h='1079' ></a>
Jul 08 01:08:14 c2s555fdd118940 debug   Received[c2s]: <a xmlns='urn:xmpp:sm:3' h='1079'>
Jul 08 01:08:14 c2s555fdd118940 warn    The client says it handled 5 new stanzas, but we only sent 0 :)
Jul 08 01:08:14 c2s555fdd118940 debug   Client h: 1079, our h: 1074
Jul 08 01:08:14 c2s555fdd118940 debug   #queue = 0
Jul 08 01:08:15 c2s555fdd118940 debug   RECV(45): <inactive xmlns='urn:xmpp:csi:0' ></inactive>
```

**Comment by Echolon** [comment]
Can it be that the message repetition bug (messages are send again and again) is related to this?

Actually the bug I mentioned a few months ago is still there

**Comment by tmolitor-stud-tu** [comment]
Yes, that could be.

What bug do you mean?

**Comment by anurodhp** [comment]
this if i understand correctly is messages coming in and the repetition is for messages going out

**Comment by tmolitor-stud-tu** [comment]
@anurodhp oh...yes, you are right.

**Comment by anurodhp** [comment]
I think this may be fixed now.
