### ISSUE TITLE
no mam query on failed smacks resume (or no resume tried/first connect)

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#268]
If the app is connecting and not doing a smacks resume (first connect, resume failed etc.) it should query the MAM archive for new message:

- for all messages of the last few days on first connect (enhancemend: infinite scrolling  in UI should load older messages from archive)
- all messages since the last received one for failed smacks  resume

**Comment by anurodhp** [comment]
hopefully fixed in the next beta

**Comment by anurodhp** [comment]
It should query everything from the lat stanza received.
