### ISSUE TITLE
Push notifications server setup in ios

### ISSUE THREAD

**Issue by NagarajuMetavoxx** [anurodhp/Monal#270]
we are download the given source code from git and fixed some basic issues related to bundle id...etc.
Now  downloaded app is running successfully in my iPhone 6s. I can able to send voip device token and udid to your server (https://push.monal.im:5281/push_appserver/v1/register) and I am getting success response. But we are  not getting the push notifications when app is terminated.  I don't know what I am missing.

so can you please  let me know the process of push notifications setup.....

**Comment by anurodhp** [comment]
the push server only works with code that i have signed myself. If you would like to run it from source you will have to run your own push server.

**Comment by NagarajuMetavoxx** [comment]
Can you please tell me the process of make push server
