### ISSUE TITLE
All History Cleared 

### ISSUE THREAD

**Issue by NagarajuMetavoxx** [anurodhp/Monal#271]
we are not getting  the message history from previous days ,and it's automatically cleared or not showing previous messages .
can you please let me know   how do i get all message history ? what is the process ?

**Comment by NagarajuMetavoxx** [comment]
We're not able to get the chat history..

**Comment by Echolon** [comment]
Double: Option request: Delete full history per contact at once #180

**Comment by Echolon** [comment]
@NagarajuMetavoxx what server are you using? Do you have Message Archiving activated? Can test this with the current version please?

**Comment by tmolitor-stud-tu** [comment]
I'll close this one, feel free to reopen it, if you still have that issue.

**Comment by Echolon** [comment]
*issues within the next update
