### ISSUE TITLE
Encryption not supported

### ISSUE THREAD

**Issue by tigexplorer** [anurodhp/Monal#272]
I don't use iOS or MacOS for myself but was trying to install Monal on a iPhone and a iPad of friends of mine.

But get always this messages if trying to set encryption for the contact.
The contact uses several OMEMO Devices, Conversations, Gajim and Dino!
Monal version, installed from App-Store on Juli/Aug 19 seems to be: 3.8 (377)

Sorry, I've first posted this issue here,
https://github.com/anurodhp/Monal/issues/240#issuecomment-519633300
but I think, it my have its  own.

![Encryption_not_supportetd](https://user-images.githubusercontent.com/43775552/62729356-1247ee80-ba1e-11e9-97dc-eea36d139516.png)

**Comment by anurodhp** [comment]
should be fixed in latest beta
