### ISSUE TITLE
wrong colors for chat bubbles and missing usernames in muc chat

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#274]
This has been happening for a long time, not related to latest release. Not sure if this happens 100% of times when visiting such a muc room. Will add findings when I find more time to debug.

![wrong colors, missing usernames](https://user-images.githubusercontent.com/5708172/62827048-ac976600-bbc7-11e9-99cb-68f1ae9224b9.JPG)

**Comment by foss-** [comment]
closing as this seems to be resolved in iOS 3.8.2 update. may re-open if the problem turns out to still not be solved permanentely.

**Comment by anurodhp** [comment]
fixed.
