### ISSUE TITLE
Messages do not arrive when device is turned off

### ISSUE THREAD

**Issue by COM8** [anurodhp/Monal#275]
## General
* **Device:** IPhone 7
* **Version Monal:** 3.8.1 (390)
* **version IOS:** 12.4

## Description
When I turn off my IPhone over night and somebody sends me a message while it's of for ~5 hours the message doesn't arrive in the morning when I turn it back on again.

## Reproduction
1. Turn off your IPhone over night
2. Somebody sends you a message after your phone is of for more than ~5 hours
3. Turn on your device in the morning ~ 8-9 hours after you turned it of
4. No new message arrived

**Comment by anurodhp** [comment]
It’s tough when the phone is turned off pushes will obviously not arrive and monal is not  started automatically anymore.  Unless you open the App it’s not going to check messages

**Comment by COM8** [comment]
Could this than be a server issue since I was only able to successfully reproduce it when my phone has been turned off for about 5 hours?

**Comment by anurodhp** [comment]
could you check 4.1 on TestFlight beta and see if thats still an issue? I think apple will hold pushes for a few hours before they are dropped but it should arrive with a notification of a new message at least.

**Comment by COM8** [comment]
I will try it and report back.

**Comment by COM8** [comment]
Looks like it's working again.
Did some extensive testing.
Thanks!

I will open the issue again, as soon I can reproduce it again.
