### ISSUE TITLE
Monal Key Transfer Between Users Not Working

### ISSUE THREAD

**Issue by mayjethva** [anurodhp/Monal#277]
Hi,

I am using the newest Monal on iOS (Version 3.8.2).  When adding a contact the contact exchange goes through, but no keys are transferred between the users.  Even when sending a message, nothing is sent.  This is not allowing me to have encrypted conversations.

In previous versions keys were being transferred between users.  

What could be the issue? 

Thanks.

**Comment by anurodhp** [comment]
Should be fixed in the latest beta.
