### ISSUE TITLE
Monal not creating OMEMO keys

### ISSUE THREAD

**Issue by gjabell** [anurodhp/Monal#278]
Hey anurodhp,

I am trying to get some family members set up with XMPP. They all use iOS, so I wanted to try out Monal as an alternative to less private messaging apps. Unfortunately, we're having some issues getting OMEMO to work. It appears that Monal isn't generating the encryption keys after logging into the server, nor is it receiving / recognizing keys from other devices (I'm running Conversations.im and Profanity).

This is the same issue as in #247, but it still seems to be an issue on v3.8.2 on iOS and v2.4 on MacOS. I am running my own Prosody server (v0.11.2) supporting XEPs 0163, 0191, 0198, 0237, 0280, 0313, 0352, and 0363. Worth noting that ChatSecure does properly generate and push the OMEMO keys, so it doesn't seem to be a server issue.

Let me know if I can help with any debugging (if needed I can make you an account on my server to help with testing).

Thanks!

**Comment by anurodhp** [comment]
This should be fixed in the latest iOS meta
