### ISSUE TITLE
List of online users always incomplete

### ISSUE THREAD

**Issue by Midar** [anurodhp/Monal#281]
I don't know why that is, but I noticed that since a few releases (or maybe even longer? I only noticed then) the lit of online users is incomplete: It always only shows 2 or 3 online users, while when connecting with another client, I see that around 30 are actually online. This also happens when the user is even messaging me. This still happens with both the latest release and the latest beta.

**Comment by anurodhp** [comment]
i think this may be an XMPP thing. I have been trying to figure out a way to get that list more accurate -- i may remove it because of how inaccurate it is

**Comment by Midar** [comment]
Do you support roster versioning? If so it might be a bug that Monal‘s state and the servers state get out of sync.

**Comment by anurodhp** [comment]
This should be fixed in the latest beta.
