### ISSUE TITLE
Sent images not embedded in chat

### ISSUE THREAD

**Issue by Stumpi73** [anurodhp/Monal#282]
Sent images are always shown as link and not embedded. Received images are embedded as expected.

**Comment by anurodhp** [comment]
What client is on the other end?

**Comment by Stumpi73** [comment]
On the other end is an android conversations. If i use ChatSecure on iOS it works, but with monal i had this problem.

**Comment by Echolon** [comment]
Would be good for 4.3, but I'd say next year :)

**Comment by Echolon** [comment]
Also double: https://github.com/anurodhp/Monal/issues/256

\close
