### ISSUE TITLE
Monal crashes as soon as I save my account

### ISSUE THREAD

**Issue by spiralsyzygy** [anurodhp/Monal#286]
I go to preferences, accounts, add XMPP account. I add my jabberID and password. I click save.
Monal closes. 

I'm at a loss.

**Comment by anurodhp** [comment]
Mac or iOS? What version?

**Comment by spiralsyzygy** [comment]
I'm using the Beta I downloaded from the site on OSX Mojave 10.14.6

**Comment by anurodhp** [comment]
Thanks. Just fixed the issue and will have a new beta up in a few min.

**Comment by spiralsyzygy** [comment]
Fantastic! Thank you for the fast response!
