### ISSUE TITLE
[iOS beta, #433] No message delivery when Monal is in background

### ISSUE THREAD

**Issue by schwindp** [anurodhp/Monal#287]
iOS 13.1b4

On Monal iOS beta 433, incoming messages don't seem to get delivered when Monal is in background.

How to test: Get a message sent from someone else when Monal isn't the active app. Log into your xmpp account with a different client. See unread messages there.

After opening Monal, messages arrive - already read (MAM does its job).

**Comment by anurodhp** [comment]
Correct the current AppStore build does work on 13.1 final.

**Comment by anurodhp** [comment]
I encountered this problem as well on iOS 13.1 beta 4. When the iOS 13.1 final release came out i didn't have this problem anymore.  Sorry, I should have been more clear, the current test flight beta beta and the app store beta are the same code so it doesnt matter which one you use.

**Comment by schwindp** [comment]
Sorry to re-comment, this problem still occurs with iOS 13.1.2.

My server is running prosody-trunk build 1118 as of 2019-Jul-12 03:09
