### ISSUE TITLE
Push no longer working since 4.0

### ISSUE THREAD

**Issue by Midar** [anurodhp/Monal#289]
Push worked fine for me before 4.0, but after 4.0, I cannot just get it working anymore. I tried both, reregisering in Monal as well as deleting the cloud_notify directory in Prosody. I also tried ChatSecure, and push with that still works - but has the usual problems that ChatSecure has with push (i.e. notifying multiple times: For Apple Push, then for the newly received message and then for MAM).

**Comment by janteau** [comment]
Also experiencing issues here with iOS 13 and the latest Monal. If the app is backgrounded the notifications seem to be very unreliable. If the the app is killed, no notification appears (not even generic New Message notification).

**Comment by Chobbes** [comment]
I have sadly had similar problems with push notifications. I think this is a pretty high priority issue. Fixing it will make monal infinitely better :).

Willing to help test it, if that's helpful.

**Comment by anurodhp** [comment]
the change is ios13. I have been trying to figure out what is going out since the betas.  I thought it was resolved when iOS 13 GM came out but it seems that it is working only sometimes now.

**Comment by Chobbes** [comment]
Notifications have always been somewhat unreliable with monal for me (maybe it's an omemo issue or something isn't set up right on my server or...??? I'm never really sure what's going on, so it's hard to report). But yeah, iOS 13 seems to have done unspeakable things to monal :(.

**Comment by anurodhp** [comment]
addressed at least so people see there's a new message in 4.1 (check the beta now or the app store next week). Working to restore the previews.
#295
