### ISSUE TITLE
http upload, SSL error?

### ISSUE THREAD

**Issue by andersruneson** [anurodhp/Monal#29]
I just tested uploading a file with http upload and I get 
"There was an error uploading the file to the server" and then some explaining text "An SSL error has occured and a secure connection to the server cannot be made.".

I don't get it, there's a valid cert on the server, and not self-signed.

(No problems with Gajim or Conversations)

**Comment by andersruneson** [comment]
Common Name (CN)	COMODO RSA Organization Validation Secure Server CA
Organization (O)	COMODO CA Limited
Organizational Unit (OU)	<Not Part Of Certificate>

Issued On	Friday, February 26, 2016 at 1:00:00 AM
Expires On	Friday, March 16, 2018 at 12:59:59 AM

**Comment by anurodhp** [comment]
iOS is incredibly strict about HTTP connections. The errors seen are OS error messages. HTTP will never be supported as Apple doesn't really allow non HTTPS connections anymore without compromising the security of the app for everyone. In the case of HTTPS, it is strict about checking the certificate.  If the OS suspects the connection is insecure (e.g TLS <1.2 ), it will not allow it.  There is a checklist of criteria on this post here:
http://stackoverflow.com/questions/31231696/ios-9-ats-ssl-error-with-supporting-server
 
If you visit the same URL in safari does it still work or do you see an error message?

**Comment by anurodhp** [comment]
Looks like jabber.at supports creating accounts, I'll make one there so I can see exactly what is causing the problem. The actual jabber.at site has an A+ on[ SSL labs test ](https://www.ssllabs.com/ssltest/analyze.html?d=jabber.at&s=2001%3A629%3A3200%3A95%3A0%3A0%3A1%3A26). It's entirely possible the upload URL is to another domain. Do you have an example of an image uploaded to jabber.at from another client? Does that work in iOS Safari without warning?

**Comment by andersruneson** [comment]
jabber.at actually works, it's my own domain not working.
This happens **at** upload, I guess nothing gets uploaded even. But if I test an url to a file which was uploaded with another client that can be opened in Safari.

**Comment by anurodhp** [comment]
could you test your domain at https://www.ssllabs.com/ssltest/ and see if everything in the required list here: http://stackoverflow.com/questions/31231696/ios-9-ats-ssl-error-with-supporting-server is set.

**Comment by andersruneson** [comment]
It's a bit more complicated, when outside of our network (such as ssllabs)
SSL are handled by our firewall/web proxy and that has issues. But I'm
running Monal on our internal network where SSL are handled directly by the
im server.

**Comment by andersruneson** [comment]
Hmm, I'm guessing Safari is no as strict and I'm probably wrong about being on the internal network. 
This is probably cased by our firewall/web proxy not handling TLS 1.2.
Closing this. (unless you can convince Apple to be a little less strict)

**Comment by Mrfuyu** [comment]
@anurodhp You wrote in your blog that you was testing XEP-0363 with Prosody as Server. Did you use the mod_http_upload for prosody or an external component like the HttpUploadComponent? If you used the mod then is it handling the SSL request by itself or did you configure e.g. Apache to handle this?
I use simply the mod_http_upload from Prosody with a certificate from Let's Encrypt but i also get this error. Viewing a sent picture in Safari is possible.
