### ISSUE TITLE
Monal on macOS leaves my account permanently online

### ISSUE THREAD

**Issue by TheMysteriousX** [anurodhp/Monal#291]
monal OS X (v2.4.1 (149)) is causing my account to be permanently online. I'm not able to reproduce this with monal iOS or Pidgin/Adium.

After connecting to the Jabber daemon (we use openfire) with the OS X client, I can quit monal, power off the machine, unplug the network, and I'll still be visible to other users as online and available.

The status doesn't appear to time out - In order to clear this state, I have to restart the Jabber daemon.

This could be an openfire issue, but as I'm not able to reproduce it with other clients, or even a different build of monal, I thought it sensible to start here. I have full control over the client and server, so please let me know if you'd like me to collect any information.

**Comment by Echolon** [comment]
@TheMysteriousX Can you confirm this still with the current version on your desktop?

**Comment by Echolon** [comment]
@TheMysteriousX ?

**Comment by TheMysteriousX** [comment]
I don't have access to the machine that had the problem at the moment. I think it should be resolved though, as the mac build has been essentially replaced with the iOS build.

**Comment by tmolitor-stud-tu** [comment]
I will close this, then.
