### ISSUE TITLE
Analyzed message loss on Monal 4.0 and iOS 13

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#295]
I analyzed a recent Monal 4.0 message loss on iOS 13:

A few minutes after the outgoing push, the device woke up and connected, could not resume an old smacks session and bound its resource.
Then it queried MAM and got the one message back, that was waiting.
It acked this message via smacks and closed the connection in the same second (server view).

But Monal never displayed the message/notification to the user.
And because the MAM stanza was acked, the server did not try to send a second push to empty the smacks queue.

Maybe you could only ack a message stanza if it was completely processed and notifications etc. shown to the user.
This will prevent this type of message loss because a closed connection with unacked stanzas will trigger a new push to wake up the client (Monal) an let it consume the smacks queue.

**Comment by anurodhp** [comment]
What is happening is the  push notification is arriving and monal starts up, downloads the message, marks it as delivered but is then cant present a notification.  I am rolling out an early version of the extension based approach for now (its in TestFlight ) .  And will add message previews in the update after that.
