### ISSUE TITLE
Monal OSX - contact list not correct/in sync

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#297]
Hi!

Contact list in Monal OSX is either not correct or accounts are listed multiple times. See screenshot as example: 

[https://silverhaze.org/s/oEjkRBt3NEqTt3m](https://silverhaze.org/s/oEjkRBt3NEqTt3m)

Video: https://silverhaze.org/s/yHnyJEppKjSFqmP

As you can see, Jitsis contact list is way different than what Monal is showing. Sometimes it helps switching between Contacts tab and Active Chat tab in Monal, but in most times it doesn't. 

Screenshot is from latest Monal OSX beta version 2.4.1(149), downloaded from website just some minutes ago.

**Comment by anurodhp** [comment]
I think this has been fixed in iOS, will update osx with the same code

**Comment by Echolon** [comment]
@ingoj 

Have you crosscheck with the latest version?

**Comment by anurodhp** [comment]
There is no longer a contacts list like this in the new UI

**Comment by licaon-kter** [comment]
But where are my contacts then?
