### ISSUE TITLE
Can't login with build 4.2(446)

### ISSUE THREAD

**Issue by ioscanner** [anurodhp/Monal#299]
I can't get the new build to login to any accounts.  I tried many times.  Went back to a different client to confirm and I can login from a different client.  I was logged in with 4.2(444), but it crashed when trying to access the chats.

**Comment by anurodhp** [comment]
Thanks,  I’ll check it. I’ve been moving code around so it a possible it broke something.  You can downgrade by going into TestFlight app and picking and old version

**Comment by ioscanner** [comment]
The older version has the crash issue.

**Comment by ioscanner** [comment]
And the with 4.1 push notifications don’t work.  So seems all of the previous versions are broken in one way or another.  Lol

I noticed the new version 4.2 seems to auto fill based on the domain instead of the DNS srv.  Which it worked in 4.1.  So that could be the issue with 4.2 not logging in.

**Comment by anurodhp** [comment]
Is this still and issue with the latest beta?

**Comment by ioscanner** [comment]
So far it seems to have fixed it.  I will test and see if any new bugs are present.

**Comment by ioscanner** [comment]
Seems omemo is still broken in the latest build.  You can’t see the keys.

**Comment by anurodhp** [comment]
check todays build

**Comment by anurodhp** [comment]
closing because this should be working now. reopen if necessary.
