### ISSUE TITLE
XEP-0363 with openfire,HttpUploadComponent and jitsi

### ISSUE THREAD

**Issue by ageekhere** [anurodhp/Monal#30]
Hey, has anyone got file http upload working for openfire?
I have setup HttpUploadComponent with openfire and have it connected as a Component Sessions. So in monal when I click to send image to another monal account it detects XEP-0363 support and tries to send the photo, however it times out with a timeout error.

Trying to workout what program has the issue (openfire, HttpUploadComponent ,monal).

Also has anyone got http upload working for jitsi? when I try pc to monal I get a can't send file error, not sure if jitsi supports XEP-0363 as I can't find any info on it.

**Comment by anurodhp** [comment]
Are you using https with a valid cert? If not it won't work. Self signed cents won't work and http will never work. Apple does not allow insecure connections. 

If you need a free valid https cert get one from let's encrypt.

**Comment by ageekhere** [comment]
I am using https but i did not create a cert yet, will try it now.

**Comment by ageekhere** [comment]
still having issues with this, when I try and send a file from monal im to another monal account i get cannot connect to server, i see the send request in HttpUploadComponent but no error.

Has anyone got XEP-0363 working?

**Comment by aroquen** [comment]
It works fine with prosody and mod_http_upload

**Comment by weiss** [comment]
*Might* be a duplicate of #38.

**Comment by anurodhp** [comment]
fixed an issue with content type passing that may address this
