### ISSUE TITLE
[iPad] Renew preview pictures in the App Store

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#300]
Hi Anu,

I just put it here for you as an **low-prio** reminder:

You should create new and nice screenshots for the preview of Monal if you access the page from an iPad. The current pictures seem to be outdated.

Looking forward to 4.2! :rocket: 

Kind regards

**Comment by anurodhp** [comment]
all the pictures on every platform will have to be refreshed now the UI is completely different
