### ISSUE TITLE
Register Account crashes after Captcha is loaded

### ISSUE THREAD

**Issue by htgoebel** [anurodhp/Monal#301]
When trying to register an account (in the "Quick Setup"/"Welcome Screen" -> Register Account), Monal crashes as soon as the captcha is loaded.

Version 4.3.1

**Comment by anurodhp** [comment]
Is this 4.2 beta on TestFlight?

**Comment by htgoebel** [comment]
Soory, i mixed up the version.
I'd the latest version from Apple Store: 4.1 (442)
