### ISSUE TITLE
Catalyst: colors hard to read

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#302]
The colors in chat windows are hard to read over here. Font color is white on light-grey backgroup: 
<img width="457" alt="Bildschirmfoto 2019-12-20 um 20 49 23" src="https://user-images.githubusercontent.com/18173881/71309258-28bb7900-2406-11ea-8bcf-3f64e915a6a5.png">

**Comment by anurodhp** [comment]
fixed in latest beta
