### ISSUE TITLE
Catalyst: Alignment of chat message

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#303]
While it is ok for iOS version to have a right-aligned text flow in chats, it is more convenient on macOS to have a left-aligned text flow in chats: 
<img width="457" alt="Bildschirmfoto 2019-12-20 um 20 49 23" src="https://user-images.githubusercontent.com/18173881/71309293-910a5a80-2406-11ea-8193-f287bf7f4de4.png">

**Comment by Echolon** [comment]
Rel. https://github.com/anurodhp/Monal/issues/214

**Comment by anurodhp** [comment]
fixed in latest beta
