### ISSUE TITLE
Catalyst: Info marker (i) on new chat messages received: 

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#305]
It's a little bit confusing, but on newly received chat messages there is an info marker on the left: 
<img width="270" alt="Bildschirmfoto 2019-12-21 um 15 31 45" src="https://user-images.githubusercontent.com/18173881/71309353-31f91580-2407-11ea-8a2d-cd895c47ea6b.png">
When you click on the (i) it asks for resending the message, which is odd for a received message: 
<img width="316" alt="Bildschirmfoto 2019-12-21 um 15 31 53" src="https://user-images.githubusercontent.com/18173881/71309381-6ec50c80-2407-11ea-9877-f09fc90b0358.png">

**Comment by anurodhp** [comment]
this should be fixed on the latest
