### ISSUE TITLE
Catalyst: Add/Edit MUCs - "Account to use" not a selection list

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#306]
When adding a new Group Chat/MUC you need to enter the JID all by yourself instead of choosing it from a selection menu. This is true for clicking on the + link to add a new MUC as well as when clicking on the (i) link to edit a Group Chat setting: the "Account to use" is then empty.

**Comment by anurodhp** [comment]
verified. will fix

**Comment by foss-** [comment]
similar with more detailed feature destription: https://github.com/anurodhp/Monal/issues/342

**Comment by anurodhp** [comment]
fixed

**Comment by foss-** [comment]
Version 4.3 (533) verified
