### ISSUE TITLE
Catalyst: Contacts vs Chats vs. Group 

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#309]
When adding a new Group Chat under "Group" tab my assumption would be that I see all my favorite or active MUCs under Chats, but there are also MUCs listed under Contacts while not all MUCs also appear on Chats (like e.g. operators@muc.xmpp.org): 
<img width="257" alt="Bildschirmfoto 2019-12-21 um 15 51 19" src="https://user-images.githubusercontent.com/18173881/71309731-c9f8fe00-240b-11ea-8066-36928730d45a.png">
<img width="286" alt="Bildschirmfoto 2019-12-21 um 15 52 29" src="https://user-images.githubusercontent.com/18173881/71309732-cebdb200-240b-11ea-9d21-e570202cc461.png">
I think this is something inherited from the iOS client, but on macOS it would be better to just have "Contacts" with your roster list and the 1:1 chats to the right part of the window and "Group Chats" with the list of MUC favorites and their chat content to the right.

**Comment by anurodhp** [comment]
the new UI only has a chats screen. contacts come up when you compose a new message.  Groups come up when you want to join a group (bookmark ) or add a new one.  It think that should clarify things
