### ISSUE TITLE
Catalyst: own messages not appear in Monal when sent in another client

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#311]
Monal on macOS seems to dismiss own messages sent from another client like dino.im on Linux. Whileas Jitsi on macOS received that message, Monal doesn't display it: 
<img width="985" alt="Bildschirmfoto 2019-12-21 um 16 17 13" src="https://user-images.githubusercontent.com/18173881/71309896-99b25f00-240d-11ea-84fb-554b02990ab9.png">

**Comment by anurodhp** [comment]
This should work correctly, was this in a group chat? could you check the latest beta. 
http://monal.im/Monal-OSX/Monal-catalyst.zip
