### ISSUE TITLE
Catalyst: List of participants missing in MUCs

### ISSUE THREAD

**Issue by ingoj** [anurodhp/Monal#312]
The list of participants in a MUC seems to be missing in Monal-catalyst. Or I haven't found the option to display that list yet... :)

**Comment by anurodhp** [comment]
Muc details and it’s called resources. Next release will call it participants

**Comment by ingoj** [comment]
Ah, right... that's well hidden... I saw that Resources entry, but thought that it was something similar like the resources thing for the client itself... my fault then... ;)
But maybe make this list easier accessible with a top right button to show the list of participants. I could provide a screenshot of another XMPP client that is using something like that...

**Comment by anurodhp** [comment]
check the latest build http://monal.im/Monal-OSX/Monal-catalyst.zip
