### ISSUE TITLE
Not able to use http upload for files using wiuwiu.de

### ISSUE THREAD

**Issue by chippisc** [anurodhp/Monal#314]
We are experiencing issues with file uploads. Both accounts are on wiuwiu.de.
One client is Conversations, the other one Monal.
Wiuwiu has XEP-0363: HTTP File Upload activated for files up to 95MiB.
The upload using this server also works perfectly when using Conversations as client. However there was a similar problem using ChatSecure.
But when using Monal directly after clicking on the "attach" button we receive an error message:
![http-upload-warning](https://user-images.githubusercontent.com/56129198/71411570-2ba6ab80-264a-11ea-97a6-9b88fd8d431e.PNG)
So there is not even a chance to select a file.
Files sent by the client on Conversations are received and displayed correctly on Monal.

**Comment by foss-** [comment]
Fixed in the beta releases which you can find here: https://monal.im/

**Comment by chippisc** [comment]
> Fixed in the beta releases which you can find here: https://monal.im/

In the beta following your link we get a different error message:
![new-error-http-upload](https://user-images.githubusercontent.com/56129198/71477967-68f76e80-27ed-11ea-9b0a-e45f38f4a8fb.PNG)
Opposed to the error I described earlier, the new message is displayed after choosing a file. The files we tried to send have only 1-2 mb filesize so filesize should not be a problem.

**Comment by anurodhp** [comment]
hmm the second error is a new one, ill have to see what it doesnt like about your config (and also check the XEP to see if i missed something in my implementation)

**Comment by Echolon** [comment]
Hmm, this is the second time wiuwiu.de pops up here:

**Delay in receiving messages** #251

@mightyBroccoli
@sebastiansterk

Do you have any ideas? :/

**Comment by sebastiansterk** [comment]
Can you provide application log files of monal while trying to upload / download something using http upload?

**Comment by chippisc** [comment]
We just now reactivated the wiuwiu account and with the newest stable release (4.5) everything works. However because the wiuwiu-account has not been used together with monal for months we cannot provide any log files or even a date when it started working correctly.
Thank you!

**Comment by Echolon** [comment]
Thanks to all of you for the quick reply!
