### ISSUE TITLE
[Website] no HTTPS for monal.im

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#315]
Hello,

I have HTTPS Everywhere active, however HTTPS is not forced/possible for just monal.im

<img src="https://user-images.githubusercontent.com/29168011/71486670-cbfdfb00-2817-11ea-8808-27663441921d.png" width="400">

Ref: https://www.eff.org/https-everywhere

Kind regards

**Comment by anurodhp** [comment]
odd its using lets encrypt certs https://monal.im

**Comment by anurodhp** [comment]
added force ssl should  be fixed
