### ISSUE TITLE
Notifications stopp working after reboot

### ISSUE THREAD

**Issue by sirdrakeistda** [anurodhp/Monal#317]
Notifications stopp working after reboot. It makes no difference if Monal is open in the background or not.

**Comment by licaon-kter** [comment]
This is 4.2? All the notifications settings are checked?

**Comment by sirdrakeistda** [comment]
I checked them and I don't know why they worked before reboot, but not after reboot.

**Comment by anurodhp** [comment]
the notification mechanism itself runs entirely outside of monal the app isn't even running. It is controlled by iOS.  The only way this could have happened is if you're unlucky enough to have your push token change at the reboot.  I have not been able to reproduce this.
