### ISSUE TITLE
Can't login success

### ISSUE THREAD

**Issue by WeightZhang** [anurodhp/Monal#32]
I think i don't know how to add an account in the client(iOS/OSX).

Openfire used to be service at local, the monal client can't login . 
But Adium(another client for osx)can.

What should i do?

**Comment by anurodhp** [comment]
The jid is in the format username@host
The host might not match your server so you may have to enter the server address manually below. Additionally if your ask cert is self signed, turn that in.

**Comment by brocksampson** [comment]
I noticed that if I put "username@server" as the Jabber ID and then filled in the Server field, it would not connect to a Prosody server with the error (in Prosody) "c2s stream for xxx.xxx.xxx closed: This server does not serve"

A successful connection lists the account/server name after "serve."

If I just put "username@server" and then leave the Server field blank, Monal connects successfully.

**Comment by Echolon** [comment]
@WeightZhang is this still an issue?

Have you tried the current version?

**Comment by Echolon** [comment]
I will close this, please test with the current release.
