### ISSUE TITLE
How to setup background

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#320]
4.2, 6S, 12.4.4

I got stuck there, actually stuck...there's only the upload (selector) button and nothing else, I can only scroll between different pics and zoom, so on a 6S I could only kill the app and restart it to escape.

Not sure even the swipe up (or was it down?) gesture that help you exit pictures viewing helped here.

**Comment by anurodhp** [comment]
swipe down should work but i have added  close button that shows up now in the next build

**Comment by licaon-kter** [comment]
"Close" means "apply background" or "cancel action" ?

**Comment by anurodhp** [comment]
Hmm I have it apply any background you are on. I’ll make it more clear
