### ISSUE TITLE
Show used account which is sending the message in compose box

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#321]
Monal beta 159
macOS 10.14.6

**Currently**

Compose box is empty before user starts to compose a message.

**Expected**

compose box should show the account the message will be sent from if more than a single account exists.

Otherwise it is impossible to tell which account the contact is connected with or even more confusing if the same contact exists in more than a single account.

**Comment by anurodhp** [comment]
added to iOS coming on Mac

**Comment by anurodhp** [comment]
in catalyst

**Comment by foss-** [comment]
Version 4.3 (525) verified
