### ISSUE TITLE
macOS: Group Bookmarks - prevent multiple entires for the same room

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#325]
**Currently**

Just noticed, that the Group Bookmarks view listed the same room _many_ times.

**Expected**

Monal should check if a bookmark for a room exists bevore adding a duplicate entry.

**Comment by anurodhp** [comment]
Verified this is an issue. Goes along with the need to provide feedback on some of the MUC screens in general

**Comment by foss-** [comment]
macOS 10.15.3, Monal Version 4.3 (524)
no longer reproducible, closing
