### ISSUE TITLE
macOS Catalyst: shift enter should go to new line / create linebreak

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#326]
[x] add keyboard shortcut: enter = send message
[ ] add keyboard shortcut: shift + enter = go to new line

**Comment by anurodhp** [comment]
worked in mac not in catalyst. enter sends right now.

**Comment by FriedrichAltheide** [comment]
added "shift + enter" in https://github.com/tmolitor-stud-tu/Monal/commit/da24a0550e913283a803476c4bc98da5ebb2fdfa

We can close this issue as soon as we added it to a PR from the alpha

**Comment by tmolitor-stud-tu** [comment]
Implemented in Monal 4.8

**Comment by foss-** [comment]
Verified in latest alpha. Thanks for tackling this.
