### ISSUE TITLE
macOS Catalyst: add OMEMO support

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#327]
see title

Currently macOS Catalyst Monal 4.2.1 (478) does not support OMEMO.

**Comment by anurodhp** [comment]
in the latest beta. won't work with 16 byte iv code in other clients as i explained in the blog but will work with monal iOS :)

**Comment by foss-** [comment]
Version 4.2.2 (493) can not decrypt. When closing lock in contact settings getting error:

Encryption not Supported
This contact does not appear to have any devices that support encryption.

When looking at the encryption keys list it is empty.

That would suggest fetching keys is not working as expected.

Let's keep this open until that works as expected.

**Comment by Echolon** [comment]
Isnt this #285 ?

**Comment by foss-** [comment]
you are 100% correct.
