### ISSUE TITLE
Strange issue with seemingly lost messages

### ISSUE THREAD

**Issue by sagamusix** [anurodhp/Monal#33]
I have a strange issue which I hope you can help me solve.

First off, some details: I am running my own XMPP server (Prosody on Debian), and I am talking to a friend on the same server. I personally use Miranda NG on my Windows machine, and they use Monal on their iPhone (connected via Wifi, _not_ 3G/4G). For the last few years I was always able to talk to my XMPP contacts without problems, and this contact is the first one I am having issues with.

So here is our problem: While chatting, it seems that some of my messages do not arrive at their end. However, the weird thing is that while the message does not show up on their screen, I still get a receipt notification from them.
I have talked to the Prosody developers, showed them some logs and they confirmed to me that it must be a client issue. It is strange because my friend also tried two other clients which exposed a similar problem, but if the server sees my message, and I see the other client's receipt notification, then it
really seems like something is going wrong on my friend's end?

I know that this might not be enough information for you to help me solving this issue, so I hope that you can give me any information if there's a debug mode in Monal or anything else my friend could do to help debugging the problem?
I already talked to the AstraChat developers (which is another client my friend tried on their phone) - and sadly they couldn't provide a debug mode for the iOS version of their client. The problem, however, was pretty much identical across all clients.

**Comment by andersruneson** [comment]
How often does the message loss occur?

**Comment by sagamusix** [comment]
In a regular conversation, it may happen every few minutes.

**Comment by andersruneson** [comment]
There's a raw XML terminal I gajim, fire that up and see if you can catch
the message.

**Comment by sagamusix** [comment]
Yes, it also exists in Miranda NG, which I'm using. I checked both the debug log of Prosody and Miranda, and they all seemed to confirm that the messages do arrive on the iPhone, but somehow won't get displayed. The really confusing part is that it happened with several clients on the iPhone, and e.g. AstraChat even sent a delivery notification back to Miranda NG (when I checked the debug log, I think Monal didn't send those). So I'm wondering if there's a way to check the raw XML output or similar things directly in Monal?

**Comment by anurodhp** [comment]
If you use the OS X Monal app from Monal.im it will print everything to console. The app is identical to iOS. 

--
Anurodh Pokharel

**Comment by sagamusix** [comment]
Sadly we don't have an OSX devices available for testing - Only Windows and iOS.

**Comment by tmolitor-stud-tu** [comment]
@sagamusix you could activate mod_rawdebug if you are using your own prosody server. This way all raw stanzas to and from your device will be logged by prosody.

You can get this module here: https://modules.prosody.im/mod_rawdebug.html

**Comment by sagamusix** [comment]
Thanks for the hint, I'll try to debug some more once I get the opportunity.

**Comment by anurodhp** [comment]
Closing this with the deployment of push. if it is still an issue please reopen.
