### ISSUE TITLE
iOS + Catalyst: mute notifications for rooms + chats which are muted

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#332]
**Currently**

Even rooms which are muted receive notifications.

**Expected**

Muted rooms should not receive notifications.

**Comment by tmolitor-stud-tu** [comment]
this can only be done once the notifications are reworked, stay tuned, it's on my list

**Comment by tmolitor-stud-tu** [comment]
Should be fixed in Monal 4.8
