### ISSUE TITLE
MUC - chat history is not sync

### ISSUE THREAD

**Issue by NagarajuMetavoxx** [anurodhp/Monal#335]
I'm the participant of one particular group. and I've login the same user in two devices(mobile and laptop). When I've send messages to group from mobile,  the messages are sync with laptop. But when I send messages to group from laptop , the messages are not synchronised with mobile.

**Comment by Echolon** [comment]
Hi,

unfortunately, I think this is a double ref. #223, #309 and #310

**Comment by Echolon** [comment]
also #180
