### ISSUE TITLE
No OMEMO with Gajim,Profanity,converse.js

### ISSUE THREAD

**Issue by nolash** [anurodhp/Monal#337]
I am trying to assist someone with an iPhone 8+ iOS 13.3 to set up Monal 4.2.1 (479) for chat with me. I am using Gajim, Profanity and have also tried converse.js. OMEMO fingerprint seems not to be published.

The other party has a "trusted" fingerprint in settings->accounts->keys and can see "and has trusted" my fingerprint in our chat session. Polling fingerprints for the other party on my end turns up nothing.

Are there additional steps that have to be made to get this working?

**Comment by licaon-kter** [comment]
Added as contact on both sides?

**Comment by Echolon** [comment]
Hi,

I think its a double regarding.

#225 and #240 
Please comment in there

**Comment by nolash** [comment]
@Echolon both of those relate to MUC. This is not about MUC.

**Comment by nolash** [comment]
Ok I see, so it must be manually turned on by clicking the "padlock." It now works.

Is there a manual entry I have missed somewhere that should have told me this? If so, I am sorry.

**Comment by Echolon** [comment]
No, is fine, see already this request #234

Still want to reopen?

**Comment by nolash** [comment]
Thanks. No - no need to repoen.

Let me risk an off-topic though; how does the other party accept my request for presence information? I've sent plenty, they don't seem to show up anywhere in the ui.
