### ISSUE TITLE
macOS Catalyst make contact info dialog larger to avoid scrolling

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#338]
**Currently**

Dialog is cut of and there is no indicator that the dialog is scrollable.

**Expected**

To avoid confusion, increase dialog size so no scrolling is needed.
Add `⌘I` keyboard shortcut to open contact dialog.

![user info dialog](https://user-images.githubusercontent.com/5708172/71993712-da94db00-3237-11ea-9ec2-4281354b5604.png)

**Comment by FriedrichAltheide** [comment]
Added "cmd + i" shortcut (https://github.com/tmolitor-stud-tu/Monal/commit/98c6b177fdb403753c7d37e17cf5feb7102f00c2)

**Comment by foss-** [comment]
Thanks for adding `⌘I` to open contact info.
@FriedrichAltheide can you also add support for `esc`to close the contact info?
