### ISSUE TITLE
[QUESTION] Pictures are not displayed in-line

### ISSUE THREAD

**Issue by therob84** [anurodhp/Monal#34]
I am using [Conversations ](www.conversations.im)(1.11.5) and chatting with two different partners, both using current version of Monal, all via jabber.de.
- If I receive an Image, Conversations displays the received image without problems as **in-line**, doesn't matter if it comes from partner1 oder partner2
- If I send an image to partner**1**, the image is displayed **in-line** in Monal, as it should be.
- If I send an image to partner**2**, the image is just displayed **as a link** to the jabber.de server to click it in Monal.

What is going on here? Obviously it CAN work, but why does'nt make it in both cases, using the nearly same conditions? Is there any hidden preference?

**Comment by anurodhp** [comment]
Monal doesn't display images online. This is at the moment an intentional design decision. I'll add an option to have inline display in the future but it will be opt in only. Inline display exposes your IP address (and therefore your location)  to the sender and has serious privacy issues.

**Comment by therob84** [comment]
Thanks for fast answer.
OK, after asking partner1 again, I have indeed to correct me: both have seen a link! Sorry.

But why is this connected with privacy issues?
Is clicking the link to display it in a browser less intruding than letting Monal download it and displaying it? Is this a Monal-issue or an iOS specific or even a general one (which would mean you claim that Conversations make a "serious privacy issue" with in-line display of images....which I would doubt!)
Is IP adress during XMPP conversations not anyway an anavoidable metadata (without TOR etc)?

In terms of privacy......I would say until Monal does not support OMEMO, it is a step to far to care about privacy with in-line images. Wouldn't you agree?

Thus, I strongly ask the feature of in-line displaying (opt-in or not) of images!

**Comment by anurodhp** [comment]
In a one on one conversation, both people are talking to a server and not to each other so neither knows the others ip. The way the online image is detected, it makes a http head call automatically for every link to check if it is an image. This head call connects to a server automatically . Basically, if I wanted to know where someone was I would send a url unique to them. They don't even have to click it, just receiving the message would let me look in my logs to see their ip and location. At least with a click the recipient is aware that something is happening.  If you trust the other party it's not a big deal, receiving a random message, it's a problem.

**Comment by therob84** [comment]
Already any progress for implementing the checkbox to display inline-images? And already future Monal-update at the horizon?

@inputmice: Would you comment on anurodhp's privacy concerns above with automatic inline-display of images? I guess you wouldn't have it implemented to [Conversations](www.conversations.im), if it is really that insecure in terms of privacy, am I right?

**Comment by silberzwiebel** [comment]
I'm trying to convince my buddies to use my private XMPP server and this is a major issue for iOS users. I'd love to see an opt-in option to see inline images!

**Comment by Mrfuyu** [comment]
Yes opt-in would be nice! Inline is a must for most users.

**Comment by anurodhp** [comment]
I have added a preference to enable this in the latest OS X beta (look on the left for a link)
https://monal.im/blog/monal-osx-has-inline-images/

After some testing, ill bring it to iOS.
