### ISSUE TITLE
macOS Catalyst Shift + Enter should create linebreak / go to new line

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#340]
see title. This was implemented for non-catalyst macOS version of monal. Catalyst variant still lacks that desired behavior.

**Currently**

shift + enter: does nothing (sends message as enter would do)

**Expected**

shift + enter: create linebreak / go to new line in composer area

**Comment by licaon-kter** [comment]
Duplicate of https://github.com/anurodhp/Monal/issues/326 ?

**Comment by foss-** [comment]
#326 was about using enter to send. that is solved.
#340 is about shift + enter to go to new line. that is unsolved.
