### ISSUE TITLE
macOS Catalyst: add option to remove contacts from contact list

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#341]
**Currently**

No option to remove a contact.

**Expected**

Right-click Remove + Mute option.
also cmd + backspace should remove the dialog. in that case add a dialog asking "Are you sure you want to remove this contact?" to avoid removing contacts by accident.

**Comment by ToEatFreshBabies** [comment]
Remove and block?  Or simply hide?

**Comment by foss-** [comment]
remove

**Comment by anurodhp** [comment]
swipe works too but there is now  a menu and a cmd+delete command
