### ISSUE TITLE
macOS Catalyst: "+" dialog to add new contact or Group Chat should have default account and dropdown if 2 or more accounts exist

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#342]
**Currently**

Account to which a new contact is added has to be entered manually.

**Expected**

Account should always be pre-filled and if 2 or more accounts exists, there should be a dropdown for the user to select the account to which the new contact is added.

![account selection missing](https://user-images.githubusercontent.com/5708172/72076457-d8915180-32f5-11ea-9463-ab63c49f78c8.png)

**Comment by foss-** [comment]
similar, but less detailed: https://github.com/anurodhp/Monal/issues/306

**Comment by anurodhp** [comment]
Like iOS  if you have only one account there is no account selection at all. I am working on adding a second screen here that should resolve this issue.

**Comment by anurodhp** [comment]
fixed in next release
