### ISSUE TITLE
macOS Catalyst + iOS: Lock icon in the corresponding chat bubble is missing

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#343]
**Currently**

when OMEMO is active and sending a link, the lock icon in the corresponding chat bubble is missing

**Expected**

As sent links are also OMEMO encrpyted, the chat bubble with the link should also display the lock icon.

![missing lock icon](https://user-images.githubusercontent.com/5708172/72078462-6d497e80-32f9-11ea-9498-1a283af9fd41.png)

**Comment by anurodhp** [comment]
this has been fixed

**Comment by foss-** [comment]
Posting a URL now has a lock on iOS. Can't test catalyst as omemo is not yet fully working there.

Minor: lock icon is on the bottom right, while for normal messages the lock icon is on the bottom left of the message bubble.
