### ISSUE TITLE
Sound played on incoming new message though "Play Sounds" is off

### ISSUE THREAD

**Issue by schwindp** [anurodhp/Monal#345]
iOS 13.3, Monat version 4.2.2 (504)

'nuff said, everything's inside the subject.

**Comment by Echolon** [comment]
rel. #6 #205 #238

**Comment by Echolon** [comment]
I have the opposite issue. Sound active, but no sound. But I think that is an issue with the phone :thinking:

**Comment by tmolitor-stud-tu** [comment]
Please check if this is still the case in the upcoming Monal 4.8 and reopen if necessary
