### ISSUE TITLE
MUC Group chat history not syncing

### ISSUE THREAD

**Issue by pasha4uu** [anurodhp/Monal#346]
Hello,
When adding a new MUC to the favorite list of MUCs and set it to autojoin, there is no sync to the iOS version of Monal so the Group Chat list there will be empty if not added manually. and when sending message A ( same user login web client & IOS app ) From Monal iOS App to B working well sync data and while reverse  send from web A to B working well but not iOS app A not syncing that message please look into this issue,

**Comment by Echolon** [comment]
Hi,

I think your problem is already known. Please see the related tag filter issue and coment there please.

https://github.com/anurodhp/Monal/labels/MUC

Therefor I will close this issue.

**Comment by Echolon** [comment]
#167 #203
