### ISSUE TITLE
Connection status often offline

### ISSUE THREAD

**Issue by ioscanner** [anurodhp/Monal#350]
I have noticed for a while that when I navigate away from Monal and come back it is logged out of jabber accounts.  Sometimes they connect one.  But most of the time it doesn't login to the accounts. I have to logoff all and then reconnect all to get it working each time.

I do get the push notifications when a new message comes in.  I am using Prosody as the server.

IOS 4.2.3(506)

**Comment by anurodhp** [comment]
I have made some fixes that should speed up the reconnection in 4.4

**Comment by unriccio** [comment]
I can confirm this still happens with the current stable version (4.6).

**Comment by tmolitor-stud-tu** [comment]
the new 4.7 beta has a completely reworked connection logic, does this still happen?

**Comment by Echolon** [comment]
I will close this as is does not happen to my understanding. 
However, there is still the problem that push messages not work correctly and Monal only loads new messages once the actual chat is opened.
