### ISSUE TITLE
Server: Prosody cloud_notify errors without push.monal.im

### ISSUE THREAD

**Issue by gjabell** [anurodhp/Monal#351]
I'm trying to debug deliverability issues between Conversations and Monal, and I am getting a number of messages of the following format in my Prosody logs:

```
cloud_notify   info    Got error of type 'cancel' (item-not-found) for identifier 'push.monal.im<UUID-REDACTED': error count for this identifier is now at 8
```

I'm guessing a client's cloud_notify session is going stale, but my server doesn't seem to recognize the new session, which might have to do with why some messages aren't delivered.

**Comment by Echolon** [comment]
@gjabell can you provide some more logs? that would be helpful evtl.

But thank you already for your effort!

**Comment by gjabell** [comment]
@Echolon I'll keep an eye on them and post more if I find the error again. Clearing out the `cloud_notify` dir and restarting the server seemed to fix it so it might have been a one-off thing.

**Comment by anurodhp** [comment]
thinking about this more they is likely the credentials on your server do not match those that the client registered with me. This happens if someone goes into notifications and taps rebuild at the bottom this regenerates everything
