### ISSUE TITLE
XEP-0184: Message Delivery Receipts - Receipts only sent while the client is open

### ISSUE THREAD

**Issue by gjabell** [anurodhp/Monal#352]
I am using Conversations to communicate with my family, who are using Monal. I have message delivery receipts enabled and have noticed that Monal only sends the receipt ACK if Monal is open, even if the message is received and a notification is shown. Conversations seems to consider a message as having failed to deliver after around 7 minutes of not receiving an ACK, and will offer the option to resend the message, which results in a second notification from Monal (although the message is not doubled).

Is it possible to send the ACK once Monal knows about a new message, even if the app is in the background (ie when the user is notified on their lock screen)? This would prevent Conversations from assuming that the message was lost.

XEP-0184: Message Delivery Receipts
[https://xmpp.org/extensions/xep-0184.html](https://xmpp.org/extensions/xep-0184.html)

Thanks!

**Comment by anurodhp** [comment]
Monal dedupes based on the message Id if the messge is sent twice it would ordinarily be shown twice. The notification right now just indicates to the user there is content but doesn’t download the message. I think this may be an issue with conversations implantation making assumptions it shouldn’t rather than monal

**Comment by gjabell** [comment]
That makes sense. Yeah arguably conversations shouldn't use the receipt in that way (although fwiw it only shows the deliverability "error" once). I think it would make sense for Monal to send the ACK receipt even when it's not the foreground application though, since showing the user a notification means the message was delivered to the user. The XEP spec also specifies that it just notifies of delivery, not that the user has necessarily read it.

**Comment by Alexmark1** [comment]
Is Monal even able to execute code while it is in the background or the screen is locked? There have been changes in iOS 13 that suspend apps more aggressively when they are not in the foreground. Related: #339

**Comment by anurodhp** [comment]
Thanks to fb using backgroud access to spy on people Apple has mostly shut background operations down in ios13. This is why the notifications are generic and not the actual message anymore. I am working on a fix, but it will take a while

**Comment by gjabell** [comment]
Ah fair enough, wasn't sure if it was possible or not. Wonder if it could be tied in with the cloud_notify or something?

**Comment by anurodhp** [comment]
More realistic is me putting in a change to the notifications in monal. I’m working towards it

**Comment by gjabell** [comment]
Fair enough. Thanks for all your hard work!

**Comment by tmolitor-stud-tu** [comment]
@gjabell If conversations shows the delivery error something on your server is probably misconfigured.
What server and modules do you use?
Prosody?

**Comment by gjabell** [comment]
@tmolitor-stud-tu it's possible, although I've noticed the following behavior:
- it only happens when sending to monal (at least I've never seen it when sending to conversations or desktop apps)
- the monal user gets a notification but doesn't open it within ~3-5 minutes
- resending it triggers another notification
- if the user opens the app within the 3-5 minute period (before the "fail to deliver" shows up), it'll correctly show the message as being delivered
- the server recognizes that a message was sent (and often will even show a log for the cloud-notify event waking up the user's phone)

As far as server goes, I'm running prosody w/ cloud_notify, smacks, mam, and some other modules that I don't think are relevant.

**Comment by tmolitor-stud-tu** [comment]
your server uses the default smacks timeout of 5 minutest, after that a session/connection is considered as closed an all messages that could not be sent to the client are returned with an error to the sender...**that** is the reason conversations shows an error. This has nothing to do with receipts.

Newer versions of mod_smacks contain code to determine if a client supports MAM (which monal does) and if so, suppress such errors.
If you update your prosody modules the error should go away.

You can also increase the smacks timeout to something like 12 hours or so (I'm doing this on my personal server).
This will stop the error from appearing, too (well, technically it will appear after 12 hours without opening monal after the first notification appeared).
`smacks_hibernation_time = 43200`

**Comment by tmolitor-stud-tu** [comment]
This bug issue can be closed now :)

**Comment by Echolon** [comment]
@tmolitor-stud-tu thank you for your work!

**Comment by gjabell** [comment]
@tmolitor-stud-tu Thanks for the follow-up, I'll fix the issues on my server :)
