### ISSUE TITLE
macOS Catalyst: adding MUC does not respect account entered, instead uses different account

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#353]
Related: https://github.com/anurodhp/Monal/issues/306 and https://github.com/anurodhp/Monal/issues/342

After manually entering account to add muc to, muc is being added to a different account on Monal macOS Catalyst build.

Not sure how or why the wrong account is used but this is reproducible for me w Version 4.2.3 (519) on 10.15.3.

**Comment by anurodhp** [comment]
will fixed in next beta

**Comment by foss-** [comment]
Version 4.3 (533) verified
