### ISSUE TITLE
iOS: lock icon placement off for encrpyted links (currently: right, expected: left)

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#355]
Posting an URL now has a lock icon on iOS. Can't test catalyst as omemo is not yet fully working there.

Minor: lock icon is on the bottom right, while for normal messages the lock icon is on the bottom left of the message bubble.
 
![lock placement](https://user-images.githubusercontent.com/5708172/74085094-e57c9e80-4a75-11ea-8337-84476849dc3e.jpeg)

**Comment by anurodhp** [comment]
fixed
