### ISSUE TITLE
Catalyst: last message cutoff UI wise, improve scroll behavior

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#356]
macOS 10.15.3, Monal 4.3 (524)

unsure when this started. but the last message is cutoff. even scrolling down does not show the complete message bubble.

<img width="642" alt="catalyst last msg cutoff" src="https://user-images.githubusercontent.com/5708172/74085196-f7ab0c80-4a76-11ea-8e84-6560002abac3.png">

**Comment by anurodhp** [comment]
Just this release. 

--
Anurodh Pokharel

**Comment by anurodhp** [comment]
fixed in the new build thats up

**Comment by foss-** [comment]
Version 4.3 (525) verified, thanks.
