### ISSUE TITLE
macOS Catalyst: Shortcut to close settings view with escape "ESC" key

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#357]
Version 4.3 (526) added support for cmd , to open the settings with https://github.com/anurodhp/Monal/issues/334.

This issue is about closing the settings with the escape key.

**Comment by tmolitor-stud-tu** [comment]
Can you check if this is implemented now?

**Comment by foss-** [comment]
Tested alpha October 05 2020 08:26:14, `⌘,` opens settings. `esc` does not close settings.

**Comment by tmolitor-stud-tu** [comment]
@FriedrichAltheide something for you

**Comment by tmolitor-stud-tu** [comment]
@FriedrichAltheide still something for you ;)

**Comment by FriedrichAltheide** [comment]
We really need someone for the UI...

**Comment by anurodhp** [comment]
I got it
