### ISSUE TITLE
macOS Catalyst: switching custom background only applied after restart of app

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#358]
Version 4.3 (526) added support to use custom backgrounds in Catalyst in https://github.com/anurodhp/Monal/issues/333.

**Currently** it is not possible once a custom background image has been selected and applied to switch to a different background image without restarting monal.

The first use of a custom background does not require a restart of monal. It is sufficient to switch the conversation

**Expected**: Ideally no restart would be required when switching custom backgrounds. If possible it would be great to instantly change the background, even for the Conversation the user currently is in after applying the custom image. So enforcing a reload of the background for all conversations (even the active/current conversation) would maybe solve this.

**Comment by anurodhp** [comment]
current version will apply the change once the conversation is changed.  will fix
