### ISSUE TITLE
Audio: File not playable and shows empty screen

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#362]
Hello Anu,

so far it was still possible to send (unencrypted!) audios to Monal and iOS user could play it. Today a friend told me it doesn't work anymore.

_Getting a file like this:_
<img src="https://user-images.githubusercontent.com/29168011/75385180-94770200-58df-11ea-80a4-bf8a8016190e.jpg" width="250">

_Opening shows only this:_
<img src="https://user-images.githubusercontent.com/29168011/75385213-a0fb5a80-58df-11ea-80d2-cb3ddf2fdc4e.jpg" width="250">

Even if full voice message support would be the ideal solution, it would be nice to re-enable playing within iOS.

EDIT: Actually does not to work for videos as well...

Related:
#6 **Add video and audio chat**

**Comment by anurodhp** [comment]
just tried this out with audio from conversations. It does play audio. All add a video /audio ui in 4.5

**Comment by sirdrakeistda** [comment]
I tried to send an encrypted audio file (.flac format, send with gajim), but I can't click on the audio file. Monal doesn't do anything when I try to open it.

**Comment by Echolon** [comment]
Yes, thats exactly the desribed case

**Comment by Echolon** [comment]
Would be really good to dig into this issue

**Comment by Echolon** [comment]
@tmolitor-stud-tu I will close with looking forward to the new file implementation (?) you announced, ok?

**Comment by tmolitor-stud-tu** [comment]
Okay

Am 26. Januar 2021 19:27:01 MEZ schrieb Echolon <notifications@github.com>:
