### ISSUE TITLE
Monal.IM is offline

### ISSUE THREAD

**Issue by Tyler-2** [anurodhp/Monal#364]
Set up my first user with Monal and was having issues getting push notifications to work. Then noticed:

```
# nslookup monal.im
Server:		50.116.53.5
Address:	50.116.53.5#53

** server can't find monal.im: NXDOMAIN

# nslookup push.monal.im
Server:		50.116.53.5
Address:	50.116.53.5#53

** server can't find push.monal.im: NXDOMAIN

```

I can't browse to the website either.

**Comment by Echolon** [comment]
@anurodhp I think thats urgend!

**Comment by anurodhp** [comment]
Well that’s weird. I’m checking with my hos, thanks

**Comment by anurodhp** [comment]
should be back up soon. Really weird. It’s a dns problem so  if you already had the up
For push.monal.im cached it would continue to work.  I have a job that sends a push evey night but it didn’t pick up this issue because of the cache

**Comment by anurodhp** [comment]
Dns Fixed, let me know if it’s not working still
