### ISSUE TITLE
[Mac OS] MUC unusable - No participants and no conversation

### ISSUE THREAD

**Issue by glomeg132** [anurodhp/Monal#365]
Join an existing group chat on Monal 4.4 shows no participants and no conversation. Trying to send a message follows to "Error:cancel - service-unavailable"

Deleting and rejoin the group with nickname/password filled and favorite and auto join marked managed to show the participants. In most cases also sending messages works after. No older conversation is shown.

**Comment by foss-** [comment]
Does this persist with the latest catalyst beta @glomeg132 ?
http://monal.im/Monal-OSX/Monal-OSX.zip

**Comment by Echolon** [comment]
@glomeg132 I will close this as there is no respond. Please come back, once you could check with the current version.
