### ISSUE TITLE
Own avatar image not settable

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#367]
The UI has no option to set my own avatar image, but I can see other avatar images just fine.
In fact I can even see my own image, if I use another client to set the image first.

**Comment by Echolon** [comment]
Hi @tmolitor-stud-tu 

thank you for your issue! Unfortunately, there is already an issue open: #148

I close this, please comment there.

(Anyway thanks for your efforts here!)
