### ISSUE TITLE
[MacOS] Closing last chat leaves it open on screen

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#369]
Version 4.5 (579)

**Comment by foss-** [comment]
Confirmed this is a general problem. Been seeing this for a while.

**Comment by Echolon** [comment]
@licaon-kter isn't this the iOS version?

**Comment by tmolitor-stud-tu** [comment]
should be fixed in Monal 4.8 or Monal 4.9 (don't recall exactly where @FriedrichAltheide  put this commit)
