### ISSUE TITLE
Support SCRAM-SHA-1 for authentication

### ISSUE THREAD

**Issue by aroquen** [anurodhp/Monal#37]
It should be possible to use SCRAM-SHA-1 for password hashing instead of PLAIN auth. See e.g. the prosody doc for a discussion on this https://prosody.im/doc/plain_or_hashed

**Comment by Neustradamus** [comment]
XMPP servers remove the old history unsecured MD5 support, any news on it?

**Comment by Echolon** [comment]
@Neustradamus MD5 auth has been removed ee6bfb2bdb33936cb8758735a6f168f30833b8a5

**Comment by tmolitor-stud-tu** [comment]
Moved to #384
