### ISSUE TITLE
Monal for older macOS versions

### ISSUE THREAD

**Issue by kyngchaos** [anurodhp/Monal#377]
I would like to install Monal on High Sierra, but the app store version requires Catalina.  Is there a non-app store build that supports earlier systems?  I tried to build from source (it says Monal supports back to 10.10) but get errors about missing Pod stuff, too much for me to figure out, I only work with compiling with the command line tools with 'nix configure/cmake projects.  It's been a long time since I played with Xcode projects.

**Comment by anurodhp** [comment]
The newest versions of monal are catalyst apps that only work on catalina. I have retired the old non catalyst code and that doesn’t exist anymore.

**Comment by kyngchaos** [comment]
catalyst only? Very disappointing.

I downloaded the Mac 2.4 release branch source, which has a last commit from June 2019, 4 months before Catalina was released.  The deployment target in the Xcode project is 10.10.  Older releases still available on Github are even much older than any betas of Catalina were available.  Are you saying this already was being developed for Catalyst then?  What version can I download and compile that supports High Sierra?

And, you have no downloadable archive of older versions?

I really need something that works on High Sierra with the current state of widespread work-at-home.  Apple's Messages has problems with setting a separate server address from the user login, which we need for our macOS server setup.

**Comment by anurodhp** [comment]
There is an ok design binary you can grab. Once is topped updating the code bass I pulled the binaries from public links because they would have bugs that will never be fixed. I’ll post a link here soon.

**Comment by anurodhp** [comment]
use this from january. 
https://monal.im/Monal-OSX/Monal-OSX-legacy.zip

**Comment by kyngchaos** [comment]
Thanks...

But, it looks like we have some other network issues keeping this from working - works for some but not others, even had a couple where it didn't work then it did.

Oh well

**Comment by foss-** [comment]
Monal Catalyst is the current code base and there is very little chance of two code bases being maintained in a project that is done in spare time by a very small team (mostly one dev).
Thus if you have to stay on an older macOS release, it is probably easier to try out Beagle IM:
https://github.com/tigase/beagle-im
