### ISSUE TITLE
OMEMO encryption not possible

### ISSUE THREAD

**Issue by sirdrakeistda** [anurodhp/Monal#379]
At the moment I can't encrypt with Monal. When go to contact details, there is no lock to activate the encryption. I can see the keys from my contact in the contact details and the contact can encrypt for Monal without Problems. In the contact details, it says "unkown subscription", but we both added each other as contact.
Monal 4.4
Server blabber.im
iOS 13.3.1

**Comment by Echolon** [comment]
@sirdrakeistda Hi, thabk you for reporting.
Just one question. may you crosschec the other issues or OMEMO labels if there are relations please?

**Comment by sirdrakeistda** [comment]
I tried to find a similar issue. There is only one issue that could be related, because there is also the lock missing.
https://github.com/anurodhp/Monal/issues/285
But there a few differences:
-There its Catalyst and not iOS
-There is an other notification "You can see their key. But they can't see yours" vs "unkown subscription"

**Comment by Echolon** [comment]
Is fine, thank you!

I can confirm that my Monal cobtact has the same issue actually

**Comment by sirdrakeistda** [comment]
After update to 4.5, the error changed. Now the Problem is similar to #285.

**Comment by tom709** [comment]
I had this problem several times and at least in my case the solution was simple: Monal as of 4.7 does not seem to support Contact subscription request procedure; you have to add mutual subscription between the two persons in another app (I used Gajim); after that you can enable OMEMO by clicking (i) at the top, then the lock in the dialog that opens.

**Comment by Echolon** [comment]
Hi @tom709,

currently there are works on the OMEMO impelementation:

https://github.com/tmolitor-stud-tu/Monal/commits?author=FriedrichAltheide

Please be a bit more patient till those made it to the master! 🙏

**Comment by FriedrichAltheide** [comment]
You may have to wait a few seconds after opening a chat for the first time till omemo devices are fetched.

**Comment by FriedrichAltheide** [comment]
fixed in alpha

e92e718c26a379b726872bd6b0de5d331fc158db
ba7aca4929f11e6b81ab673e1d4bd05efa0100a7
