### ISSUE TITLE
Connection loop after removing stream management 

### ISSUE THREAD

**Issue by aroquen** [anurodhp/Monal#39]
I have a prosody server with stream management (XEP-0198) enabled. I wanted to disable it to make some tests but I am facing some issues with a Monal client connected to the server. When I disable stream management and restart the server, Monal enters in a loop: it connects, tries to resume some previous stream, fails, connects again and so on. Attempt rate is about 1 every 10 sec. I expect Monal to recognize there has been some configuration change. 

Here is a sample of the logs:

```
May 14 22:14:15 c2sd8622    debug   Sent reply <stream:stream> to client
May 14 22:14:15 c2sd8622    debug   Received[c2s]: <resume h='9' previd='XXX' xmlns='urn:xmpp:sm:3'>
May 14 22:14:15 stanzarouter warn    Unhandled c2s stream element or stanza: resume; xmlns=urn:xmpp:sm:3: <resume h='9' previd='XXX' xmlns='urn:xmpp:sm:3'/>
May 14 22:14:15 c2sd8622    debug   Disconnecting client, <stream:error> is: <stream:error><unsupported-stanza-type xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
```

Note I have a Conversations client connected to the same server which resumes gracefully after disabling stream management.

**Comment by anurodhp** [comment]
the issue here is that when I reconnect I don't check to see if the same features are provided.  its not an elegant solution but the fix I have  put in is to requery when the app is restarted. Its a bit of an edge case so I haven't put a ton of time into actually resolving it completely (vs fixing other issue)
