### ISSUE TITLE
Missing new message notifications when Monal is running in background

### ISSUE THREAD

**Issue by tom709** [anurodhp/Monal#391]
Thanks for giving us Monal. But I have one issue: I am often missing messages. 

New message notifications are randomly missing when Monal 4.5 (iOS) is running in the background. This applies to notifications in the iOS notification area and lockscreen as well as to "icon badges", i.e. the red dot on the Monal icon indicating new messages.

Reproduce:
Start Monal on "Alice's" device and enter a conversation with "Bob". Press the home button on Alice's device so that Monal goes into the background. Now takes Bob's device and send a message to Alice. Look at the received message on Alice's device. Press home again. Repeat the whole process a couple of times. Observed result: sometimes, a new message notification and icon badge appears and sometimes not. Sometimes it is shown shortly but disappears within a second.

I guess what is happening is a race condition between the APNS message being received (triggering the notification/icon badge to be shown) and Monal in the background receiving the actual message (causing the notification to be cleared). Depending on which happens first, I get a persistent notification or not.

Monal should never clear new message notifications when running in the background, because then, the user has no way of knowing that new messages were received. It would be better to only clear the notification once Monal is brought to foreground or even when the corresponding conversation is viewed.

**Comment by Echolon** [comment]
rel. #373

**Comment by tmolitor-stud-tu** [comment]
Anu will rework the whole notification stuff. After that the bug should be gone away.

I observed the exact same behaviour btw. and your description and analysis is very accurate :)

**Comment by Echolon** [comment]
Confirmed. No notifications. However, I see the red message counter on the app.

iOS - Beta 4.7. (633)

**Comment by tmolitor-stud-tu** [comment]
Should all be fixed in the upcoming Monal 4.8
