### ISSUE TITLE
The operation couldn't be completed. Cannot allocate memory

### ISSUE THREAD

**Issue by uzairsabir** [anurodhp/Monal#399]
Hi,

I am facing this issue on version 4.6 when ever i connect to my own ejabbered server. It was working fine on 4.5 (downloaded from appstore). Kindly please help.

**Comment by Echolon** [comment]
@uzairsabir that was an error message that appeared in Monal? You tried to send a file?

**Comment by tmolitor-stud-tu** [comment]
this will be fixed in #398
