### ISSUE TITLE
push.monal.im down?

### ISSUE THREAD

**Issue by billroland** [anurodhp/Monal#400]
Is the Monal push server down?  The "Monal Push Server" is showing as unticked on the Notification Settings screen, my server is not connecting to the push service, and I can't ping push.monal.im either.  ChatSecure push is working so I believe my server is ok.  Thanks.

**Comment by Echolon** [comment]
@anurodhp 
(@tmolitor-stud-tu )

**Comment by anurodhp** [comment]
looking.

**Comment by anurodhp** [comment]
well looks like prosodyctl reload  doesnt reload SSL certs for HTTP. its fixed.

**Comment by tmolitor-stud-tu** [comment]
you should switch to prosody 0.11 or even better trunk...that will reload the 
certs, trunk will have SNI, too.
That means trunk is able to automatically load and present the right cert for 
each component/host automatically.
