### ISSUE TITLE
XEP-0215: External Service Discovery

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#401]
https://xmpp.org/extensions/xep-0215.html

As per https://www.process-one.net/blog/ejabberd-20-04/ "allows XMPP clients to discover STUN/TURN services and to obtain temporary credentials for using them"

**Comment by licaon-kter** [comment]
For A/V yes, using it with Conversations + ejabberd. ;)

**Comment by Echolon** [comment]
rel. #6 Add audio / video chat

**Comment by tmolitor-stud-tu** [comment]
This is not needed because we don't use webrtc and our av implementation is not interoperable.
We will switch to webrtc once most other bugs/features are fixed/complete.
