### ISSUE TITLE
Monal Crashes when Sending Large Encrypted Picture

### ISSUE THREAD

**Issue by a11fruitless** [anurodhp/Monal#408]
Monal: iOS (616)
Other Clients: Conversations, Gajim

With the present beta version, Monal (iOS) will crash if trying to send a large encrypted picture. From my rough tests, any picture greater than approximately 1 MB seems to cause Monal to crash for me. Any picture smaller than that seems to send fine.

If encryption is turned off, all pictures send without issue.

**Comment by anurodhp** [comment]
What iOS version?

**Comment by a11fruitless** [comment]
This is an iPhone XR using iOS version 12.3.1. Sorry for leaving that off. 

Tried going back a few versions to find where this started, but it looks like some things changed recently that keep Monal from logging in with old versions without recreating the account. Don't want to recreate this account at the moment (regen OMEMO keys).

Thanks for your help!

**Comment by Echolon** [comment]
@a11fruitless what was the last version that it worked?

**Comment by Echolon** [comment]
@a11fruitless ?

**Comment by a11fruitless** [comment]
Hi. Sorry for the delay. As I mentioned, I couldn't go back far enough in the previous versions to find that out. Something changed in the logins that prevents me from logging in with versions prior to 608. I don't own an iOS device, and I didn't want to reset the owner's account or create a test account on their device to find out. I went back to version 608 on Test Flight and it was still occuring. I can also confirm that the issue is still occuring on version 626.

Turn off the encryption and everything works fine. Send a smaller encrypted picture (by my testing < 1MB) and everything works fine.

**Comment by Echolon** [comment]
Confirmed. 2.7 MB wallpaper file.

iOS - Beta 4.7. (633)

**Comment by Echolon** [comment]
Confirmed for iOS - alpha 4.7 (30.07 18:39)

**Comment by Echolon** [comment]
Still confirmed for iOS - alpha 4.7 (13.08. 19:43)

**Comment by Echolon** [comment]
Is anyone here who can reproduce this on iOS > 12 ?

**Comment by FriedrichAltheide** [comment]
@Echolon please try again in the latest alpha version.

**Comment by Echolon** [comment]
@a11fruitless what picture exactly did you send? Link to source?

**Comment by foss-** [comment]
persisting macOS 10.15.7, Monal alpha from today

**Comment by tmolitor-stud-tu** [comment]
Should be fixed now in alpha

**Comment by foss-** [comment]
macOS 10.15.7
monal alpha December 01 2020 20:28:11
verified

thanks!
