### ISSUE TITLE
With all chats read and hidden: badge notification count is still at "2"

### ISSUE THREAD

**Issue by mbirth** [anurodhp/Monal#411]
I've read all messages, hid all chats so the list of "Chats" is completely empty. Yet the app icon for Monal still shows a red "2" badge. Disabling the badge and re-enabling it doesn't help. Rebooting the phone also doesn't help. I don't want to reinstall the app, if possible.

**Comment by Echolon** [comment]
Thank you for reporting.
Please be a bit patient with replies atm.

**Comment by FriedrichAltheide** [comment]
@tmolitor-stud-tu we should add a "mark all as read" button to the notification menu. (Update all rows in message_history with unread=0)

**Comment by tmolitor-stud-tu** [comment]
yeah, good idea!

**Comment by Echolon** [comment]
> @tmolitor-stud-tu we should add a "mark all as read" button to the notification menu. (Update all rows in message_history with unread=0)

Would be really nice, see also this suggestion:

**Remove notification + mark as read on multi-client message** #103

**Comment by mbirth** [comment]
I've noticed something strange recently. With no messages unread, the badge shows "2". Yet with 1 unread message, the badge correctly shows "1". When reading the one message, the badge changes to "2" again.

**Comment by anurodhp** [comment]
ive verified this  (i see it too) this appears to be a UI glitch.

**Comment by anurodhp** [comment]
should be fixed in next betas

**Comment by Echolon** [comment]
@mbirth Yes thanks for feedback. It is in the beta already, correct @tmolitor-stud-tu @FriedrichAltheide ?

I would like to ask for your patience again. the release is in preparation.

**Comment by tmolitor-stud-tu** [comment]
this will only be solved after refactoring of the whole notification subsystem, I'm on it.

**Comment by FriedrichAltheide** [comment]
I added a new reset button to the notification menu this morning. https://github.com/tmolitor-stud-tu/Monal/commit/90a3633245bbb8347785318e7485cc9a3ce812bf
Should be in the next PR.
