### ISSUE TITLE
Monal Push Server is off

### ISSUE THREAD

**Issue by surentharp** [anurodhp/Monal#413]
Hi,

I am using the latest release from Apple store. The app was working good.

Today, all of a sudden, I didn't get any notifications. When I checked in my Notification settings, the Monal Push Server is Off, so I think this affects my notification. Is, Monal Push Server down?

___________________________________
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by anurodhp** [comment]
This is a network problem at the server. I am looking

**Comment by anurodhp** [comment]
The push server seems to have Stopped overnight. I’ll investigate when I have time but it should be working again
