### ISSUE TITLE
Monal Push Server is off

### ISSUE THREAD

**Issue by surentharp** [anurodhp/Monal#414]
Hi,

I am using the latest Monal app, the Monal Push Server option is off in the Notification settings. I am not receiving notification, I think the Monal Push Server is having network problem.

___________________________________
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by Echolon** [comment]
Thank you for reporting. Let's wait what the developers say.

Can you please tell us the Monal version you have installed?

**Comment by surentharp** [comment]
Hi,

I use the version 4.6 (616).

**Comment by anurodhp** [comment]
yeah my alert went off as well. prosody seems to shut down and not restart sometimes. Ive fixed it thanks for reporting.  FYI there is a health check that shows the server status 
https://push.monal.im:5281//push_appserver/v1/health
