### ISSUE TITLE
info panel can not be closed

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#419]
macOS 10.15.6
Monal 4.7 (632)
Redesigned info panel can not be closed in most recent beta. Clicking on "Close" does nothing. Pressing ESC also does nothing.

Expected

Both click on "Close" and pressing ESC key should close the info panel.

Workaround: select different chat and go back to the chat with the unclosable info panel and users will find themselves in chat view again.

![monal not closing info panel](https://user-images.githubusercontent.com/5708172/87908770-49fd4a00-ca67-11ea-8691-2b1b8211b19d.gif)

**Comment by FriedrichAltheide** [comment]
Fix should be in the next build

**Comment by FriedrichAltheide** [comment]
ref 7b40568edc4a9e59538e85e963a62db5618a43dd

**Comment by Echolon** [comment]
@foss- thanks for the helpful feedback. I am going to close this due to the fix already. If there is anything later on, please come back!

**Comment by foss-** [comment]
Fix verified in alpha build provided by Friedrich.
