### ISSUE TITLE
Leaving conversation opens wrong dialog in wrong location

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#420]
macOS 10.15.6
Monal 4.7 (632)

**Reproduce**
1. join group chat
1. open info panel and click "Leave Conversation"

**Currently**
Dialog asking wether to add address to contacts.
![leave conversation](https://user-images.githubusercontent.com/5708172/87913687-c4ca6300-ca6f-11ea-9993-8430133b7976.png)

**Expected**
Dialog to ask leave conversation yes | no

**Additional Problems**
The extended Dialog should connect to the item it was opened for. In this case it should connect to "Leave Conversation" as otherwise this can be somewhat confusing.

**Comment by licaon-kter** [comment]
Same for 1:1 contact details: Remove contact, Block sender, Unblock sender
