### ISSUE TITLE
Duplicate resources for contact

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#421]
```
/Conversations.XXXX
Conversations.XXXX
```

Latest Mac beta 4.7 (632)

**Comment by Echolon** [comment]
You mean that those double resources are shown in other clients like Dino or Gajim?

**Comment by licaon-kter** [comment]
This is the Monal issues tracker :)

**Comment by Echolon** [comment]
:neutral_face: Many clients show this for their contacts.

If you don't mean this, I don't understand where you see several resources. Do you have a screenshot?

**Comment by tmolitor-stud-tu** [comment]
This is only because of a (now fixed bug) in an older beta.
We don't have code to clean up the resource list as far as I know.
--> The old unused (and wrong) resource "/Conversations.xxxx" is still in the db and gets displayed.

**Comment by Echolon** [comment]
But there is action necessary to build a clean up?

**Comment by tmolitor-stud-tu** [comment]
I just now found the code that triggers the cleanup of old resources and the code path you took to not reach it ;)
I fixed it (should be in next beta once my next pull request for push will be merged)
