### ISSUE TITLE
MUC titlebar shows `contactJid (XXX)` and `online`

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#423]
...where XXX is members count.

Note that's literal "contactJid" text, not XMPP address.

Mac beta 4.7 (632)

**Comment by FriedrichAltheide** [comment]
Should already be fixed in the alpha. @tmolitor-stud-tu have your tried my patch?

**Comment by licaon-kter** [comment]
I'm not aware on how to get the alpha, I just use the ZIP from the sitee

**Comment by tmolitor-stud-tu** [comment]
what patch exactly?

**Comment by FriedrichAltheide** [comment]
https://github.com/tmolitor-stud-tu/Monal/commit/ed2e144f5b14b543639f2fcc0dd73ac396d50c62

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter you can get the alpha here: https://www.eightysoft.de/monal/
for iOS you need to be unlocked by me via device UDID.

If you want to use homebrew/cask you can use this formula: https://github.com/tmolitor-stud-tu/homebrew-monal-alpha

**Comment by tmolitor-stud-tu** [comment]
no, didn't try it yet, I don't have any groups in my test install on my old ios 12 device

**Comment by licaon-kter** [comment]
> If you want to use homebrew/cask you can use this formula: https://github.com/tmolitor-stud-tu/homebrew-monal-alpha

It's a Mac VM in Virtualbox, I do have homebrew for Dino and Siskin.

Can you detail the commands as I'm not really familiar with formulas?

**Comment by tmolitor-stud-tu** [comment]
@FriedrichAltheide what are the exact brew commands to use our cask repo?

**Comment by tmolitor-stud-tu** [comment]
the tar file directly should be enough...but using brew should make updating much easier :)

**Comment by licaon-kter** [comment]
Tried the TAR, logged it, tried to open an 1:1, got the spinning ball....had to kill Monal to be able to shutdown the VM.

**Comment by licaon-kter** [comment]
@tmolitor-stud-tu Yes, your build has this fixed thanks

**Comment by Echolon** [comment]
Thanks everyone!
