### ISSUE TITLE
Account view - menu order off by one

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#425]
MacOS 4.7 (634) beta

Pressing MAM does nothing
Pressing My keys opens MAM
Pressing Change Password opens My keys
Pressing Resource opens Change Password

**Comment by Echolon** [comment]
Thanks for reporting. I checked again with alpha 4.7 (30.07 18:39)

It seems to be fixed, I will close this. Please come back if that should still existing in the stables later.

**Comment by licaon-kter** [comment]
635 has it fixed indeed
