### ISSUE TITLE
MacOS have specific resource name

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#429]
...instead of `Monal-iOS.xxxx`

MacOS 4.7 (634) beta

**Comment by tmolitor-stud-tu** [comment]
why?

**Comment by tmolitor-stud-tu** [comment]
Conversations does not let you choose a resource name either.

**Comment by licaon-kter** [comment]
There's no Desktop version of Conversations, right?

Didn't say CHOOSE, but USE.

**Comment by tmolitor-stud-tu** [comment]
Already implemented. Please check with a fresh install and a new account.
If it still says "iOS" instead of "macOS" I'll reopen.

**Comment by tmolitor-stud-tu** [comment]
maybe fixed now: https://github.com/tmolitor-stud-tu/Monal/commit/2b2b5eecb6997445fd6e8e46a4d5d283b8ac9c12

**Comment by licaon-kter** [comment]
I'll wait for the updated TAR then...

**Comment by licaon-kter** [comment]
@tmolitor-stud-tu quick question, is Move to Bin and Empty Bin enough to clean up app settings and accounts and all?

The web guides are not updated tvfor Catalina and I can't seem to locate where exactly these are stored.

**Comment by tmolitor-stud-tu** [comment]
I don't know, just try. But my guess would be yes.

**Comment by licaon-kter** [comment]
635 has this fixed, indeed
