### ISSUE TITLE
Add support for renaming contacts

### ISSUE THREAD

**Issue by sysfu** [anurodhp/Monal#43]
It would be nice to have the ability to rename contacts directly from Monal.

Current workaround is to do all contact renaming from another XMPP client.

**Comment by Echolon** [comment]
I think this is essential for UX, too!

**Comment by thenktor** [comment]
Yes, please add this. Without this feature Monal is actually not usable as only XMPP client. Especially if your contacts have cryptic Jabber IDs (I've added some Quicksy.im contacts and they show as telephone numbers only).
