### ISSUE TITLE
MacOS - remove push settings

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#430]
...as these don't apply, right? Apple/Monal/Tokens entries

MacOS 4.7 (634) beta

**Comment by anurodhp** [comment]
No it still uses push (optionally) 

--
Anurodh Pokharel

**Comment by licaon-kter** [comment]
These are unchecked for me, using the ZIP, this is normal vs App store install?

**Comment by anurodhp** [comment]
App Store app would be properly  signed yes  

--
Anurodh Pokharel
