### ISSUE TITLE
Make lock icon in chat UI top right interactive

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#437]
Monal 4.7 (635)
macOS 10.15.6

**Currently**
Confusing UI - a lock icon is shown in chat view in the top right. The icon suggests it is clickable as clicking it, briefly dims it and then it turns back to normal. But actually the icon is not interactive. It is merely a visualisation of the state (encryption on | off).

So in order to enable | disable encryption users have to click the i Icon. In the info panel, which then opens they see identical lock icon. This time it is interactive and actually allows to enable | disable encryption.

**Expected**
This is highly confusing. There is no way for the user to know which icon is interactive and which is not.
To solve this confusion, I recommend making the lock icon in the chat UI interactive as well. This solves several problems and gives users easier access to toggle encryption on | off.

Chat UI: non-interactive lock icon
![icon](https://user-images.githubusercontent.com/5708172/89174217-c9ba0700-d585-11ea-93a4-be21d27abf18.png)

Info Panel: interactive lock icon
![info panel](https://user-images.githubusercontent.com/5708172/89174654-857b3680-d586-11ea-914a-c01f53926878.png)

**Comment by foss-** [comment]
Verified in August 19 2020 07:31:01 Version 4.8 (0)

**Comment by licaon-kter** [comment]
4.8 (641) macOS

Click the lock -> "This contact does not appear to have any devices that support encryption"
Click the Info -> click the lock -> lock on -> click the lock -> lock off 
Click Encryption keys -> 2 keys llisted
Click the lock -> lock on
Go back to chat -> lock on -> click lock -> lock off 

And now it works just fine, but that first interaction appears to be broken

**Comment by foss-** [comment]
Can you file a separate bug for that, as it is not specific to the icon location but rather general OMEMO functionality and key exchange related.

**Comment by licaon-kter** [comment]
It's about icon functionality, as the contact details icon works fine.

**Comment by foss-** [comment]
Oh I did recall I had some inconsistend behavior with the other lock icon as well so didn't assume it was limited to this new location. But things change a lot in Monal so might be two different issues we were seeing.
