### ISSUE TITLE
UI: Keyboard not shown sometimes

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#438]
Sometimes the keyboard is not shown.

Unfortunately I cannot reproduce :/

<img src="https://user-images.githubusercontent.com/29168011/89585425-1cbde380-d83e-11ea-946c-ac87014672eb.PNG" width="250">

----
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by anurodhp** [comment]
im guessing this is ios12, judging from the icons. i  will close please reopen if it is still an issue.
