### ISSUE TITLE
Contacts being duplicated

### ISSUE THREAD

**Issue by JohnneyBoy** [anurodhp/Monal#44]
Hello, I have my own jabber server, which Monal (iOS) accesses just fine. I get an initial list of contacts. However, if I then send a message to a contacts, then come back to the contacts, they seems to have duplicated, i.e. xyz@xyz.com appears twice. If I stop/shutdown Monal I get the original contact list, i.e. no duplicates.

John

**Comment by rf600** [comment]
I am seeing this same behavior also. In some cases, there are triplicates.
iPhone 7+
iOS v10.1
Monal v2.9.3

**Comment by anurodhp** [comment]
The  clearing the container will fix Mac clients on the newest beta that may have a dB in an in consitwnt state that show duplicate contacts. iOS you can delete and reinstall.
