### ISSUE TITLE
XEP-0172: User Nickname

### ISSUE THREAD

**Issue by felinira** [anurodhp/Monal#45]
Monal does not allow to set a custom nickname. This is especially important for MUC chats. Currently the nick displayed to others in muc chats is the username part of the JID.

This should be fixed by implementing [XEP-0172](https://xmpp.org/extensions/xep-0172.html) and allowing people to use custom nicknames

**Comment by anurodhp** [comment]
nick names are now supported properly in Muc. will be int he next Mac update followed by iOS
https://monal.im/blog/mac-has-group-chat/

**Comment by tmolitor-stud-tu** [comment]
@anurodhp but these nicks are derived from the resource part (in muc) or locally set.
XEP-0172 will allow the *remote* party to set a proper nickname/name across mucs and 1:1 chats.

See here for an explanation where nicknames should be generated from and which one has which priority: https://docs.modernxmpp.org/client/design/#contexts

**Comment by tmolitor-stud-tu** [comment]
I implemented XEP-0172 now (but not for mucs yet)

**Comment by Echolon** [comment]
The function also reads nicknames which have been set via another client?

**Comment by tmolitor-stud-tu** [comment]
sure :)


Am Montag, 19. Oktober 2020, 09:14:57 CEST schrieb Echolon:
> The function also reads nicknames which have been set via another client?
