### ISSUE TITLE
Minor correction in App details: Version and show full text

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#453]
Hello,

I want to suggest two corrections:
- Put a variable for the current Monal version
- Always show the complete text if that is possible to configure

<img src="https://user-images.githubusercontent.com/29168011/90543529-1f95ce00-e186-11ea-9746-78076c605c5c.PNG" width="320">

**Comment by anurodhp** [comment]
The version is filled in under info there.  I don’t think I can force the default display to expand. These are things in apples app
