### ISSUE TITLE
Port to windows phone using bridge for iOS

### ISSUE THREAD

**Issue by tigre-bleu** [anurodhp/Monal#46]
There is currently no modern XMPP app for Windows Phone that supports at lease:
- MUC
- MAM
- HTTP Upload

I have no idea if it is easy or not, but you could try to use Microsoft Bridge for iOS in order to provide Monal for Windows Phone:

https://developer.microsoft.com/en-us/windows/bridges/ios

**Comment by anurodhp** [comment]
i looked at this when it originally came out.  There are large parts of the API missing. Additionally, i just don't have the bandwidth to support a third platform.  Others are welcome to try, but I don't have time to do it.
