### ISSUE TITLE
No audio heard in call, not seeing inbound RTP

### ISSUE THREAD

**Issue by gracion** [anurodhp/Monal#47]
I have Monal running on an iPhone and iPad on the same network. Login, presence, and text chat between them is successful, but audio call is not.

To reproduce:
- Log each device into a separate XMPP account (local XMPP server on same network).
- Tap (i) and green “Call (Beta)” button in one device, “Accept Call” on the other.

Both display “Calling" view with Cancel button. No sound is heard on either device.

Running one in Xcode, it looks like the app is receiving packets, but they are not RTP:
1/second polling is occuring, and when a packet comes in, ProcessRawPacket is called, but IsRTP() never returns true.

I’m not sure where the failure is. Debugging with printf’s in jrtplib, it appears to be sending RTP packets. And if I run Monal in the simulator and run Wireshark there, I see UDP packets with 172 bytes of data going out, but not coming in from the other device running Monal. I’m not sure those are RTP, since Wireshark knows about RTP but does not indicate they are.

I’d like to troubleshoot and fix this. Any suggestions where to look?

Version: “2.9.2 (0)” top-of-tree debug from github. (Same results with 2.9.1 downloaded from App Store )
Environment: 802.11g unencrypted/open (Old Airport Extreme), Mikrotik RouterOS providing DHCP.
Account settings: TLS off. Server: OS X 10.10.5, OS X Server Messages service 5.0.15.
iOS 9.3.5
Other anomalies: after device sleep, a repeating login/failure cycle occurs about 2 second interval until I use Log out All. Then Reconnect All is successful.

**Comment by anurodhp** [comment]
hmm, i haven't looked at this code in a few years.  It just sort of worked, wire shark should definitly identify the RTP stream, that is how i debugged it when i originally wrote it.   UDP does not have the handshake that TCP does, it might just be blasting packets / listening on the wrong ip and port combo.

**Comment by gracion** [comment]
Great, I'll check out the ports and what Wireshark is seeing this weekend. Thanks for the note.

**Comment by gracion** [comment]
I can't see anything wrong WRT ports or anything else. Of course the simulator does not support audio, but running on two devices they connect but nothing is ever heard. I did get it to run on iOS 10 with a few required CFBridgingRelease and adding a NSMicrophoneUsageDescription string to the info.plist. I expect to try again in a couple of weeks.

**Comment by anurodhp** [comment]
Thanks for checking. I'll check the audio code. It's possible something chaged in iOS and I didn't realize. 

--
Anurodh Pokharel

**Comment by gracion** [comment]
Latest build and test: I pulled to top of tree (see you're working on Mac, cool), and got a new result when running dev builds on two devices: About 8 seconds after accepting the call, both devices play 1 to 2 seconds of audio (one buffer worth?) from the beginning of the call, then nothing heard after that. I did about 10 tries with the debug build and once it did keep playing in one direction. I could not reproduce this partial success. I’m not sure why I get audio now instead of my previous builds, but at least we know audio packets are making it through.  One clue: upon tapping “Cancel”, this error is logged many times:  void AudioInputCallback(void *, AudioQueueRef, AudioQueueBufferRef, const AudioTimeStamp *, UInt32, const AudioStreamPacketDescription *) [Line 268] audio reenqueue error -66632.  The number of times logged equals NUM_BUFFERS_REC in RTP.hh (500).

**Comment by anurodhp** [comment]
So  I tested this more today. Could you try the latest Mac beta on the website or the current code. It appears there was permissions change in I failed to account for .

**Comment by gracion** [comment]
Thanks for taking another look. It'll probably be a while but I'll try to get to it at some point.

**Comment by anurodhp** [comment]
Regarding wirehark, the UDP packages are rtp.  You need to right click and tell it to identify it as RTP. You would then be able to just use the RTP stream analysis to play back the audio of the conversation in Wireshark. That said, I know the audio is broken in the current iOS client so it may not be worth you time to check that one. I'm preparing to release the next update and that would be a much better place to look at things.

**Comment by gracion** [comment]
My less-than-swift report: Everything looks good now! I have a local build from source running on iPad and talking to the app store version on my iPhone and the OS X dmg binary version. Audio working in all directions. I'll just close this issue if that's ok. (Mumble 1003001001, mumble-iphoneos git 3f1ce81)
