### ISSUE TITLE
Translate string in "ACCOUNT TO USE".

### ISSUE THREAD

**Issue by poormusic2001** [anurodhp/Monal#474]
### Description of my issue or feature request:

I am translating Traditional Chinese and I found a phrase that I don’t understand.

That is “Account To Use”. 

Does that mean “need accounts”?

### The Monal version and system version I use:

Version 4.8 (638)

### Additional information like screenshots:

I search the phrase in the the code. 

It shows the phrase is in the "Edit Group Chat". 

When the number of account is not equal to one then the phrase shows up.

http://u.pc.cd/jOkrtalK

I delete all of my account.

It shows up. See the red rectangle.

http://u.pc.cd/FwfrtalK

The page clicks from "Join a Group Chat".

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
It means something like "which account should I use to connect to the group 
chat?"
if you have multiple accounts you could use any of them to enter a group chat, 
thus the app asks you what account to use.
if you enter a work related groupchat, for example, you most certainly want to 
use your work xmpp account and not your private one.


Am Donnerstag, 27. August 2020, 15:12:03 CEST schrieb JimTsai:

**Comment by Echolon** [comment]
I would change it to:

`Selected account:`
`Account of choice:`

**Comment by poormusic2001** [comment]
How about "Account"?

**Comment by tmolitor-stud-tu** [comment]
I think "Account to use" is better, but Account ist okay, too

**Comment by Echolon** [comment]
May just state it like this:

`Select the account you want the group chat to connect with:`

**Comment by Echolon** [comment]
Review in code #463

**Comment by tmolitor-stud-tu** [comment]
I think we can close this now :)
