### ISSUE TITLE
HTTP Upload: Picture not shown sufficiently, transparent background

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#478]
Hello,

this is the situation of what I send and how it is shown in the current Beta:

<kbd>
<img src="https://user-images.githubusercontent.com/29168011/91757293-5defac00-ebce-11ea-8da9-081416bb10f6.PNG" width="220">
</kbd>

If I look at the same chat in the Alpha, I see only this:

<kbd>
<img src="https://user-images.githubusercontent.com/29168011/91757301-60ea9c80-ebce-11ea-8416-3b7afb07e1d2.PNG" width="220">
</kbd>

Clicking the transparent area will show up this:

<kbd>
<img src="https://user-images.githubusercontent.com/29168011/91757311-63e58d00-ebce-11ea-8895-9f166ff1a223.PNG" width="220">
</kbd>

Beta: 4.8 - 646
Alpha: 4.8 - 31.08.2020: 18:28:31

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by Sadiashraful-KCL** [comment]
I implemented the same feature recently and found the same issue

**Comment by tmolitor-stud-tu** [comment]
can you still confirm this?

**Comment by Sadiashraful-KCL** [comment]
Hi, 

Yes I implemented the feature yesterday and found the issue of transparent backgrounds.

**Comment by tmolitor-stud-tu** [comment]
implement? where?

**Comment by Sadiashraful-KCL** [comment]
I implemented the service in my own app with uploading file feature.

**Comment by FriedrichAltheide** [comment]
@Echolon could you try the new beta?

**Comment by Echolon** [comment]
Still exists unfortunately 🙁

**Comment by tmolitor-stud-tu** [comment]
and in 4.8? still existing?

**Comment by tmolitor-stud-tu** [comment]
or better: 4.9?

**Comment by Echolon** [comment]
Yes, it is fixed in the 4.8 - however I couldn't check for the alpha because MAM does not load that far :/

Anyway, thanks!
