### ISSUE TITLE
NSPOSIXErrorDomain error at Login time

### ISSUE THREAD

**Issue by meghaParmar** [anurodhp/Monal#48]
After integration of Monal sample to my code, after using Login code getting following error 
`Stream error code=49 domain=NSPOSIXErrorDomain   local desc:The operation couldn’t be completed. Can't assign requested address`
Same credentials are working for Monal app but in application with integration gives this error.

**Comment by anurodhp** [comment]
Hi, sorry i can't offer any help with your custom application that uses this code.
