### ISSUE TITLE
Mac notifications use stock notif sound instead of selected one

### ISSUE THREAD

**Issue by Boundarybreaker** [anurodhp/Monal#481]
### Description of my issue or feature request:
When receiving a notification on Mac, the stock MacOS notification sound is used instead of one of the Monal custom ones.

### The Monal version and system version I use:
Mac 4.7
MacOS Catalina 10.15.6 Beta 19G73

### Additional information like screenshots:

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
Please wait for Monal 4.8 and report again if this hasn't changed.


Am Dienstag, 15. September 2020, 01:14:43 CEST schrieb Meredith Espinosa:
> ### Description of my issue or feature request:
> When receiving a notification on Mac, the stock MacOS notification sound is
> used instead of one of the Monal custom ones.
> 
> ### The Monal version and system version I use:
> Mac 4.7
> MacOS Catalina 10.15.6 Beta 19G73
> 
> ### Additional information like screenshots:
> 
> 
> ---
> [x] I have cross-check this overview
> https://github.com/anurodhp/Monal/issues/322 as well es filtered for
> regarding labels https://github.com/anurodhp/Monal/labels
