### ISSUE TITLE
Suddenly no new message notifications

### ISSUE THREAD

**Issue by surentharp** [anurodhp/Monal#486]
Hi,

**Description of my issue**:
I am experiencing the below issue for the past 10 hours now, before that it was working perfect.

Only If I keep the app open, the message notifications are getting delivered, or else the message notifications are not getting delivered.

**The Monal version I use**:

Version 4.8 (648)

**Additional information**:

We are using Openfire server at the backend. The logs are displaying that the push notifications were delivered, I hope this may help you for your analysis.

`org.igniterealtime.openfire.plugins.pushnotification.PushInterceptor - Delivered a notification for user 'user' to node 'Y4T5CR8B-0763-4517-D456-R356R303BWER' on service 'ios13push.monal.im'`

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by FriedrichAltheide** [comment]
Workaround for now: Go to settings - accounts - click reconnect all

@tmolitor-stud-tu  and I are aware of the bug and still investigating

**Comment by surentharp** [comment]
Hi @FriedrichAltheide,

It started working again, I can able to receive message notifications now. Thank you guys for rectifying and making it work again.

**Comment by anurodhp** [comment]
there was a problem with the push server and i restarted it. @tmolitor-stud-tu  is looking at it so we can fix the bug

**Comment by surentharp** [comment]
Thank you @anurodhp for rectifying the problem
