### ISSUE TITLE
Horizontal rotation: Top bar info not shown correctly

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#488]
Hello,

just reporting a minor UI issue:

When the screen is turned horizontal, the top bar _"Last seen"_ info cannot be read.

<kbd>
<img src="https://user-images.githubusercontent.com/29168011/94736718-f5caec00-036c-11eb-9597-5d55f1fb1e9d.PNG" width="480">
</kbd>

Possible solutions, in at least my preference order:

- Just don't show it (What's App also does not show it here)
- Expand on click
- Place it on the right

iOS: 12.4
Alpha: 4.8 - 30.09.2020: 17:55:57

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
you forgot to mention the solution "make top bar higher"

**Comment by foss-** [comment]
Fixed in 4.9.1 please close @Echolon

**Comment by Echolon** [comment]
Thanks
