### ISSUE TITLE
[macOS] Change text from "Pull to load more messages"

### ISSUE THREAD

**Issue by licaon-kter** [anurodhp/Monal#491]
...to something more appropriate, "scroll to..."?

Ref: https://github.com/anurodhp/Monal/blob/d8d09b2c7e8f183196c166256607a764e16e3b62/Monal/localization/en.lproj/Main.strings#L33

**Comment by Echolon** [comment]
But wait... isn't it pull down? Or scroll down?

I actually depends if iOS or MacOS right?

**Comment by licaon-kter** [comment]
Can I pull on Mac? I guess, on that trackpad...?

**Comment by FriedrichAltheide** [comment]
Fixed in alpha
