### ISSUE TITLE
Certificate chain is invalid for certificate with many hostnames.

### ISSUE THREAD

**Issue by ari** [anurodhp/Monal#497]
Trying to connect to chat.ish.com.au results in this error, regardless of "validate certificate" setting. The certificate is valid, but note that it contains several hostname in the one certificate which is probably confusing Monal.

Also note that Monal cannot detect the SRV record, even though it should:

` dig _xmpp-client._tcp.ish.com.au srv`

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by Echolon** [comment]
Yep, SRV is not yet implemented.
Thanks for reporting. Lets wait on feedback

**Comment by Echolon** [comment]
Can you provide your client version please?

**Comment by ari** [comment]
4.8 (659)

**Comment by tmolitor-stud-tu** [comment]
@ari what username did you configure? `<something>@ish.com.au`?

**Comment by tmolitor-stud-tu** [comment]
also: what error do you get exactly?

**Comment by ari** [comment]
The error was the SSL Verify error, that the certificate was invalid. But interestingly I moved the server from prosody to ejabberd for unrelated reasons and now the issue has gone away. The server .pem certificate file is the identical file from the old config (signed by Let's Encrypt) but I can't make the error happen now.

Odd. I'll close this ticket and keep exploring. Thanks for your help.

**Comment by Echolon** [comment]
Thanks for the feedback!

**Comment by ari** [comment]
Turns out the problem came back. I cannot see what causes it to happen sometimes, but perhaps you'd like to connect to the server with user ari@ish.com.au and see if you can reproduce the SSL issue.

    SSL Error: Certificate chain is invalid

**Comment by FriedrichAltheide** [comment]
Please check your server (VirtualHost) c2s with e.g. IM Observatory.

You should include "ish.com.au" in your cert.

**Comment by ari** [comment]
Are you sure that is correct? The actual server certificate at chat.ish.com.au is in the certificate and that's what is found in SRV as the hostname.

The bare domain is not in the certificate, but I'm not understanding why it should be. No other XMPP client I've come across has this problem with this particular server.

https://xmpp.net/result.php?id=1474553

**Comment by FriedrichAltheide** [comment]
> Trying to connect to chat.ish.com.au results in this error, regardless of "validate certificate" setting. The certificate is valid, but note that it contains several hostname in the one certificate which is probably confusing Monal.
> 
> Also note that Monal cannot detect the SRV record, even though it should:
> 
> ` dig _xmpp-client._tcp.ish.com.au srv`
> 
> [x] I have cross-check this overview #322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

` dig _xmpp-client._tcp.ish.com.au srv` -> you are trying to login as `<user>@ish.com.au`. therefore you should add ish.com.au to your cert. (ref. https://prosody.im/doc/certificates#which_domain)
https://xmpp.net/result.php?id=1474556

If you try to connect as `<user>@chat.ish.com.au` you should add a corresponding SRV record.
`dig _xmpp-client._tcp.chat.ish.com.au srv` -> no SRV set

**Comment by ari** [comment]
Interesting. You are correct:

https://xmpp.org/rfcs/rfc3920.html#tls  (point 8)

However this makes some things complicated.

1. ACME (let's encrypt) wants to connect to port 80. But port 80 of the bare domain usually points to a public website, not the XMPP server.
2. Most other XMPP clients don't have this design. Yours is the first I've hit with this implementation.
3. Giving a chat server a certificate for the bare domain seems like it is exceeding the authority it should be given. A vulnerability here would be more significant.

Anyhow, thanks for the insight.
