### ISSUE TITLE
Outgoing messages remain in Sending state

### ISSUE THREAD

**Issue by tom709** [anurodhp/Monal#498]
### Description of my issue or feature request:
After upgrading to Monal 4.8 on iOS, all outgoing simple text messages from one of our devices remain in state "Sending..." (shown next to the message). I verified under accounts that Monal is connected to the server. I also tried reconnecting multiple times. The issue continued to exist after 48 hours. This happens regardless of whether OMEMO is on or off. The server is magicbroccoli.de.

I tried sending OMEMO encrypted messages to the affected device. They seem to be received but the device only shows "There was an error decrypting this message (Signal error)...try sending a message to this person...". This error used to occur randomly before (although many OMEMO messages had already been sent both ways), but now it always occurs.

### The Monal version and system version I use:
Monal 4.8. iOS 14.
Before updating Monal on the affected device I tested 4.8 on another device running iOS 13 and there it works normally. Not sure if iOS version is related though.

### Additional information like screenshots:
Monal 4.7 was working normally on the affected device with same accounts and servers before updating to 4.8.

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by Echolon** [comment]
Thank you!

I think there has been a fix implemnted in the alpha already!
@tmolitor-stud-tu

**Comment by tmolitor-stud-tu** [comment]
can you try reconnecting once more and provide a log containing that reconnect?
you can send it to thilo@eightysoft.de

**Comment by tom709** [comment]
Problem only occurs on a friend's device. I don't know if and when I will have phy access again. Will try to reproduce on my own (iOS 13) device, but no luck so far.

**Comment by FriedrichAltheide** [comment]
should be fixed in the latest beta #506
