### ISSUE TITLE
Option: Enable use Openstreetmap instead of iMaps

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#507]
### Description of my issue or feature request:

I would like to suggest to optional use Openstreetmap instead of iMaps for the dhare location funcation as a matter of privacy. That could be selected under privacy settings, too.

---
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by FriedrichAltheide** [comment]
You could disable: "Show Inline Geo Location" in privacy settings

**Comment by Echolon** [comment]
Yes, true. I intended to suggest thus as a third option:

- Disable
- iMaps
- OSM

**Comment by FriedrichAltheide** [comment]
Disabled == OSM. Just tap the msg

**Comment by Echolon** [comment]
Ok, I checked this out and deactivated inline geolocation. However, when I try to share, Monal is simply asking for the permission to access my geolocation.

What do I not understand?

**Comment by tmolitor-stud-tu** [comment]
To share your location monal has to know your location, so that is expected...
I think wie can close this

**Comment by Echolon** [comment]
Yes sure. However, is there a need to serve the geo-data to iMaps as well? I think that is a thing one day that we should question if its worth to import another library. I personally think yes. However, Friedrich don't wants this.

**Comment by tmolitor-stud-tu** [comment]
virtually every iOS user is using iMaps, I don't think it is necessary to jump through several burning rings just to implement a feature nobody really needs.

Most iOS users even back up all app data and settings into the apple cloud.

**Comment by Echolon** [comment]
Yes, they do, because they more or less don't have the option. And I don't think we should follow all those things they commonly do.

For sure that is not an important feature now or in the near future but it should be considered in my opinion. We are not the guys/app which is doing things the "mainstream" way. That's something people should and will appreciate.

**Comment by foss-** [comment]
Agreeing with echelon. Can we keep this open? Just because there are privacy insensitive defaults and the majority of users follows defaults doesn't mean it's not a good idea to do better. So offering OSM as alternative to Apple Maps is a valid feature request.

**Comment by Echolon** [comment]
Friedrich explained that will increase the need to import another library.

What do you think @anurodhp ?

**Comment by anurodhp** [comment]
Generally speaking I think there needs to be a strong reason to not use the native library. I don’t see that here. Every added library is more to maintain in the long run. An option to disable May be useful but adding more that needs to be maintained is the opposite of what we have been doing the past year
