### ISSUE TITLE
Need Help, build failed

### ISSUE THREAD

**Issue by seal555** [anurodhp/Monal#509]
Hello everyone,
I'm facing some problem after successfully clone the branch and then open it on XCODE, everything looks fine but when I'm try to build it always fail. 
Below is the some error messages found:
**_/Users/me/Monal/Monal/Pods/Target Support Files/Pods-NotificaionService/Pods-NotificaionService.debug.xcconfig: unable to open file (in target "NotificaionService" in project "Monal")_**
**_Unable to read contents of XCFileList '/Target Support Files/Pods-Monal/Pods-Monal-frameworks-Debug-output-files.xcfilelist'_**
**_Unable to load contents of file list: '/Target Support Files/Pods-Monal/Pods-Monal-frameworks-Debug-input-files.xcfilelist'_**
**_Unable to load contents of file list: '/Target Support Files/Pods-Monal/Pods-Monal-frameworks-Debug-output-files.xcfilelist'_**

I'm using XCODE 12.1 and MacOS Catalina 10.15.7

Is there any clue how to solved this issue. Or at least anyone can guide me step-by-step to build this project successfully? Kindly appreciate your help. 

Best Regards

**Comment by FriedrichAltheide** [comment]
Make sure that you have cocoapods and bartycrouch (optional) installed.
```
cd <CLONED_REPO_FOLDER>
cd Monal
pod install
open Monal.xcworkspace
```

**Comment by seal555** [comment]
Amazing, thankyou very much for your help, really appreciate it!!!

Best Regards

**Comment by Echolon** [comment]
Hi @seal555,

do you further plan to contribute to the project?
