### ISSUE TITLE
Reconnecting causes Connection Loop

### ISSUE THREAD

**Issue by bugtrapper** [anurodhp/Monal#51]
Monal (on iOS) enters a connection loop here which seemingly causes the Jabber server to block connection attempts for a while. We encounter that a lot in testing server-related stuff.

Steps taken: 
- Connecting to the account via Pidgin (works fine)
- Disconnecting from the account with Pidgin
- Connecting to the account with Monal (works fine)
- Closing the Monal app (quit, not running in background)
- Opening the Monal app

Then, Monal tries to (re-)connect and displays "logging in" / "could not log in" very quickly until the login fails permanently. After that, logging in stops working completely for a while with different clients / webchats. Also, Monal creates another internal account for the Jabber account. 

Client: Monal 2.9.1. (184)
OS: iOS 7.1.2 (11D257)

**Comment by anurodhp** [comment]
I believe this has been fixed in the most recent builds on TestFlight. if you would like to test it an let me know, please sent me an Apple ID email info@monal.im.

**Comment by anurodhp** [comment]
This should be fixed in the latest release.
