### ISSUE TITLE
Chat bubble: Indicate links by adding underline HTTP URL

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#519]
### Description of my issue or feature request:
**Currently**
Monal does not underline links so there is no indicator that there is a link hidden in the messages. Also mouse pointed is not changing when hovering a link.
**Expected**
Links should be underlined and hovering them should change the mouse pointer.

### The Monal version and system version I use:
macOS 10.15.7 + iOS 14.2
Monal 4.9 todays nightly build

### Additional information like screenshots:
No underline or indication this is a clickable link.
![link](https://user-images.githubusercontent.com/5708172/101279943-4d029800-37c6-11eb-806c-5db4b67b790b.png)

**Comment by Echolon** [comment]
Thanks for reporting!

**Comment by anurodhp** [comment]
yup this is definitely a regression as it did work in older monal versions.
