### ISSUE TITLE
No Group OMEMO encyption!

### ISSUE THREAD

**Issue by Peter0961** [anurodhp/Monal#521]
### Description of my issue or feature request:
No OMEMO encryption in my Groups!

### The Monal version and system version I use:
Version 4.9-676

### Additional information like screenshots:

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by licaon-kter** [comment]
This is part of the other issues

/close

**Comment by Echolon** [comment]
Hi Peter, yes you are right, the feature is not yet implemented, but we hope to provided this in the near future, just be a bit patient!

Other then that please check out the labels.
Therefore I will close the issue with reference to many exisiting ones!
