### ISSUE TITLE
Message interaction: Copying of a message actually deletes the message

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#523]
### Description of my issue or feature request:

When swiped left on a message, clicking on "Copy" the message will be copied (as intended), but also deleted (not intended).

### The Monal version and system version I use:
iOS 4.9 Dec 7 2020: 16:24:25

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
Seems to be an ios 12 only bug.... @anurodhp do you have any idea how to fix this?
