### ISSUE TITLE
Login: Loading OMEMO bundels takes long

### ISSUE THREAD

**Issue by Echolon** [anurodhp/Monal#527]
The login procedure now takes quite long loading omemo bundles.
Also on small screens the progress is not shown correctly. The progress numbers should be in a new line.

---
[ X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
will be fixed in 5.0

**Comment by Echolon** [comment]
Shouldnt we keep it open till then?
