### ISSUE TITLE
Smacks keepalive ping

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [anurodhp/Monal#53]
Currently Monal doesn't seem to do some sort of keepalive ping and I have to configure my prosody server to send out smacks pings (r-tags) after 7 minutes of inactivity to keep the connection alive.

If I don't do this my mobile carrier closes the TCP connection after some time (approximately 10-15 minutes) and Monal gets disconnected.

Sending an r-tag every 5 minutes or so (that is the interval Conversation uses for this) would solve this issue. For non-smacks sessions you could send a ping stanza to get the same result.

This could be connected to issue #3 I think.

**Comment by tmolitor-stud-tu** [comment]
I just looked at the code and saw you already implemented this (smacks ping and regular ping if smacks isn't available and even whitespace ping if ping isn't available :) )

But: could you lower the ping timeout to 5 minutes? Currently it is set to 10 minutes, which is far too long for some mobile carriers here :(

**Comment by anurodhp** [comment]
the rough 10  minute ping when in the background is an apple thing.  I can probably add a setting to allow the user to adjust the ping when in the foreground but i suspect that will not do you a lot of good since it will likely disconnect eventually in the background.

**Comment by tmolitor-stud-tu** [comment]
well, such a setting would at least prevent it to get disconnected when in foreground.
But to get this right: apple prevents pings shorter than 10 minutes?

**Comment by evaryont** [comment]
This isn't exactly related, but Android 7.0+ is also moving to aggressively limit background data usage. I believe Google's recommended default setting is only allowing background apps to synchronize once every 15 minutes.

It seems like it's probable that Apple has indeed limited it to no more than once every 10 minutes.

**Comment by tmolitor-stud-tu** [comment]
That's not fully correct.
As far as I know background data is only limited in doze mode which is activated when the device isn't moved and the display turned off for a ceratin amount of time.

See this for a good explanation: https://developer.android.com/training/monitoring-device-state/doze-standby.html

**In the emulator I observed Monal is successfully pinging every minute while in background.**

**Comment by anurodhp** [comment]
I think the smacks changes and the adoption of push should let us close this.

**Comment by tmolitor-stud-tu** [comment]
Yes, I think so :)
After I revised the complete smacks implementation everything worked as intended (at least in the simulator).
