### ISSUE TITLE
Certificate for ios13push.monal.im expired

### ISSUE THREAD

**Issue by aumatt** [anurodhp/Monal#532]
I'm getting this in my XMPP server logs, and push notifications are currently failing:

warn	Forbidding insecure connection to/from ios13push.monal.im because its certificate has expired

Openssl confirms cert is expired:

$ openssl s_client -servername ios13push.monal.im -connect ios13push.monal.im:5269 -starttls xmpp
verify depth is 100
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = ios13push.monal.im
**verify error:num=10:certificate has expired**
notAfter=Dec 12 16:30:42 2020 GMT
verify return:1
depth=0 CN = ios13push.monal.im
notAfter=Dec 12 16:30:42 2020 GMT
verify return:1

I was originally using the beta via Testflight, but installing the App Store version seems to get the same error. I assume the same push server is used.

**Comment by madfoss** [comment]
The same here
https://push.monal.im:5281/push_appserver/v1/health
Certificate expired on 10.12.2020.

**Comment by anurodhp** [comment]
sorry bout this. should  be resolved.
