### ISSUE TITLE
Build 679 not re-generating "eu.siacs.conversations.axolotl.devicelist" node in PubSub service of XMPP server

### ISSUE THREAD

**Issue by surentharp** [anurodhp/Monal#533]
### Description of my issue or feature request:

Hi,
I'm currently using Openfire 4.5.2 XMPP server. When I face OMEMO encrption issue, I delete the "eu.siacs.conversations.axolotl.devicelist" node in the Openfire PubSub Service and reconnect the Account from the Monal. This makes the node "eu.siacs.conversations.axolotl.devicelist" to generate in Openfire and the OMEMO message encryption will also works fine.

In Build 679:
The node "eu.siacs.conversations.axolotl.devicelist" is not generating when I delete the node from Openfire and then reconnect the account from Monal. I have attached compressed file (openfire_monal_video.zip) containing the video demonstration of the "eu.siacs.conversations.axolotl.devicelist" re-generation for both build 678 and the current stable version 658.

### The Monal version and system version I use:
Build 679, Version: 4.9

### Additional information like screenshots:
[openfire_monal_video.zip](https://github.com/anurodhp/Monal/files/5696724/openfire_monal_video.zip)

Edited the issue to correct the version

---
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
Persistent `PEP` / `PubSub` nodes are not meant to be (manually) deleted on servers.
Deleting them manually on the server is not a valid usecase and the outcome is undefined behaviour.

Old monal versions were inefficient and always republished the devicelist on reconnect, this implementation detail changed now and thus the undefined behaviour changed as well.

Nothing we will "fix", because there is nothing broken.

**Second thing: You are using an old beta, build 679 is the current one...**

**Comment by licaon-kter** [comment]
Ok, so what does Monal do then? Shouldn't it put them back? Afaik Conversations does this.

**Comment by tmolitor-stud-tu** [comment]
It does, but not on smacks resume...and only in beta 679, not 678...

**Comment by tmolitor-stud-tu** [comment]
but nontheless: simply deleting some files on the server can have unexpected side effects and should be avoided (unless you **exactly** know what you are doing)

**Comment by surentharp** [comment]
HI,

For you kind information, I was using build 679 for testing.

I have one doubt, what if someone by viewing some random tutorial from youtube/webpage deletes the "eu.siacs.conversations.axolotl.devicelist" node in the server for a particular account.

If Monal doesn't re-generate the node, I think it won't be usable for further OMEMO encryption for that particular account, isn't it?

**Comment by licaon-kter** [comment]
@surentharp as said it might not refresh right away but on a dis/reconnect.

**Comment by surentharp** [comment]
@licaon-kter Noted. Thank you for your response. I will test it out.
