### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by cfraizer** [anurodhp/Monal#535]
### Description of my issue or feature request:
When I attempt to start the App, it crashes with a SQLite3Exception error. Stack backtrace below.
This is my first attempt to launch the app.

### The Monal version and system version I use:
4.9 (682)

### Additional information like screenshots:

[Notebin](https://notebin.de/?1b192753b6658590#J5z4k542LZyWZ5HMfmvVVn4yVqvkhkBoYHuXiFZYuNrh)

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
This seems to be caused by a very old install of Monal (pre 4.5) that was updated to 4.9 recently.

This should fix it: https://github.com/tmolitor-stud-tu/Monal/commit/6d66938325155f3796820109ab15b93d030c68c4

**Comment by Echolon** [comment]
Thanks for the extended reprorting @cfraizer !

**Comment by licaon-kter** [comment]
@cfraizer please use gist.github.com and post only the link not paste here the wall of text

**Comment by Echolon** [comment]
> @cfraizer please use gist.github.com and post only the link not paste here the wall of text

Is alright, we can manage this. Reporting at all is more important.

**Comment by cfraizer** [comment]
> @cfraizer please use gist.github.com and post only the link not paste here the wall of text

@licaon-kter Thanks for the tip! I will definitely do that next time.
