### ISSUE TITLE
OMEMO: Can't decrypt messages received from Conversations client

### ISSUE THREAD

**Issue by metabubble** [anurodhp/Monal#536]
### Description of my issue or feature request:

When receiving OMEMO encrypted messages from a conversations client, I get
Error while decrypting: iv.length != 12

### The Monal version and system version I use:

Version 4.9 (682)

---
[x] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
what version of conversations is your chat partner using?


Am Donnerstag, 31. Dezember 2020, 10:54:37 CET schrieb Christian Hawkins:
> ### Description of my issue or feature request:
> 
> When receiving OMEMO encrypted messages from a conversations client, I get
> Error while decrypting: iv.length != 12
> 
> ### The Monal version and system version I use:
> 
> Version 4.9 (682)
> 
> ---
> [x] I have cross-check this overview
> https://github.com/anurodhp/Monal/issues/322 as well es filtered for
> related labels https://github.com/anurodhp/Monal/labels

**Comment by metabubble** [comment]
Conversations 2.4.2+fcr

**Comment by Echolon** [comment]
Can first you ask to upgrade to the current 2.9.2 please

31 dic. 2020 3:22:27 PM Christian Hawkins <notifications@github.com>:

**Comment by metabubble** [comment]
I advised him to upgrade. he Downlaoded through F-Droid and didn't eralize google play store wouldn't update as it was not purchased there.

All's fine and this issue can be closed.

**Comment by Echolon** [comment]
@metabubble nice! Thank your for reporting - we are happy for all feedback especially currently as lot of changes have been made and are upcoming!
