### ISSUE TITLE
Contact and I lose ability to decrypt OMEMO messages

### ISSUE THREAD

**Issue by jelbana** [anurodhp/Monal#537]
### Description of my issue or feature request:

A contact of mine who uses two clients, Conversations (2.9.2) on Android and Dino (0.2.0) on Linux, and I are continuously losing the ability to decrypt OMEMO messages at random intervals. The only solution has been to remove my account from Monal and then re-add or alternatively for him to remove his account from his client and then re-add. This once again results in OMEMO encrypted messages to work, but seemingly after a day or two of messages one or eventually both clients will no longer be able to decrypt messages and the following error messages occur: 

1

[This message is OMEMO encrypted]

2  - The latter shows up in Dino
Your contact does not trust this device. That means, you might be missing messages.

The contact can confirm that this only occurs with Monal and all OMEMO encrypted messages with contacts using Conversations only does not have this issue.

### The Monal version and system version I use:

4.9 on iOS 14

**Comment by licaon-kter** [comment]
Think my Monal contact experienced this too. Didn't get a chance to see the app myself though.

**Comment by Echolon** [comment]
Hi @jelbana thank you for your report - we are already investigating!

Apart from that, we are looking for more testers, especially on newer devices. If you are eager and motivated that would be a great help! You can take a look at Testflight for example: 

**Support Monal:** https://github.com/anurodhp/Monal/issues/363

**Comment by FriedrichAltheide** [comment]
@jelbana Which 4.9 build are you using exactly?

On the next occurrence: Check if Monal has the correct device fingerprints from your contact. (Should be at least two.)

**Comment by jelbana** [comment]
> @jelbana Which 4.9 build are you using exactly?
> 
> On the next occurrence: Check if Monal has the correct device fingerprints from your contact. (Should be at least two.)

Build number is 680. I checked and there is only 1 key (from Conversations and not Dino). Subsequently my contact removed their account from Dino and then re-added their account. I now see 2 keys and OMEMO is working. I will monitor to see if the aforementioned situation repeats.

**Comment by jelbana** [comment]
Confirming that it happened again. Only 1 key currently from the contact, the contact and I once again no longer see OMEMO messages sent to and from his Dino client.

**Comment by FriedrichAltheide** [comment]
https://github.com/tmolitor-stud-tu/Monal/commit/175b89864ef1cc8e446d36b8b31b0a5e02674bc5

**Comment by jelbana** [comment]
Updating that I still lose the ability to decrypt OMEMO messages after a brief period of time. I am now on build 686. While my contact on Dino and Conversations can see OMEMO messages that I send, after a brief initial period when it works on my side, I then see the following two error messages irrespective of whether the message originates from Conversations or Dino:

"there was an error decrypting this encrypted message (Signal error). To resolve this, try sending an encrypted message to this person. (Error Domain=org.whispersystems.SignalProtocol Code =7 "Invalid Message" UserInfo={NSLocalizedDescription=Invalid Message})"

"there was an error decrypting this encrypted message (Signal error). To resolve this, try sending an encrypted message to this person. (Error Domain=org.whispersystems.SignalProtocol Code =10 "No Session" UserInfo={NSLocalizedDescription=No Session})"
