### ISSUE TITLE
What are the supported XEPs?

### ISSUE THREAD

**Issue by mathiasertl** [anurodhp/Monal#54]
We at jabber.at provide [a list of recommended clients](https://jabber.at/clients/) for our users and show support for a few important XEPs. I couldn't find a list of supported XEPs for monal, so my question is if you support:
- XEP-0027
- XEP-0167
- XEP-0198
- XEP-0280

Of course it would also be great if you could ping us about new versions for your client, especially if they improve support for the mentioned XEPs ;-)

greetings, Mati

**Comment by WarrenBKN** [comment]
add xep-0016, Privacy Lists

  By contrast the simplified blocking command has the same fun limitaions as caller if number blocking does preventing illicit marketeting calls, or email blacllists

**Comment by lgg** [comment]
Note: use this list to create list: https://jabber.at/clients/?os=ios

**Comment by Echolon** [comment]
Is that pull request what you expect?

**Comment by Echolon** [comment]
@mathiasertl 

Today I created a XEP file, which will be filled with information by time. Help is highly appreciated!

https://github.com/anurodhp/Monal/blob/develop/XEPsupport.md

Thanks to @marmistrz

**Comment by haansn08** [comment]
@Echolon The URL https://github.com/anurodhp/Monal/blob/develop/XEPsupport.md stopped working. It is also referenced in the README and should be updated.

**Comment by Echolon** [comment]
Yes, everything is listed in the DOAP file
