### ISSUE TITLE
I cannot join groupchats or see invitation to groupchats

### ISSUE THREAD

**Issue by Hund** [anurodhp/Monal#541]
### Description of my issue or feature request:

My girlfriend uses Ios and Monal and I just invited her to a groupchat, but she never recieves any notification. It's not possible to join any groupchat either. I click on the `+` then `Join a Group Chat`. I enter the name `Familjen` as the room name and then press join, nothing happens. The buttons greys out and that's it.

### The Monal version and system version I use:

* iOS 14.3
* Monal 4.9 (680)

**Comment by Echolon** [comment]
Hi @Hund,

thank you for your report! Unfortunately this feature is not yet implemented sufficiently. And there are attempts to work on this. Hence, I am asking for your patience.

This is also known, please check out the labels: https://github.com/anurodhp/Monal/issues?q=is%3Aissue+is%3Aopen+label%3A%22%3Abusts_in_silhouette%3A+MUC%22

Therefore I will close this as duplicate.
