### ISSUE TITLE
Unable to send photo

### ISSUE THREAD

**Issue by rstefko** [anurodhp/Monal#543]
When I select existing photo or make a new one an error is displayed right after it:

Could not upload file
Upload Error: (null)

Monal version: 4.9 (680)
iOS version: 14.3

The server is Prosody, upload of photos works fine with Conversations. I am not sure where to look for some additional info. There is no error on the server side.

**Comment by Echolon** [comment]
Thank you for your report. Please be reminded that this is a project of volunteers, it might take a while until a fix will come.

If you can reproduce the error, a log file would be really nice.

**Comment by rstefko** [comment]
I have not found out how to get the log from Monal yesterday...
There is file-too-large error in the log. Prosody has only 1MB by default https://modules.prosody.im/mod_http_upload. Conversations probably makes the photos smaller, that's why it worked on Android. So I have made the limit bigger. It works now.

**Comment by Echolon** [comment]
You can find it under `Settings/Logs`

**Comment by rstefko** [comment]
Yes, I have not noticed the buttons on the bottom.
