### ISSUE TITLE
"This server does not appear to support HTTP file uploads [...]"

### ISSUE THREAD

**Issue by Hund** [anurodhp/Monal#544]
### Description of my issue or feature request:

My girlfriend cannot  send any images, when she clicks on the attachment button she recieves a popup with this message:

>This server does not appear to support HTTP file uploads (XEP-0363). Please ask the administrator to enable it.

It works fine for me with Conversations on Android and I can send her pictures as well. Our server is Prosody 0.11.2.

### The Monal version and system version I use:

* iOS 14.3
* Monal 4.9 (680)

**Comment by licaon-kter** [comment]
Any server side logs?

**Comment by FriedrichAltheide** [comment]
Please try to reconnect the account (settings - accounts - reconnect all). After that try again to upload a photo.

**Comment by Hund** [comment]
> Any server side logs?

```
Jan 17 18:48:21 s2sout558944903520	info	Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Jan 17 18:48:21 s2sout558944903520	info	Outgoing s2s connection linuxkompis.se->ios13push.monal.im complete
Jan 17 18:48:22 s2sin5589446e6c30	info	Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Jan 17 18:48:22 linuxkompis.se:saslauth	info	Accepting SASL EXTERNAL identity from ios13push.monal.im
Jan 17 18:48:22 s2sin5589446e6c30	info	Incoming s2s connection ios13push.monal.im->linuxkompis.se complete
Jan 17 18:48:27 c2s558944a98130	info	Client connected
Jan 17 18:48:28 c2s558944a98130	info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Jan 17 18:48:28 c2s558944a98130	info	Authenticated as ***@linuxkompis.se
Jan 17 18:48:37 c2s558943e19ae0	info	Client disconnected: closed
```

> Please try to reconnect the account (settings - accounts - reconnect all). After that try again to upload a photo.

We did that and it didn't do anything. :/

**Comment by tmolitor-stud-tu** [comment]
We need a log of monal created after the "reconnect all".
You can find the logs in Settings --> Logs, tap onto the leftmost icon in the footer to export the file.
You can send the file to thilo@eightysoft.de

**Comment by Hund** [comment]
> We need a log of monal created after the "reconnect all".
> You can find the logs in Settings --> Logs, tap onto the leftmost icon in the footer to export the file.
> You can send the file to [thilo@eightysoft.de](mailto:thilo@eightysoft.de)

Is there some official email address for Monal? It's nothing personal, but I have no idea who you are.

**Comment by Echolon** [comment]
@Hund I can confirm Thilo is an official and trustful developer for Monal. I think @anurodhp can also confirm this, too.

See here his commit history to Monal: https://github.com/anurodhp/Monal/commits/develop

**Comment by tmolitor-stud-tu** [comment]
@Hund you can send it to info@monal.im, too. Anu will forward it to me then.

**Comment by Hund** [comment]
> @Hund I can confirm Thilo is an official and trustful developer for Monal. I think @anurodhp can also confirm this, too.
> 
> See here his commit history to Monal: https://github.com/anurodhp/Monal/commits/develop

Thanks! :) I'll send the email right away.

**Comment by tmolitor-stud-tu** [comment]
I found the bug and committed a fix to the alpha build over here https://github.com/tmolitor-stud-tu/Monal/commit/1edb98c0d405d297658f7f2a49a1846905de3659
This will eventually be in the next stable releases.

**Comment by Hund** [comment]
Thank you! I appreciate it. :)
