### ISSUE TITLE
Messages from JIDs don't appear in chat history

### ISSUE THREAD

**Issue by sith-on-mars** [anurodhp/Monal#545]
I'm using the latest Monal on iOS.

[JID](https://jmp.chat/) is a service providing virtual phone number for sending picture and text messages right from a Jabber account. I quoted this from the original developer of JID.

> JMP provides a phone number for users, which they can then receive text/pictures messages on - these messages arrive from special JIDs representing the sender's phone number, and they are naturally not in the user's contact list (unless they knew who'd be sending them a text/picture message and pre-added them).

When I tried to use JMP for receiving SMS verification code, I could receive notification, but the messages won't show up in my chat history. But they show up in the chat logs instead. Is this because those special JIDs are not in my contact list?

There is also some discussion about the [JMP support for ChatSecure](https://github.com/ChatSecure/ChatSecure-iOS/issues/844), but it seems the developers of ChatSecure hasn't been active.

**Comment by Echolon** [comment]
Hi,

I guess you are right about ChatSecure.

Im not sure if can do anything about thirdparty services here. I think you should get in cobtact with those provideres. But basically Monal supports Message Archive Management.

**Comment by Echolon** [comment]
Does it work with other clients. e.g. Siskin?

**Comment by sith-on-mars** [comment]
On Siskin it works perfectly. JID messages show up in the chat history.

**Comment by sith-on-mars** [comment]
I think there is probably nothing else that the JID author can really do. Do you think adding a setting which allows messages from people who're not on your contact lists should help?

**Comment by Echolon** [comment]
> I think there is probably nothing else that the JID author can really do. Do you think adding a setting which allows messages from people who're not on your contact lists should help?

Yes, please try this!

**Comment by tmolitor-stud-tu** [comment]
@sith-on-mars we will add such a setting, thanks for reporting!

**Comment by tmolitor-stud-tu** [comment]
@FriedrichAltheide did we solve this in the alpha already? Our ios 12 test today added you to my activechats list without me doing something (like it should be).

**Comment by FriedrichAltheide** [comment]
@tmolitor-stud-tu not that I'm aware off

**Comment by tmolitor-stud-tu** [comment]
This should solve the problem, a real-world-test in our alpha build is still pending, though:
https://github.com/tmolitor-stud-tu/Monal/commit/026d17d0c4e330e8f562c60ecc6f7eaf96847adb
