### ISSUE TITLE
Joining group chat not possible currently

### ISSUE THREAD

**Issue by foss-** [anurodhp/Monal#547]
### Description of my issue or feature request:
- click + to join new room
- select `Join a Group Chat`
- enter Group Information: `monal_dev@conference.jabbers.one`
- Click `Join Group`

**Currently**
There are two problems:
1. a password is being requested (expected: do not ask for passwords for rooms not using a password)
2.  leaving the password field blank and pressing `OK` goes back to the previous `Join Group Chat`dialog, so the group can never be joined. Entering anything in the password field also goes back to that dialog view.

### The Monal version and system version I use:
macOS 10.15.7
Monal 5.0 2021-01-23

**Comment by tmolitor-stud-tu** [comment]
yes, group chats are broken in monal 4.9.1, they will work in 5.0 once 5.0 is ready to be released to stable
