### ISSUE TITLE
Prosody: Whitelisting push server doesn't work

### ISSUE THREAD

**Issue by bytehamm3r** [anurodhp/Monal#549]
Basically I try to run a prosody server with disabled s2s functionality, but still preserving a running push service. Now, it seems when using the s2s_whitelist module within prosody, no push notifications reaches the clients...

s2s_whitelist = {
"monal.im";
}

...any ideas?

---
[X] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
yes: the push servers are not monal.im but push.monal.im and 
ios13push.monal.im


Am Sonntag, 24. Januar 2021, 10:26:50 CET schrieb bytehamm3r:
> Basically I try to run a prosody server with disabled s2s functionality, but
> still preserving a running push service. Now, it seems when using the
> s2s_whitelist module within prosody, no push notifications reaches the
> clients...
> 
> s2s_whitelist = {
> "monal.im";
> }
> 
> ...any ideas?
> 
> ---
> [X] I have cross-check this overview
> https://github.com/anurodhp/Monal/issues/322 as well es filtered for
> related labels https://github.com/anurodhp/Monal/labels
