### ISSUE TITLE
XEP-0174: Serverless Messaging

### ISSUE THREAD

**Issue by DanScharon** [anurodhp/Monal#55]
Please add support for [XEP-0174](https://xmpp.org/extensions/xep-0174.html) aka Bonjour-Chat.

**Comment by Echolon** [comment]
@tmolitor-stud-tu also this one?

**Comment by tmolitor-stud-tu** [comment]
Yes, close it

Am 30. Oktober 2020 09:03:24 MEZ schrieb Echolon <notifications@github.com>:
