### ISSUE TITLE
Unnecessarily accessing camera only to attach existing images

### ISSUE THREAD

**Issue by FediVideos** [anurodhp/Monal#550]
### Description of my issue or feature request:

Attaching image requires access to camera, when all it should really need is access to selected images in Photos.

If I deny access to the camera, attempting to attach an image does nothing (doesn't even open Photos).

If I allow access to the camera, attaching images from Photos works as expected.

Note these are existing images I am trying to attach, **not** photos taken with the camera.

### The Monal version and system version I use:

Monal Version 4.9.1 (686)
iPhone iOS 14.4

### Additional information like screenshots:

I never give messenger apps access to camera, I don't know why Monal requires it?

---
[X ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for related labels https://github.com/anurodhp/Monal/labels

**Comment by Echolon** [comment]
@FediVideos thank you for your report. Lets wait for a response of one of the developers

**Comment by anurodhp** [comment]
Thanks for the report. It shouldn’t need camera access to get to photos. It may just be a mistake with an if() statement and it’s asking for both
