### ISSUE TITLE
[Feature Request] Group Chat Bookmarks and autojoin.

### ISSUE THREAD

**Issue by specter1591** [anurodhp/Monal#57]
This feature, although not necessary, would make my life and the lives of others alot easier. Could you add  Group Bookmark support to Monal? [Protocol 0048](http://www.xmpp.org/extensions/xep-0048.html). 

[This has been suggested previously.](https://github.com/anurodhp/Monal/issues/19)

**Comment by anurodhp** [comment]
There are now local bookmarks in the app with auto join as an option. Will adopt the XEP later.
