### ISSUE TITLE
New iTunes releases

### ISSUE THREAD

**Issue by aanodin** [anurodhp/Monal#58]
Hi everyone,
I've just created it to know about your current plans about releases in iTunes. Last update was on 23/03/2016 and many bugs were fixed since that. For example: https://github.com/anurodhp/Monal/issues/49 
I have my own server with HttpFileUpload and I haven't found any other iOS client supporting XEP-0363. Monal supports it, but this very bug (fixed in github) prevents my users from transmitting their files successfully. 
I would appreciate if someone made the newest version released. 

Best regards,
Alexander

**Comment by anurodhp** [comment]
You are right. I am due for a release. I wanted to fix a few more bugs before the next release  but i think i can probably put this one out.

**Comment by anurodhp** [comment]
Testing new release iOS 2.9.2 on test flight. ETA should be early next week after some more  testing.

**Comment by aanodin** [comment]
Thanks for your work :)
