### ISSUE TITLE
Contact List Disappears v2.9.2

### ISSUE THREAD

**Issue by rf600** [anurodhp/Monal#59]
iPhone 7+ on iOS 10.1
Using Monal v2.9.2

Open app and it automatically logs into my xmpp account.
Contact list populates and all is good.
Open another app, ie. mail or safari, then double click to open Monal again, Contact list is empty.

Also, the app is constantly disconnecting and trying to reconnect, but never logs in again. Have to close the app and re-open, only to get the same behavior. Application is not usable now.

This worked fine in v2.9.1

**Comment by anurodhp** [comment]
I am experiencing the same issues myself. I am going to see if something changed in iOS or the ask between builds.

**Comment by anurodhp** [comment]
this might be an issue with iOS 10 and Xcode 8. Damn. 
https://openradar.appspot.com/28734094

**Comment by anurodhp** [comment]
Yeah looks like apple killed it with the latest update 
" 2016-11-08 19:14:52.218427 Monal[7359:2481485] Legacy VoIP background mode is deprecated and no longer supported"

**Comment by anurodhp** [comment]
I've pushed up 2.9.3 . This has resolved the issue for me on on iOS 10.1

**Comment by rf600** [comment]
Thanks! Works for me now also.
