### ISSUE TITLE
[Feature Request] Multi-user chat in desktop client

### ISSUE THREAD

**Issue by ricardobeat** [anurodhp/Monal#60]
It looks like joining group chats is only possible in the iOS client. I'm looking for a replacement to Adium and group chat is a must-have (work environment).

**Comment by anurodhp** [comment]
I am currently working on this.  client can now join Muc. I am fixing several related UI issues behind this as well as just making it more user friendly. Will update the blog soon about this.

**Comment by anurodhp** [comment]
its in the latest beta
