### ISSUE TITLE
Bug in recognizing the end of stanza from inputBuffer, if there is a self-closed XML child element

### ISSUE THREAD

**Issue by horvathj** [anurodhp/Monal#61]
In xmpp.m file there is an error in  nextStanza function:

The server sends the IQ for http upload feature support:

If the inputbuffer contains the start of the IQ:

```
<iq from='upload.montague.tld'
    id='step_02'
    to='romeo@montague.tld/garden'
    type='result'>
  <query xmlns='http://jabber.org/protocol/disco#info'>
    <identity category='store'
              type='file'
              name='HTTP File Upload' />
```

at least until this self closed elemenet, but not the closing iq tag:

```
    <feature var='urn:xmpp:http:upload' />
    <x type='result' xmlns='jabber:x:data'>
      <field var='FORM_TYPE' type='hidden'>
        <value>urn:xmpp:http:upload</value>
      </field>
      <field var='max-file-size'>
        <value>5242880</value>
      </field>
    </x>
  </query>
</iq>
```

then the algorithm wrongly identifies the end of the stanza at the self-closing element!
(Causing:  the client will not be able to upload to the server, because the rest of the stanza will be dropped, and the http upload flag not set to true...)

**Comment by anurodhp** [comment]
yup you are right. its really ode code that i intend to replace with a parser that points to the input stream from ios5. really good catch. thanks!
