### ISSUE TITLE
Cannot add new contacts on an iPad Mini

### ISSUE THREAD

**Issue by sentaidigital** [anurodhp/Monal#65]
If a contact adds me, then it all works fine.  But, there is no control for me to initiate.  I would expect there to be a plus sign (+) next to "Contacts".

See attached screenshots.

![img_0146](https://cloud.githubusercontent.com/assets/481531/20769873/aea5a6d6-b711-11e6-9952-327dc9297e4c.PNG)
![img_0147](https://cloud.githubusercontent.com/assets/481531/20769874/aea5b2ca-b711-11e6-9663-3fac680ae77e.PNG)

**Comment by anurodhp** [comment]
This has been fixed in the most recent refactor.
