### ISSUE TITLE
iOS Group Chat dialog shows server name instead of domain

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#66]
When trying to join a MUC with Monal 2.9.3 ("More" --> "Group Chat"), the account selection shows "user@xmpp-server" instead of "user@domain".

I have an account at the server `yax.im`, which is internally using the SRV host `xmpp.yaxim.org`. When I open the Group Chat dialog in Monal, it shows me "user@xmpp.yaxim.org" as the account.

**Comment by anurodhp** [comment]
this has been fixed
