### ISSUE TITLE
iOS: "Active Chats" counter not reset on "Close All"

### ISSUE THREAD

**Issue by ge0rg** [anurodhp/Monal#67]
Initial situation:

* I have multiple active chats with unread messages
* the "Active Chats" tab and Monal app icon show a :red_circle: (2) overlay for unread messages
* I push the "Close All" button in "Active Chats"

Desired effect:

* the (2) unread messages overlay is reset

Actual effect:

* the (2) unread messages overlay remains
* there is no way to reset the counter until I receive a new message from each of the cleared chat partners

**Comment by anurodhp** [comment]
This should be resolved.
