### ISSUE TITLE
Create Homebrew Cask formula

### ISSUE THREAD

**Issue by joelpurra** [anurodhp/Monal#68]
I don't use the OS X app store; I use the command line tools [Homebrew](http://brew.sh/) and [Homebrew Cask](https://caskroom.github.io/) instead. How about [adding a `monal` cask formula](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) to open up this distribution channel?

This would require uploading builds (for example a `.zip` or `.dmg` file) to a public location of your choice, so the brew cask client can download it. Installation would then look like this.

```shell
brew cask install monal
```

The installation file's sha256 checksum is checked against the value in the formula before installing the `.app` to the right place. [Support for developer gpg signature](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/gpg.md) is coming.

**Comment by anurodhp** [comment]
assuming this PR is accepted: 
https://github.com/caskroom/homebrew-cask/pull/42664
 this will work soon.

**Comment by joelpurra** [comment]
@anurodhp: tested, and it works very well -- both `brew` installation and Monal execution. Thanks =)
