### ISSUE TITLE
Messages not received

### ISSUE THREAD

**Issue by muneikh** [anurodhp/Monal#71]
Not sure, if it is part of the future implementation but here is what I have experienced:

1. Two iOS devices with Monal v2.9.3 installed from AppStore.
2. Using Ejaberred for XMPP.
3. Send message from device A to B (while device B app is stopped)
4. Device B does not receive message or pull archived message when the app is not connected.

So, the device does not receive messages when it is not connected. Is it only me experiencing it or maybe I am missing something?

**Comment by mmehrle** [comment]
Same happening on my end. I am sending messages from A to B (running Monal) and it is received. Then I lot out of A and log into C. I send a message from C to B (again running Monal) and it is not received. All other clients do receive messages from the same C account, e.g. SecureChat on iOS or Xabber or Conversations on Android.

**Comment by anurodhp** [comment]
Im looking at this right now .  I am hoping the shift to push messages will resolve this issue.

**Comment by anurodhp** [comment]
Ive been working on this. Would you be interested in testing the latest beta to see if this has been resolved?

**Comment by anurodhp** [comment]
Closing this since I have deployed push. please reopen if it is still an issue.
