### ISSUE TITLE
Monal attachment not available (XEP - 0363)

### ISSUE THREAD

**Issue by stephendaniel** [anurodhp/Monal#72]
Hi, I'm using existing Monal app in app store. I use ejabberd as the xmpp server. I already activate the mod_http_upload in ejabberd. I try to send attachment in Monal app, but it gives me this error :
"This server does not appear to support HTTP file uploads (XEP-0363). Please ask the administrator to enable it. You can also link to DropBox in settings and use that to share files". So how can I send attachment in Monal with mod_http_upload already activated in ejabberd server?

**Comment by anurodhp** [comment]
Mac or iOS? Latest version?  Generally it can detect if mod http is enabled. It seems like it's not doing it. There was a bug in an earlier release that didn't do it right. I want to and sure you are on a version that does support it. Does http upload work with any other client?

**Comment by stephendaniel** [comment]
Both for Mac and iOS, I use the one in App Store. Http Upload work with other client in Android.

**Comment by shravanteegala** [comment]
Iam  waiting for long time for http file upload in my IOSProject. using XEP-0363 XMPPExtension.
Plz  help me.

**Comment by thundergreen** [comment]
Hi guys. i installed monal but it wont show me pic after httpupoad but a link. Can we have inband view?

**Comment by anurodhp** [comment]
looking at this more I think this might be a duplicate of #61 which I just fixed.  I hope to include better error handing and display in the next release so hopefully all of this poking in the dark will be a thing of the past.

**Comment by anurodhp** [comment]
Hi I have updated the Mac beta with a build that has a server details option under the accounts menu. could you see what it  sees as features on the server?

**Comment by anurodhp** [comment]
This should be fixed in the latest release.
