### ISSUE TITLE
Message Logs Disappear

### ISSUE THREAD

**Issue by everestf** [anurodhp/Monal#73]
On my iPad (a Mini 2 running iOS 10.1.2 and Monal 2.9.3), when I go to chat logs it gives me a list of my contacts, and "(null)". However, when I go to a contact and select one of the dates, the header displays (null)([date]) and the screen is grey and does not show any messages.

**Comment by tmolitor-stud-tu** [comment]
I see the same bug on a friend's iPhone. Let me know if you need some more info to debug this further :)

**Comment by anurodhp** [comment]
Working on this now.  Looks like a  combo of a few bugs.
