### ISSUE TITLE
macOS Server Messages and Monal

### ISSUE THREAD

**Issue by MichelStam** [anurodhp/Monal#81]
guys,

I've been trying to get Monal/iOS and Monal/OSX Server to play nice, but I don't seem to be able to get any connection whatsoever, regardless of the combination of settings I choose. I've tried with SSL, TLS and self-signed certificate. I'm using a certificate from Let's Encrypt on the chat server. Configuration has been slightly modified to allow authentication against an LDAP backend.

Can you tell me which authentication types are supported, and maybe if there's any way I can get Monal to give me some debugging information?

Regards,

Michel

**Comment by anurodhp** [comment]
Adding a error log/debugging window and will update the beta on the website soon.

**Comment by MichelStam** [comment]
Thanks!

Michel Stam

**Comment by Echolon** [comment]
Hi,

@MichelStam 

Is this still an issue / question?

**Comment by Echolon** [comment]
I will close this issue. Please report if there is still something happening.
