### ISSUE TITLE
MacOS version 1.5, can't input full jabberI into Jabber ID label

### ISSUE THREAD

**Issue by jerry-chao** [anurodhp/Monal#82]
# Monal Version(MacOS)
- Version 1.5 (56)

when i input test@localhost and press save, it will reponse test@ to me, how can i fix it, thanks

**Comment by anurodhp** [comment]
I just tried this can you elaborate where you see this issue? Is it in the account creation or when you send/receive  messages?

**Comment by anurodhp** [comment]
closing this as there hasn't been an update in over a year
