### ISSUE TITLE
Messages are not always being received on iOS

### ISSUE THREAD

**Issue by LouDS** [anurodhp/Monal#83]
Prior to installing v2.9.3 I was on v2.9.1 which worked without issues, I understand that the build for v2.9.2 had issues and the developer had to rebuild using iOS 9 SDK  due to the VOIP socket being depreciated by apple.  With version v2.9.3 I'm seeing very inconsistent results, some messages I send are not received when I reply to a conversation that someone else started.  Perhaps there is still issues with background working.  Is there a way for users to have access to version 2.9.1 until the instability is fixed?

One example of inconsistency is as follows:-
I get messages like for instance someone will ping me that I’ve not got an open window to in Monal or my desktop IM client, I see the first ping on Monal, but then the following pings do not show on the Monal app, I see the whole thread pop up on Pidgin, including the first Hi message that I saw on Monal, but the conversation then seems to cut off from Monal and only continue on the Pidgin client.

Regards
Louise

**Comment by LouDS** [comment]
How can I get in touch with this developer?

**Comment by anurodhp** [comment]
I am here, I am just incredibly busy with personal stuff at the moment.

**Comment by LouDS** [comment]
Hi  thanks for replying, yes its not looking good for the future on the app, but hoping when you have some time that you might work out a fix.

Regards
Louise

**Comment by anurodhp** [comment]
A question about this, what is the priority of pidgin and monal (you can see this in settings). The XMPP server will send messages based on the higher priority (higher number).   Looking at pidgin, it seems there has been some issues with it and  priority (https://developer.pidgin.im/ticket/1345) . Monal defaults to 5 and you can raise it if you want to guarantee messages arrive (try priority 100)

**Comment by LouDS** [comment]
Hi Anu, that bug is over 11 years old and last comment on it was over 3 years ago, its also been highlighted as enhancement fixed.  Additionally we have android users using xabber and pidgin and do not see message non deliveries on mobile and desktop when they are running at the same time.  So I see this issue with Monal and not Android, Monal v2.9.1 which worked without issues.

Regards
Louise

**Comment by anurodhp** [comment]
Im going to install pidgin on a vm and take a look. Its quite puzzling.

**Comment by anurodhp** [comment]
Testing this with pidgin, I see that when I set the priority to >0 on monal which is the default the opposite happens. All the messages go to Monal. In monal, could you try setting the resource value to 0, log out and see if it still happens?

**Comment by LouDS** [comment]
I still don't see this working

**Comment by anurodhp** [comment]
made another change the other day. Anyluck?

**Comment by LouDS** [comment]
Hi if you've got a beta version where can I install it from on my device?

**Comment by anurodhp** [comment]
There are regular betas. Send an email with your Apple ID to info@monal.im and I will add you the TestFlight beta program.

**Comment by LouDS** [comment]
Hi is it my email address that I use with my xmpp server or is it just to send me the beta app if so can you send it to my personal email louisedavies16@hotmail.co.uk<mailto:louisedavies16@hotmail.co.uk> ??

regards
Louise

Sent from my iPhone

On 8 Jan 2018, at 20:35, Anu Pokharel <notifications@github.com<mailto:notifications@github.com>> wrote:


There are regular betas. Send an email with your Apple ID to info@monal.im<mailto:info@monal.im> and I will add you the TestFlight beta program.

**Comment by LouDS** [comment]
Hi no change to behaviour with the updated verson.


Regards

Louise

________________________________
From: TestFlight <no_reply@email.apple.com>
Sent: 21 March 2018 12:53:26
To: louisedavies16@hotmail.co.uk
Subject: "Monal - Free XMPP chat 3.0 (234)" for iOS is now available to test




[Monal - Free XMPP chat, app icon]



Monal - Free XMPP chat 3.0 (234) for iOS is ready to test


What To Test:



Lots of fixes and updates since the last build.




To test this app, open TestFlight<https://beta.itunes.apple.com/v1/app/317711500?build=26797883> on your iOS device using iOS 9.3 or later and install the update.




In order to use Monal - Free XMPP chat, you agree that crash data as well as statistics about how you use Monal - Free XMPP chat will be provided to Anurodh Pokharel and linked to your email address. Anurodh Pokharel may contact you regarding this information. You should review the Terms and Conditions of the TestFlight program, as well as the terms, policies, and practices of Anurodh Pokharel. Beta apps may crash or result in data loss.



[https://itunesconnect.apple.com/itc/images/email/spacer.gif]

TestFlight is a service provided by Apple.
Terms of Service<http://www.apple.com/support/itunes/legal/terms.html> | Privacy Policy<http://www.apple.com/legal/privacy/> | Unsubscribe<mailto:bugs@monal.im?subject=Unsubscribe%20from%20TestFlight>
Copyright © 2018 Apple Inc. One Apple Park Way
Cupertino, CA 95014, United States.
        [https://itunesconnect.apple.com/itc/images/email/spacer.gif]


[http://outsideapple.apple.com/img/APPLE_EMAIL_LINK/spacer4.gif?v=2&a=ZZrZKdgoJBHTiCNXcXW49104QB%2F6U8LT89%2Foy5J8E7JkyXJUnAIbeIpFUZKopOOY7RcLgCjKDPJihDefPnNhM12Q6YBnQgQmmZYgiPQAdPJGJZU7SuiLA%2FO14f2WrUyRZIV6C1Yt2BoJFRQoXUVxcmEZX0rO%2BhQ%2BZnp9%2FCVaZ9bWZQ0opW9S8EmJBDTg63xjn9q%2FyBimXd3SfnDE08D9azMbPLOHUeSMmBQMjRRLJn5LglyskLUMI%2BV%2Fy0LMASI0rz4lTbs5pEt0MltNxRdKQpwUYzuT%2F58QXB%2FFpiCfVNOAdszfUr6sFveD4%2Bmad7J1WXG9%2B3DT8DoW6FwqBRR3AKUZBG7Ft0FJ2myzHvFbP7fA9frW6o2bSUU8q85iifKzLhYFvX91ax6cU9Uru2o7RRhZ2R3fMwYxLBFdjSXB%2FK8%3D]

**Comment by anurodhp** [comment]
Hi, 
Ive put a lot of work into message synch in the last few months. Have you seen any improvement?  At the very least push notifications should force the clients to be in synch now.

**Comment by LouDS** [comment]
Thank but Oracle are all using Slack now which has mobile app so we have moved away from other im clients.

Regards

Sent from my iPhone

On 9 Dec 2018, at 03:20, Anu Pokharel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Ive put a lot of work into message synch in the last few months. Have you seen any improvement? At the very least push notifications should force the clients to be in synch now.

**Comment by anurodhp** [comment]
thanks for following up.
