### ISSUE TITLE
Question about message carbons

### ISSUE THREAD

**Issue by azbok** [anurodhp/Monal#84]
I have Monal 2.9.3, iOS 11.0.1, and a fairly recent version of OpenFire.  My pidgin works with carbons but Monal doesn't.  Is there anything I can check to figure out why the message carbons aren't working?

**Comment by anurodhp** [comment]
Hoping some of the fixes in the current beta will address this. You should be able to see if carbons are enabled and the fixes should improve reliability

**Comment by anurodhp** [comment]
I havent tested open fire but on every other server, carbons is working fine now with the recent fixes. Would you be interested testing the current beta and helping me verify your bug is fixed?

**Comment by azbok** [comment]
Hi, yes I'd be interested in testing out the beta.  Sorry for the delay,
the email got lost in the mix!

**Comment by anurodhp** [comment]
please send your apple id to info@monal.im and i can add you to the beta test group
