### ISSUE TITLE
[macOS] Presence message text overlapping username in contacts list display

### ISSUE THREAD

**Issue by housetrotter** [anurodhp/Monal#85]

**Comment by anurodhp** [comment]
iOS or OSX?

**Comment by housetrotter** [comment]
Apologies for the delayed response, this is on OS X. I’ve blocked out the identifying info below but you can see the presence text and name overlapping below.

**Comment by anurodhp** [comment]
Hmm I dont see an image attached but am going to assume this is with a longer presence text

**Comment by Echolon** [comment]
@housetrotter 

Is this still existent? Can you provide a screenshot please?

**Comment by foss-** [comment]
@Echolon / @anurodhp  can you close this one? Was filed against pre catalyst build which was unstable. Catalyst build does not overlap contact name and presence message.
