### ISSUE TITLE
Window activation … something … uhm, title.

### ISSUE THREAD

**Issue by da2x** [anurodhp/Monal#91]
Version 2.0 (68).

0. Open any other app in fullscreen mode, and switch back to Monal in regular windowed mode
1. Open two active chats
2. Select chat/contact 1 in contacts
3. Switch to active chats and select chat/contact 2
4. Switch back to contacts and confirm that chat/contact 1 is selected
5. Now, switch to the other workspace (where the fullscreen app is located)
6. Switch back to the desktop with Monal on

Expected: to see chat/contact 1 selected in the Monal window.

Actual: chat/contact 2 is displayed instead.

**Comment by anurodhp** [comment]
yup looks like a bug. good catch.

**Comment by anurodhp** [comment]
this should be fixed now. putting out a new beta today
