### ISSUE TITLE
[macOS] Panels not resizeable

### ISSUE THREAD

**Issue by da2x** [anurodhp/Monal#92]
Version 2.0 (68)

Can’t resize the sidepanel. The line between the contacts/chats list and the conversation view shows a horizontal resize mouse cursor hand, but it isn’t draggable. Being able to resize or collapse this area is important when using Monal in a half-width full-screen window.

**Comment by foss-** [comment]
2.2 (100) beta persisting. Although low priority it's irritating and should not be that hard to fix.

**Comment by Echolon** [comment]
Hi @da2x 

is this still existent in the current macOS release?

**Comment by foss-** [comment]
persisting

**Comment by anurodhp** [comment]
resizing is possible in catalyst.  though the side bar has a max width and the minimum width isn't actually useful.

**Comment by foss-** [comment]
should this still be closed? I think it's better to proceed with a new clean issue which accurately describes the correct problem remaining in catalyst.

**Comment by anurodhp** [comment]
Closing. The current app is totally different from the old Mac app
