### ISSUE TITLE
Authenticating google talk results in error

### ISSUE THREAD

**Issue by bronzehedwick** [anurodhp/Monal#94]
Google responds with the following error:

![image-1](https://user-images.githubusercontent.com/637174/36169193-8e134334-10c9-11e8-848d-a8086a1a112b.jpg)

I found this blog post that seems to address the issue: https://blog.cloudrail.com/solving-disallowed_useragent-for-google-services/

**Comment by anurodhp** [comment]
Ive updated the client. Will close this after release.

**Comment by rlpietraszek** [comment]
Wondering if you have a timeline on this? Would love to use the client!

**Comment by anurodhp** [comment]
I can add you to the beta group if you would like to test it. Next release turned into a huge update. It’s the third major release in ten years. Send your Apple ID to info@Monal.im that said, googles xmpp has progressively gotten worse and doesn’t support push so while it will work, it may not be a good experience anymore.

**Comment by rlpietraszek** [comment]
Gotcha... didn’t know that about push. Honestly if they don’t support push any more then it won’t work for my purposes. Guess I’ll have to keep using their crummy client. Thanks anyway, I appreciate the reply.

**Comment by anurodhp** [comment]
If you need push the only thing that will work for google is hangouts. They don’t support xmpp push

**Comment by anurodhp** [comment]
Fixed in the latest release.
