### ISSUE TITLE
URLs in chat should not automatically trigger HEAD requests

### ISSUE THREAD

**Issue by patrixl** [anurodhp/Monal#95]
Hi, just noticed this while chatting:

Issue:
When a http or https URL appears in chat, whether sent or received, Monal will automatically send a HEAD request to this URL. This is undesirable from a privacy standpoint and also offers no benefits such as link previews. In the case where there would be benefits, there should be an option to disable that.

Version: version 3.0 (234) as well as current version in App Store

How to reproduce: Send or receive a message containing a http or https URL. I noticed that when the url's protocol part is all caps, e.g. HTTPS://monal.im, HEAD requests are not triggered.

**Comment by anurodhp** [comment]
This used to be off by default but a lot of people expect it. If you go to display there is an option to turn it off under inline images.

**Comment by patrixl** [comment]
Thanks for the reply.

However:
1- This is a HEAD request for every link, and I've never seen an image preview, so I'm not sure what this is offering me
2- I don't see the option about inline images, on the App store version or the latest beta that was just released...

**Comment by anurodhp** [comment]
on the beta look under display. there is a checkbox for show inline images.  The reason it needs to look for all links is that not all images will have an obvious extension especially cloud hosted ones. i need to improve the code for that because  I know it leaks IP. I am planning on limiting it to people in your roster. i think that would be a happy compromise.

**Comment by patrixl** [comment]
Alright so it seems this option was available only on the macOS client and not the iOS. And as discussed over email, it should be added to the iOS client in the future.

That's much better and acceptable!

Thanks
