### ISSUE TITLE
RFCs and XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [anurodhp/Monal#96]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by Echolon** [comment]
@Neustradamus 

Is your issue an duplicate of this actually? 

**What are the supported XEPs?** #54

**Comment by Neustradamus** [comment]
@Echolon: I request a document here which will be updated all time :)
The previous ticket, is only a question ah ah

**Comment by Echolon** [comment]
Is that pull request what you expect?

**Comment by Neustradamus** [comment]
A document with all feature details:
- all XEPs with VERSION (XEP-XXXX v1.2)
- all RFCs

**Comment by Echolon** [comment]
@Neustradamus 

Today I created a XEP file, which will be filled with information by time. Help is highly appreciated!

https://github.com/anurodhp/Monal/blob/develop/XEPsupport.md

Thanks to @marmistrz

**Comment by Neustradamus** [comment]
@Echolon, @marmistrz, A very good start, thanks!

You have forgotten RFCs, can you add RFCs too?
